STYLE: clearly document which scripts contain user-configurable settings
- unify cd, check for the cwd and error message

diff --git a/Allclean b/Allclean
--- a/Allclean
+++ b/Allclean
@@ -4,7 +4,7 @@
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
-#    \\/     M anipulation  | Copyright (C) 2016 OpenCFD Ltd.
+#    \\/     M anipulation  | Copyright (C) 2016-2017 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
@@ -26,26 +26,24 @@
 #     Allclean
 #
 # Description
-#     Clean script for third-party applications and libraries
+#     Clean script for ThirdParty applications and libraries
 #
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# run from third-party directory only
-cd ${0%/*} || exit 1
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+# Run from third-party directory only
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
     exit 1
 }
 # . etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
-Script=${0##*/}
-
 usage() {
     exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
-Usage: $Script [OPTION] [<platform> [ ... <platformN> ]]
+Usage: ${0##*/} [OPTION] [<platform> [ ... <platformN> ]]
 options:
   -all              remove all platforms directories.
   -current          clean the current platform ($WM_OPTIONS).
@@ -60,14 +58,15 @@ USAGE
 }
 
 # Print help message
-if [ "$1" = "-h" -o "$1" = "-help" ]; then
+if [ "$1" = "-h" -o "$1" = "-help" ]
+then
     usage
 fi
 
 #------------------------------------------------------------------------------
 
 # Clean various packages via 'distclean'
-for i in openmpi-* ADIOS-* metis-*
+for i in openmpi-* metis-* adios-* ADIOS-*
 do
     [ -d "$i" ] && (
         echo
@@ -105,12 +104,6 @@ fi
 #
 # Clean platforms directories
 #
-if [ "$#" -ge 1 ]
-then
-    echo
-    echo "Clean platforms/sub-directories"
-fi
-
 removePlatform()
 {
     local platform="$1"
@@ -125,6 +118,11 @@ removePlatform()
     fi
 }
 
+if [ "$#" -ge 1 ]
+then
+    echo
+    echo "Clean platforms/sub-directories"
+fi
 
 # Optionally cleanup platforms specified from the arguments
 while [ "$#" -ge 1 ]
diff --git a/etc/relocateQt b/etc/relocateQt
--- a/etc/relocateQt
+++ b/etc/relocateQt
@@ -28,19 +28,19 @@
 # Description
 #     Change prefix when relocating QT installation
 #
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-unset qtVERSION # No default version
-
-#------------------------------------------------------------------------------
-# Run from third-party directory only
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+# Run from third-party (parent) directory only
+wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : current directory is not \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
     exit 1
 }
 . etc/tools/ThirdPartyFunctions
 . etc/tools/QtFunctions
+#------------------------------------------------------------------------------
+unset qtVERSION # No default version
 #------------------------------------------------------------------------------
 usage() {
     exec 1>&2
diff --git a/makeCCMIO b/makeCCMIO
--- a/makeCCMIO
+++ b/makeCCMIO
@@ -4,7 +4,7 @@
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright (C) 2011-2016 OpenFOAM Foundation
-#    \\/     M anipulation  |
+#    \\/     M anipulation  | Copyright (C) 2016-2017 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
@@ -28,29 +28,28 @@
 # Description
 #     Build CD-adapco's ccmio library
 #
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Get version info
+# Run from third-party directory only
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
+    exit 1
+}
+[ -n "$FOAM_EXT_LIBBIN" ] || {
+    echo "Error (${0##*/}) : \$FOAM_EXT_LIBBIN not set"
+    echo "    Check your OpenFOAM environment and installation"
+    exit 1
+}
+. etc/tools/ThirdPartyFunctions
+#------------------------------------------------------------------------------
+# libccmio version from OpenFOAM etc/config.sh file
 . $WM_PROJECT_DIR/etc/config.sh/functions
 _foamSource $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/ccmio)
 
 ccmioPACKAGE=${ccmio_version:-libccmio-2.6.1}
 targetType=lib
-
-#------------------------------------------------------------------------------
-# Run from third-party directory only
-cd ${0%/*} || exit 1
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
-    exit 1
-}
-[ -n "$FOAM_EXT_LIBBIN" ] || {
-    echo "Error: FOAM_EXT_LIBBIN not set"
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 usage()
 {
@@ -78,7 +77,6 @@ USAGE
     exit 1
 }
 #------------------------------------------------------------------------------
-
 
 # Parse options
 while [ "$#" -gt 0 ]
diff --git a/makeCGAL b/makeCGAL
--- a/makeCGAL
+++ b/makeCGAL
@@ -4,7 +4,7 @@
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright (C) 2012-2016 OpenFOAM Foundation
-#    \\/     M anipulation  | Copyright (C) 2016 OpenCFD Ltd.
+#    \\/     M anipulation  | Copyright (C) 2016-2017 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
@@ -34,8 +34,18 @@
 #     simply specify a 'system' version. For example,
 #         makeCGAL boost-system gmp-system
 #
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Get CGAL, boost and gmp/mpfr versions
+# Run from third-party directory only
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
+    exit 1
+}
+. etc/tools/ThirdPartyFunctions
+#------------------------------------------------------------------------------
+# CGAL, boost and gmp/mpfr versions from OpenFOAM etc/config.sh file
 . $WM_PROJECT_DIR/etc/config.sh/functions
 unset -f _foamAddPath _foamAddLib _foamAddMan   # get settings only
 unset BOOST_ARCH_PATH CGAL_ARCH_PATH            # purge current values
@@ -48,24 +58,13 @@ boostPACKAGE=${boost_version:-boost-system}
 gmpPACKAGE=${gmp_version:-gmp-system}
 mpfrPACKAGE=${mpfr_version:-mpfr-system}
 cgalPACKAGE=$cgal_version
-
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
-#------------------------------------------------------------------------------
-Script="${0##*/}"
 usage() {
     exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
 
-usage: $Script [OPTION] [CGAL-VERSION] [boost-VERSION] [gmp-VERSION] [mpfr-VERSION]
+usage: ${0##*/} [OPTION] [CGAL-VERSION] [boost-VERSION] [gmp-VERSION] [mpfr-VERSION]
 options:
   -cmake PATH       with cmake from the path given
   -gcc              force gcc/g++ instead of the values from \$WM_CC, \$WM_CXX
@@ -82,7 +81,7 @@ options:
 Normally builds against ThirdParty boost and gmp/mpfr when possible.
 To override this behaviour (and use the system boost and/or gmp/mpfr),
 simply specify a 'system' version. For example,
-    $Script boost-system gmp-system
+    ${0##*/} boost-system gmp-system
 
 Use gmp-none to disable use of gmp/mpfr (eg, not available)
 
diff --git a/makeCmake b/makeCmake
--- a/makeCmake
+++ b/makeCmake
@@ -4,7 +4,7 @@
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
-#    \\/     M anipulation  | Copyright (C) 2016 OpenCFD Ltd.
+#    \\/     M anipulation  | Copyright (C) 2016-2017 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
@@ -28,19 +28,19 @@
 # Description
 #     Build script for cmake
 #
-#------------------------------------------------------------------------------
-# Special purpose script, no default version.
-unset cmakePACKAGE
-
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
 # Run from third-party directory only
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
     exit 1
 }
 . etc/tools/ThirdPartyFunctions
+#------------------------------------------------------------------------------
+# Special purpose script - no default version.
+unset cmakePACKAGE
 #------------------------------------------------------------------------------
 usage() {
     exec 1>&2
@@ -53,7 +53,7 @@ options:
   -help
 
 * build cmake
-      ${cmakePACKAGE:-'unspecified version'}
+      ${cmakePACKAGE:-'unspecified'}
 
 USAGE
     exit 1
diff --git a/makeFFTW b/makeFFTW
--- a/makeFFTW
+++ b/makeFFTW
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2016 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2016-2017 OpenCFD Ltd.
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # License
@@ -28,24 +28,24 @@
 # Description
 #     Build script for FFTW
 #
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Get FFTW versions
+# Run from third-party directory only
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
+    exit 1
+}
+. etc/tools/ThirdPartyFunctions
+#------------------------------------------------------------------------------
+# FFTW version from OpenFOAM etc/config.sh file
 . $WM_PROJECT_DIR/etc/config.sh/functions
 unset -f _foamAddPath _foamAddLib _foamAddMan # get settings only
 
 _foamSource $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/FFTW)
 
 fftwPACKAGE=${fftw_version:-fftw-system}
-
-#------------------------------------------------------------------------------
-# Run from third-party directory only
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 usage() {
     exec 1>&2
diff --git a/makeGcc b/makeGcc
--- a/makeGcc
+++ b/makeGcc
@@ -4,7 +4,7 @@
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright (C) 2011-2016 OpenFOAM Foundation
-#    \\/     M anipulation  | Copyright (C) 2016 OpenCFD Ltd.
+#    \\/     M anipulation  | Copyright (C) 2016-2017 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
@@ -40,8 +40,18 @@
 #
 #         WM_COMPILER=Gcc51 ./makeGcc -system
 #
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# get default GCC, mpfr, gmp and mpc versions
+# Run from third-party directory only
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
+    exit 1
+}
+. etc/tools/ThirdPartyFunctions
+#------------------------------------------------------------------------------
+# Default GCC, mpfr, gmp and mpc versions from OpenFOAM etc/config.sh file
 WM_COMPILER_TYPE=ThirdParty       # ensure we get the correct compiler settings
 : ${WM_COMPILER:=Gcc}             # this will still fail if 'Clang' was set
 
@@ -52,25 +62,13 @@ gmpPACKAGE=${gmp_version:-gmp-system}
 mpfrPACKAGE=${mpfr_version:-mpfr-system}
 mpcPACKAGE=${mpc_version:-mpc-system}
 gccPACKAGE=$gcc_version
-
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
-#------------------------------------------------------------------------------
-Script=${0##*/}
-
 usage() {
     exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
 
-usage: $Script [OPTION] [gcc-VERSION] [gmp-VERSION] [mpfr-VERSION] [mpc-VERSION]
+usage: ${0##*/} [OPTION] [gcc-VERSION] [gmp-VERSION] [mpfr-VERSION] [mpc-VERSION]
 options:
   -multilib         for 64-bit systems with 32-bit support required
   -no-multilib      for 64-bit systems without 32-bit support (DEFAULT)
diff --git a/makeLLVM b/makeLLVM
--- a/makeLLVM
+++ b/makeLLVM
@@ -4,7 +4,7 @@
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright (C) 2011-2016 OpenFOAM Foundation
-#    \\/     M anipulation  | Copyright (C) 2016 OpenCFD Ltd.
+#    \\/     M anipulation  | Copyright (C) 2016-2017 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
@@ -30,28 +30,30 @@
 #
 # Note
 #    - Ensure that you always use matching versions between llvm and clang.
-#    - The LLVM components reside in the LLVM tools/ subdirectory
+#    - LLVM components such as clang reside in the LLVM tools/ subdirectory
 #
-#    Example, building from svn repository:
-#      1) Checkout LLVM:
-#            svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm-svn
+#    For example, when building from tar files (version 3.8.0)
 #
-#      2) Checkout Clang, in the correct location
-#            cd llvm-svn/tools
-#            svn co http://llvm.org/svn/llvm-project/cfe/trunk clang
-#            cd -
-#
-#    Example, building from tar files (version 3.8.0)
-#    - Unpack LLVM:
-#        tar -Jvf llvm-3.8.0.src.tar.xz
+#    1) Unpack LLVM:
+#        tar -xJvf llvm-3.8.0.src.tar.xz
 #        mv llvm-3.8.0.src  llvm-3.8.0
 #
-#    - Unpack Clang (also know as cfe):
-#        tar -Jvf cfe-3.8.0.src.tar.xz
+#    2) Unpack Clang (also know as cfe):
+#        tar -xJvf cfe-3.8.0.src.tar.xz
 #        mv cfe-3.8.0.src  llvm-3.8.0/tools/clang
 #
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Get default llvm/clang version
+# Run from third-party directory only
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
+    exit 1
+}
+. etc/tools/ThirdPartyFunctions
+#------------------------------------------------------------------------------
+# LLVM/Clang version from OpenFOAM etc/config.sh file
 WM_COMPILER_TYPE=ThirdParty       # ensure we get the correct compiler settings
 WM_COMPILER=Clang                 # force values for 'clang'
 
@@ -59,16 +61,6 @@ WM_COMPILER=Clang                 # force values for 'clang'
 _foamSource $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/compiler)
 
 llvmPACKAGE=$clang_version
-
-#------------------------------------------------------------------------------
-# run from third-party directory only
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 usage() {
     exec 1>&2
diff --git a/makeMesa b/makeMesa
--- a/makeMesa
+++ b/makeMesa
@@ -32,22 +32,26 @@
 #     Building with mesa-12.x.x fails to create an include/GL directory and
 #     an "osmesa.h" file. Both make it fairly useless for off-screen VTK.
 #
-#     Building with mesa-11.x is fine and mesa-13.x also seems to be okay.
+#     Building with mesa-11.x and mesa-13.x seem to be okay.
 #
-#------------------------------------------------------------------------------
-# Special purpose script, no default version.
-unset mesaPACKAGE
-
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
 # Run from third-party directory only
-cd ${0%/*} || exit 1
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
     exit 1
 }
 . etc/tools/ThirdPartyFunctions
+#------------------------------------------------------------------------------
+# MESA version from OpenFOAM etc/config.sh file
+. $WM_PROJECT_DIR/etc/config.sh/functions
+unset -f _foamAddPath _foamAddLib               # get settings only
+unset vtk_version mesa_version                  # purge current values
+
+_foamSource $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/vtk)
+mesaPACKAGE=$mesa_version
 #------------------------------------------------------------------------------
 usage() {
     exec 1>&2
@@ -207,4 +211,4 @@ adjustMESA()
     exit 1
 }
 
-# ----------------------------------------------------------------- end-of-file
+# -----------------------------------------------------------------------------
diff --git a/makeParaView b/makeParaView
--- a/makeParaView
+++ b/makeParaView
@@ -33,27 +33,25 @@
 #
 #     Note the capitalization of ParaView in the directory names.
 #
+# ------------------------------------------------
+# SOME USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Get ParaView_VERSION location from OpenFOAM config file
+# Run from third-party directory only
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
+    exit 1
+}
+. etc/tools/ThirdPartyFunctions
+. etc/tools/ParaViewFunctions
+#------------------------------------------------------------------------------
+# ParaView_VERSION from OpenFOAM etc/config.sh file
 . $WM_PROJECT_DIR/etc/config.sh/functions
 unset -f _foamAddPath _foamAddLib               # get settings only
 unset ParaView_VERSION                          # purge current values
 
 _foamSource $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/paraview)
-
 : ${ParaView_VERSION##*-}
-
-#------------------------------------------------------------------------------
-# Run from third-party directory only
-cd ${0%/*} || exit 1
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
-. etc/tools/ParaViewFunctions
 #------------------------------------------------------------------------------
 #
 # USER DEFAULTS:
@@ -69,7 +67,7 @@ MESA_LIBRARY="/usr/lib$WM_COMPILER_LIB_ARCH/libOSMesa.so"
 #   If that fails, specify the path using the PYTHON_LIBRARY variable below.
 withPYTHON=false
 PYTHON_LIBRARY=""
-# PYTHON_LIBRARY="/usr/lib$WM_COMPILER_LIB_ARCH/libpython2.6.so.1.0"
+# PYTHON_LIBRARY="/usr/lib$WM_COMPILER_LIB_ARCH/libpython2.7.so.1.0"
 
 # New rendering backend (starting with paraview 5.0).
 # Default to auto-config based on paraview version
@@ -79,14 +77,13 @@ withGL2=auto
 # NO FURTHER EDITING BELOW THIS LINE
 #
 #-----------------------------------------------------------------------------
-Script=${0##*/}
 usage() {
     : ${ParaView_VERSION:=none} # some dummy value for usage information
     exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
 
-usage: $Script [OPTION] [paraview-VERSION] [CMAKE-OPTION]
+usage: ${0##*/} [OPTION] [paraview-VERSION] [CMAKE-OPTION]
 options:
   -gcc              force gcc/g++ instead of the values from \$WM_CC, \$WM_CXX
   -rebuild          for repeated builds (-make -install) *use with caution*
@@ -116,7 +113,7 @@ The -no-FEATURE option can be used to forcibly disable these features:
 
 CMake options start with a capital letter and contain an '='.
 For example,
-    $Script BUILD_TESTING=ON
+    ${0##*/} BUILD_TESTING=ON
 to add tests
 
 For finer control, the build stages can be selected or deselected individually:
diff --git a/makeQt b/makeQt
--- a/makeQt
+++ b/makeQt
@@ -28,20 +28,20 @@
 # Description
 #     Build script for QT (the qt-everywhere-opensource-src package)
 #
-#------------------------------------------------------------------------------
-unset qtVERSION # No default version
-qtTYPE=qt-everywhere-opensource-src
-
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
 # Run from third-party directory only
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
     exit 1
 }
 . etc/tools/ThirdPartyFunctions
 . etc/tools/QtFunctions
+#------------------------------------------------------------------------------
+qtTYPE=qt-everywhere-opensource-src
+unset qtVERSION # No default version
 #------------------------------------------------------------------------------
 usage() {
     exec 1>&2
@@ -53,7 +53,7 @@ options:
   -gcc              Force gcc/g++ instead of the values from \$WM_CC, \$WM_CXX
   -help
 
-* build $qtTYPE, version $qtVERSION
+* build $qtTYPE, version ${qtVERSION:-undefined}
 
 USAGE
     exit 1
diff --git a/makeVTK b/makeVTK
--- a/makeVTK
+++ b/makeVTK
@@ -28,26 +28,33 @@
 # Description
 #     Make and install VTK.
 #     The VTK sources should be located under one of these locations:
-#       - $WM_THIRD_PARTY_DIR/ParaView-VERSION
-#       - $WM_THIRD_PARTY_DIR/ParaView-vVERSION
+#       - $WM_THIRD_PARTY_DIR/VTK-VERSION
 #
 #     To use the VTK source from the ParaView source tree, simply make an
 #     appropriate link first. For example,
 #
 #        (cd $WM_THIRD_PARTY_DIR && ln -s ParaView-v5.2.0/VTK VTK-7.1.0)
 #
+# ------------------------------------------------
+# SOME USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
 # Run from third-party directory only
-cd ${0%/*} || exit 1
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
     exit 1
 }
 . etc/tools/ThirdPartyFunctions
 . etc/tools/ParaViewFunctions
 . etc/tools/vtkFunctions
+#------------------------------------------------------------------------------
+# VTK version from OpenFOAM etc/config.sh file
+. $WM_PROJECT_DIR/etc/config.sh/functions
+unset -f _foamAddPath _foamAddLib               # get settings only
+unset vtk_version mesa_version                  # purge current values
+
+_foamSource $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/vtk)
+VTK_VERSION=$vtk_version
 #------------------------------------------------------------------------------
 #
 # USER DEFAULTS:
@@ -66,13 +73,12 @@ withGL2=auto
 # NO FURTHER EDITING BELOW THIS LINE
 #
 #-----------------------------------------------------------------------------
-Script=${0##*/}
 usage() {
     exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
 
-usage: $Script [OPTION] [vtk-VERSION] [CMAKE-OPTION]
+usage: ${0##*/} [OPTION] [vtk-VERSION] [CMAKE-OPTION]
 options:
   -gcc              force g++ instead of the value from \$WM_CXX
   -rebuild          for repeated builds (-make -install) *use with caution*
@@ -91,12 +97,12 @@ options:
   -suffix NAME      specify a suffix to distinguish the build
   -help
 
-The -no-FEATURE option can be disable these features (if not already disabled):
+The -no-FEATURE option can be used to forcibly disable these features:
   -no-gl2 | -no-mesa | -no-mpi
 
 CMake options start with a capital letter and contain an '='.
 For example,
-    $Script BUILD_TESTING=ON
+    ${0##*/} BUILD_TESTING=ON
 to add tests and avoid building documentation
 
 For finer control, the build stages can be selected or deselected individually:
diff --git a/minCmake b/minCmake
--- a/minCmake
+++ b/minCmake
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2016 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2016-2017 OpenCFD Ltd.
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # License
@@ -28,12 +28,13 @@
 # Description
 #     Scour CMakeLists.txt files to report the cmake_minimum required.
 #
+# ----------------------------------------------
+# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
 # Run from third-party directory only
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+    echo "    Check your OpenFOAM environment and installation"
     exit 1
 }
 #------------------------------------------------------------------------------
