ENH: remove reliance on OpenFOAM etc/config.sh/functions file.
- similar functionality in etc/tools/ThirdPartyFunctions to improve
  the independence of ThirdParty while reducing clutter in the callers.

- add useGcc function for convenience
- mask seeing our own git-repo when building

STYLE: various items

- eliminate old user-editable configuration in files - now command-line only.
- use *_BUILD_DIR instead of *_BINARY_DIR for more clarity of the purpose
- drop use of '-q' option for wmakeCheckPwd (already has stderr redirect)
- drop checkVersion for makeParaView since it stopped working properly
  with newer paraview version

CONFIG: update list of versions

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -32,7 +32,7 @@
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
 # Run from third-party directory only
-cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+cd ${0%/*} && wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
     echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
     echo "    Check your OpenFOAM environment and installation"
     exit 1
@@ -44,7 +44,7 @@ cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
 }
 . etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
-# Export WM settings in a form that GNU configure recognizes
+# Compiler/linker settings for CMake/configure
 [ -n "$WM_CC" ]         &&  export CC="$WM_CC"
 [ -n "$WM_CXX" ]        &&  export CXX="$WM_CXX"
 [ -n "$WM_CFLAGS" ]     &&  export CFLAGS="$WM_CFLAGS"
@@ -105,7 +105,7 @@ echo "    $SCOTCH_ARCH_PATH"
 
 SCOTCH_SOURCE_DIR=$sourceBASE/$SCOTCH_VERSION
 
-# This needs generalizing, but works fairly well
+# Needs generalizing, but works fairly well
 scotchMakefile=../../etc/wmakeFiles/scotch/Makefile.inc.i686_pc_linux2.shlib-OpenFOAM
 
 if [ -f $SCOTCH_ARCH_PATH/include/scotch.h \
@@ -118,53 +118,56 @@ elif [ -d "$SCOTCH_SOURCE_DIR" ]
 then
 (
     cd $SCOTCH_SOURCE_DIR/src || exit 1
+    export GIT_DIR=$SCOTCH_SOURCE_DIR/.git # Mask seeing our own git-repo
     rm -rf $SCOTCH_ARCH_PATH
 
     applyPatch $SCOTCH_VERSION ..       # patch at parent-level
 
     prefixDIR=$SCOTCH_ARCH_PATH
+    incDIR=$SCOTCH_ARCH_PATH/include
     libDIR=$FOAM_EXT_LIBBIN
 
     mkdir -p $prefixDIR 2>/dev/null
-    mkdir -p $libDIR 2>/dev/null
+    mkdir -p $incDIR    2>/dev/null
+    mkdir -p $libDIR    2>/dev/null
 
-    configOpt="prefix=$prefixDIR libdir=$libDIR"
+    # 'CC' already set (eg, from WM_CC) - set scotch-specific 'CCS' too
+    [ -n "$CC" ] && export CCS="$CC"
 
     if [ -f $scotchMakefile ]
     then
         rm -f Makefile.inc
         ln -s $scotchMakefile Makefile.inc
     fi
-
     [ -f Makefile.inc ] || {
         echo " Error: scotch needs an appropriate Makefile.inc"
         exit 1
     }
 
-    # handle non-gcc compilers
-    unset configEnv
-    [ "${WM_CC:-gcc}" != gcc ] && configEnv="CC=$WM_CC CCS=$WM_CC"
+    make realclean 2>/dev/null                  # Extra safety
 
-    make realclean 2>/dev/null  # for safety
+    make -j $WM_NCOMPPROCS scotch \
+     && make \
+        prefix=$prefixDIR \
+        includedir=$incDIR \
+        libdir=$libDIR \
+        install
 
-    make -j $WM_NCOMPPROCS $configEnv scotch \
-    && make $configOpt install
-
-    # cleanup, could also remove Makefile.inc
-    make realclean 2>/dev/null
+    make realclean 2>/dev/null || true          # Failed cleanup is uncritical
 ) || warnBuildIssues SCOTCH
 else
     warnNotFound SCOTCH
 fi
 
 # Build ptscotch if MPI (ThirdParty or system) is available
-# and normal scotch was build (has include and library)
+# and normal scotch was built (has include and library)
 if [ "${FOAM_MPI:-dummy}" != dummy ] && \
    [ -f $SCOTCH_ARCH_PATH/include/scotch.h \
   -a -r $FOAM_EXT_LIBBIN/libscotch.so ] || \
 {
+    # Report that the above tests failed and pass-through the failure
     echo
-    echo "    WARNING: skipping pt-scotch - 'scotch.h' include file not found!"
+    echo "    WARNING: skipping pt-scotch - no mpi or <scotch.h> not found"
     false
 }
 then
@@ -182,6 +185,7 @@ then
     else
     (
         cd $SCOTCH_SOURCE_DIR/src || exit 1
+        export GIT_DIR=$SCOTCH_SOURCE_DIR/.git # Mask seeing our own git-repo
         echo
 
         prefixDIR=$SCOTCH_ARCH_PATH
@@ -189,41 +193,43 @@ then
         libDIR=$FOAM_EXT_LIBBIN/$FOAM_MPI
 
         mkdir -p $prefixDIR 2>/dev/null
-        mkdir -p $libDIR 2>/dev/null
+        mkdir -p $incDIR    2>/dev/null
+        mkdir -p $libDIR    2>/dev/null
 
-        configOpt="prefix=$prefixDIR includedir=$incDIR libdir=$libDIR"
+        # 'CC' already set (eg, from WM_CC) - set scotch-specific 'CCS' too
+        [ -n "$CC" ] && export CCS="$CC"
 
         if [ -f $scotchMakefile ]
         then
             rm -f Makefile.inc
             ln -s $scotchMakefile Makefile.inc
         fi
-
         [ -f Makefile.inc ] || {
-            echo " Error: scotch needs an appropriate Makefile.inc"
+            echo " Error: ptscotch needs an appropriate Makefile.inc"
             exit 1
         }
 
-        # handle non-gcc compilers
-        unset configEnv
-        [ "${WM_CC:-gcc}" != gcc ] && configEnv="CC=$WM_CC CCS=$WM_CC"
+        make realclean 2>/dev/null              # Extra safety
 
-        make realclean 2>/dev/null  # for safety
+        make -j $WM_NCOMPPROCS ptscotch \
+         && make \
+            prefix=$prefixDIR \
+            includedir=$incDIR \
+            libdir=$libDIR \
+            install
 
-        make -j $WM_NCOMPPROCS $configEnv ptscotch \
-        && make $configOpt install
-
-        # cleanup, could also remove Makefile.inc
-        make realclean 2>/dev/null
-    )
+        make realclean 2>/dev/null || true      # Failed cleanup is uncritical
+    ) || warnBuildIssues PTSCOTCH
     fi
 
-    # verify existence of ptscotch include
+    # Verify existence of ptscotch include
     [ -f $SCOTCH_ARCH_PATH/include/$FOAM_MPI/ptscotch.h ] || {
         echo
         echo "    WARNING: required include file 'ptscotch.h' not found!"
     }
 fi
+
+# Could now remove $SCOTCH_SOURCE_DIR/src/Makefile.inc
 
 
 #------------------------------------------------------------------------------
@@ -233,7 +239,7 @@ echo
 echo ========================================
 echo Build Metis decomposition
 
-# get METIS_VERSION, METIS_ARCH_PATH
+# Get METIS_VERSION, METIS_ARCH_PATH
 if settings=$($WM_PROJECT_DIR/bin/foamEtcFile config.sh/metis)
 then
     . $settings
@@ -250,6 +256,7 @@ elif [ -d "$METIS_SOURCE_DIR" ]
 then
 (
     cd $METIS_SOURCE_DIR || exit 1
+    export GIT_DIR=$PWD/.git # Mask seeing our own git-repo
     rm -rf $METIS_ARCH_PATH
 
     # Adjust metis integer size to match OpenFOAM label-size
@@ -260,10 +267,10 @@ then
     # - build normally and use mv to relocate it
 
     make config shared=1 prefix=$METIS_ARCH_PATH \
-    && make -j $WM_NCOMPPROCS install \
-    && mv $METIS_ARCH_PATH/lib/libmetis.so $FOAM_EXT_LIBBIN
+     && make -j $WM_NCOMPPROCS install \
+     && mv $METIS_ARCH_PATH/lib/libmetis.so $FOAM_EXT_LIBBIN
 
-    rmdir $METIS_ARCH_PATH/lib 2>/dev/null || true # failure is not critical
+    rmdir $METIS_ARCH_PATH/lib 2>/dev/null || true # Failed rmdir is uncritical
 ) || warnBuildIssues METIS
 else
     warnNotFound METIS
diff --git a/makeCCMIO b/makeCCMIO
--- a/makeCCMIO
+++ b/makeCCMIO
@@ -32,7 +32,7 @@
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
 # Run from third-party directory only
-cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+cd ${0%/*} && wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
     echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
     echo "    Check your OpenFOAM environment and installation"
     exit 1
@@ -44,12 +44,13 @@ cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
 }
 . etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
-# libccmio version from OpenFOAM etc/config.sh file
-. $WM_PROJECT_DIR/etc/config.sh/functions
-_foamSource $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/ccmio)
+
+# libccmio version from OpenFOAM etc/config.sh file:
+_foamEtc config.sh/ccmio
 
 ccmioPACKAGE=${ccmio_version:-libccmio-2.6.1}
-targetType=lib
+targetType=lib  # Default is static linkage
+
 #------------------------------------------------------------------------------
 usage()
 {
@@ -59,6 +60,7 @@ usage()
 
 Usage: ${0##*/} [OPTION] [lib|libso] [libccmio-VERSION]
 options:
+  -gcc              Force gcc/g++ instead of the values from \$WM_CC, \$WM_CXX
   -help
 
 * Compile the proprietary libccmio library
@@ -82,9 +84,10 @@ USAGE
 while [ "$#" -gt 0 ]
 do
     case "$1" in
-    -h | -help)
-        usage
-        ;;
+    '') ;;      # Ignore empty
+    -h | -help) usage   ;;
+    -gcc)       useGcc  ;;
+
     lib|libso)
         targetType="$1"
         ;;
@@ -98,19 +101,20 @@ do
     shift
 done
 
-# assert: directory must be available
-[ -d "$ccmioPACKAGE" ] || die "missing source directory '$ccmioPACKAGE'"
-
 #------------------------------------------------------------------------------
-CCMIO_SOURCE_DIR=$sourceBASE/$ccmioPACKAGE
-CCMIO_ARCH_PATH=$installBASE/$ccmioPACKAGE
-
 #
 # Build LIBCCMIO
 #
-echo "---------------"
+CCMIO_SOURCE_DIR=$sourceBASE/$ccmioPACKAGE
+CCMIO_ARCH_PATH=$installBASE/$ccmioPACKAGE
+
+# Sources must be available
+[ -d "$CCMIO_SOURCE_DIR" ] || die "Missing sources: '$ccmioPACKAGE'"
+
 (
     cd $CCMIO_SOURCE_DIR || exit 1
+    export GIT_DIR=$PWD/.git # Mask seeing our own git-repo
+
     incDIR=$CCMIO_ARCH_PATH/include/libccmio
     libDIR=$CCMIO_ARCH_PATH/lib
 
@@ -118,16 +122,17 @@ echo "---------------"
     mkdir -p $libDIR 2>/dev/null
 
     cpMakeFiles libccmio 2>/dev/null
+
+    # Place static libraries in sub-directory:
+    if [ "$targetType" = lib ]
+    then
+        export FOAM_EXT_LIBBIN=$libDIR
+    fi
+
     if wmake $targetType
     then
-        # make headers available:
+        # Make headers available:
         /bin/cp -pv libccmio/ccmio*.h $incDIR
-
-        # relocate static libraries to sub-directory:
-        if [ "$targetType" = lib ]
-        then
-            /bin/mv -v $FOAM_EXT_LIBBIN/libccmio.a $libDIR
-        fi
     fi
 )
 
diff --git a/makeGcc b/makeGcc
--- a/makeGcc
+++ b/makeGcc
@@ -44,24 +44,25 @@
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
 # Run from third-party directory only
-cd ${0%/*} && wmakeCheckPwd -q "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+cd ${0%/*} && wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
     echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
     echo "    Check your OpenFOAM environment and installation"
     exit 1
 }
 . etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
-# Default GCC, mpfr, gmp and mpc versions from OpenFOAM etc/config.sh file
-WM_COMPILER_TYPE=ThirdParty       # ensure we get the correct compiler settings
-: ${WM_COMPILER:=Gcc}             # this will still fail if 'Clang' was set
 
-. $WM_PROJECT_DIR/etc/config.sh/functions
-_foamSource $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/compiler)
+[ "${WM_COMPILER#Gcc}" = "$WM_COMPILER" ] && WM_COMPILER=Gcc        # Force gcc
+WM_COMPILER_TYPE=ThirdParty                # Ensure we get the correct settings
+
+# Default GCC, mpfr, gmp and mpc versions from OpenFOAM etc/config.sh file:
+_foamEtc config.sh/compiler
 
 gmpPACKAGE=${gmp_version:-gmp-system}
 mpfrPACKAGE=${mpfr_version:-mpfr-system}
 mpcPACKAGE=${mpc_version:-mpc-system}
 gccPACKAGE=$gcc_version
+
 #------------------------------------------------------------------------------
 usage() {
     exec 1>&2
@@ -94,9 +95,9 @@ unset optThreadSafe # unset=auto
 while [ "$#" -gt 0 ]
 do
     case "$1" in
-    -h | -help)
-        usage
-        ;;
+    '') ;;      # Ignore empty
+    -h | -help) usage   ;;
+
     -multi*)
         optMultilib=enable
         ;;
@@ -163,6 +164,18 @@ GMP_ARCH_PATH=$installBASE/$gmpPACKAGE
 MPFR_ARCH_PATH=$installBASE/$mpfrPACKAGE
 MPC_ARCH_PATH=$installBASE/$mpcPACKAGE
 
+# Prefix <dir> to LD_LIBRARY_PATH, if it exists. 0 on success, 1 on failure
+addLib()
+{
+    if [ -d "$1" ]
+    then
+        export LD_LIBRARY_PATH=$1:$LD_LIBRARY_PATH
+        return 0
+    else
+        return 1
+    fi
+}
+
 
 # ================
 # Build GMP
@@ -182,6 +195,7 @@ else
     buildDIR=$buildBASE/$gmpPACKAGE
 
     cd $sourceDIR || exit 1
+    export GIT_DIR=$PWD/.git # Mask seeing our own git-repo
     make distclean 2>/dev/null
 
     rm -rf $buildDIR
@@ -203,10 +217,8 @@ else
 }
 fi
 
-if [ -d "$GMP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH" ]
+if addLib "$GMP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH"
 then
-    _foamAddLib "$GMP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH"
-
     configGMP=$(cat <<CONFIG_OPTIONS
     --with-gmp-include=$GMP_ARCH_PATH/include
     --with-gmp-lib=$GMP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH
@@ -235,6 +247,7 @@ else
     buildDIR=$buildBASE/$mpfrPACKAGE
 
     cd $sourceDIR || exit 1
+    export GIT_DIR=$PWD/.git # Mask seeing our own git-repo
     make distclean 2>/dev/null
 
     rm -rf $buildDIR
@@ -260,10 +273,8 @@ else
 }
 fi
 
-if [ -d "$MPFR_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH" ]
+if addLib "$MPFR_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH"
 then
-    _foamAddLib "$MPFR_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH"
-
     configMPFR=$(cat <<CONFIG_OPTIONS
     --with-mpfr-include=$MPFR_ARCH_PATH/include \
     --with-mpfr-lib=$MPFR_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH
@@ -292,6 +303,7 @@ else
     buildDIR=$buildBASE/$mpcPACKAGE
 
     cd $sourceDIR || exit 1
+    export GIT_DIR=$PWD/.git # Mask seeing our own git-repo
     make distclean 2>/dev/null
 
     rm -rf $buildDIR
@@ -313,10 +325,8 @@ else
 }
 fi
 
-if [ -d "$MPC_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH" ]
+if addLib "$MPC_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH"
 then
-    _foamAddLib "$MPC_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH"
-
     configMPC=$(cat <<CONFIG_OPTIONS
     --with-mpc-include=$MPC_ARCH_PATH/include \
     --with-mpc-lib=$MPC_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH
@@ -349,6 +359,7 @@ else
     buildDIR=$buildBASE/$gccPACKAGE
 
     cd $sourceDIR || exit 1
+    export GIT_DIR=$PWD/.git # Mask seeing our own git-repo
     make distclean 2>/dev/null
 
     rm -rf $buildDIR
