ENH: add build scripts for KaHIP and METIS

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -65,8 +65,7 @@ warnBuildIssues()
 
 warnNotFound()
 {
-    echo "    Optional component ($1) was not found"
-    echo
+    echo "Optional component ($1) was not found"
 }
 
 #------------------------------------------------------------------------------
@@ -101,7 +100,7 @@ fi
 
 echo
 echo ========================================
-echo "Build Scotch decomposition library $SCOTCH_VERSION"
+echo "Scotch decomposition ($SCOTCH_VERSION)"
 echo "    $SCOTCH_ARCH_PATH"
 
 SCOTCH_SOURCE_DIR=$sourceBASE/$SCOTCH_VERSION
@@ -113,8 +112,8 @@ if [ -f $SCOTCH_ARCH_PATH/include/scotch.h \
   -a -r $FOAM_EXT_LIBBIN/libscotch.so \
   -a -r $FOAM_EXT_LIBBIN/libscotcherrexit.so ]
 then
-    echo "    scotch header in $SCOTCH_ARCH_PATH/include"
-    echo "    scotch libs   in $FOAM_EXT_LIBBIN"
+    echo "    scotch include: $SCOTCH_ARCH_PATH/include"
+    echo "    scotch library: $FOAM_EXT_LIBBIN"
 elif [ -d "$SCOTCH_SOURCE_DIR" ]
 then
 (
@@ -176,15 +175,15 @@ if [ "${FOAM_MPI:-dummy}" != dummy ] && \
 then
     echo
     echo ========================================
-    echo "Build pt-scotch decomposition library $SCOTCH_VERSION (with $FOAM_MPI)"
+    echo "pt-scotch decomposition ($SCOTCH_VERSION with $FOAM_MPI)"
     echo "    $SCOTCH_ARCH_PATH"
 
     if [ -f $SCOTCH_ARCH_PATH/include/$FOAM_MPI/ptscotch.h \
       -a -r $FOAM_EXT_LIBBIN/$FOAM_MPI/libptscotch.so \
       -a -r $FOAM_EXT_LIBBIN/$FOAM_MPI/libptscotcherrexit.so ]
     then
-        echo "    ptscotch header in $SCOTCH_ARCH_PATH/include/$FOAM_MPI"
-        echo "    ptscotch libs   in $FOAM_EXT_LIBBIN/$FOAM_MPI"
+        echo "    ptscotch include: $SCOTCH_ARCH_PATH/include/$FOAM_MPI"
+        echo "    ptscotch library: $FOAM_EXT_LIBBIN/$FOAM_MPI"
     else
     (
         cd $SCOTCH_SOURCE_DIR/src || exit 1
@@ -239,55 +238,46 @@ fi
 
 #------------------------------------------------------------------------------
 
-# Metis is optional
 echo
 echo ========================================
-echo Build Metis decomposition
-
-# Get METIS_VERSION, METIS_ARCH_PATH
-if settings=$($WM_PROJECT_DIR/bin/foamEtcFile config.sh/metis)
+# Get KAHIP_ARCH_PATH
+if settings=$($WM_PROJECT_DIR/bin/foamEtcFile config.sh/kahip)
 then
     . $settings
 fi
-
-METIS_SOURCE_DIR=$sourceBASE/$METIS_VERSION
-
-if [ -f $METIS_ARCH_PATH/include/metis.h \
-  -a -r $FOAM_EXT_LIBBIN/libmetis.so ]
+if [ -n "$KAHIP_ARCH_PATH" ]
 then
-    echo "    metis header in $METIS_ARCH_PATH/include"
-    echo "    metis libs   in $FOAM_EXT_LIBBIN"
-elif [ -d "$METIS_SOURCE_DIR" ]
-then
-(
-    cd $METIS_SOURCE_DIR || exit 1
-    export GIT_DIR=$PWD/.git # Mask seeing our own git-repo
-    rm -rf $METIS_ARCH_PATH
-
-    # Adjust metis integer size to match OpenFOAM label-size
-    sed -i -e 's=\(#define IDXTYPEWIDTH\).*=\1 '$WM_LABEL_SIZE'=' \
-        include/metis.h
-
-    # No config option for the library location.
-    # - build normally and use mv to relocate it
-
-    make config shared=1 prefix=$METIS_ARCH_PATH \
-     && make -j $WM_NCOMPPROCS install \
-     && mv $METIS_ARCH_PATH/lib/libmetis.so $FOAM_EXT_LIBBIN
-
-    rmdir $METIS_ARCH_PATH/lib 2>/dev/null || true # Failed rmdir is uncritical
-) || warnBuildIssues METIS
+    echo KaHIP decomposition
+    ./makeKAHIP -test "$KAHIP_ARCH_PATH" || \
+    ./makeKAHIP || warnBuildIssues KAHIP
 else
-    warnNotFound METIS
+    warnNotFound KAHIP   # METIS is optional
 fi
-
 
 #------------------------------------------------------------------------------
 echo
 echo ========================================
-echo Build CGAL
+
+# Get METIS_ARCH_PATH
+if settings=$($WM_PROJECT_DIR/bin/foamEtcFile config.sh/metis)
+then
+    . $settings
+fi
+if [ -n "$METIS_ARCH_PATH" ]
+then
+    echo Metis decomposition
+    ./makeMETIS -test "$METIS_ARCH_PATH" || \
+    ./makeMETIS || warnBuildIssues METIS
+else
+    warnNotFound METIS   # METIS is optional
+fi
+
+#------------------------------------------------------------------------------
+echo
+echo ========================================
 if [ -n "$CGAL_ARCH_PATH" ]
 then
+    echo "CGAL/boost"
     ./makeCGAL -test "$CGAL_ARCH_PATH" "$BOOST_ARCH_PATH" || \
     ./makeCGAL || warnBuildIssues CGAL
 else
@@ -296,9 +286,9 @@ fi
 
 echo
 echo ========================================
-echo Build FFTW
 if [ -n "$FFTW_ARCH_PATH" ]
 then
+    echo FFTW
     ./makeFFTW -test "$FFTW_ARCH_PATH" || \
     ./makeFFTW || warnBuildIssues FFTW
 else
diff --git a/makeKAHIP b/makeKAHIP
--- a/makeKAHIP
+++ b/makeKAHIP
@@ -3,8 +3,8 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2011-2016 OpenFOAM Foundation
-#    \\/     M anipulation  | Copyright (C) 2016-2017 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2017 OpenCFD Ltd.
+#    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
@@ -23,13 +23,39 @@
 #     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Script
-#     makeCCMIO
+#     makeKAHIP
 #
 # Description
-#     Build the libccmio library
+#     Build the KaHIP library (int32 only).
 #
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
+#------------------------------------------------------------------------------
+# Short-circuit test for an installation
+if [ "$1" = "-test" ]
+then
+    [ "$#" -eq 2 ] || { echo "${0##*/} -test : needs 1 argument"; exit 1; }
+    dir="$2" # <- KAHIP_ARCH_PATH
+    if [ -d "$dir/include" ]
+    then
+        for lib in \
+            $FOAM_EXT_LIBBIN/libkahip.so \
+            $dir/lib/libkahip.a \
+            $dir/lib/libkahip.so \
+            $dir/lib$WM_COMPILER_LIB_ARCH/libkahip.a \
+            $dir/lib$WM_COMPILER_LIB_ARCH/libkahip.so \
+            ;
+        do
+            if [ -r "$lib" ]
+            then
+                echo "    kahip include: $dir/include"
+                echo "    kahip library: ${lib%/*}"
+                exit 0
+            fi
+        done
+    fi
+    exit 2
+fi
 #------------------------------------------------------------------------------
 # Run from third-party directory only
 cd ${0%/*} && wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
@@ -44,12 +70,10 @@ cd ${0%/*} && wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
 }
 . etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
+_foamEtc config.sh/kahip
 
-# libccmio version from OpenFOAM etc/config.sh file:
-_foamEtc config.sh/ccmio
-
-ccmioPACKAGE=${ccmio_version:-libccmio-2.6.1}
-targetType=lib  # Default is static linkage
+kahipPACKAGE=${KAHIP_VERSION:-kahip-system}
+targetType=libso
 
 #------------------------------------------------------------------------------
 usage()
@@ -58,22 +82,13 @@ usage()
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     /bin/cat<<USAGE
 
-Usage: ${0##*/} [OPTION] [lib|libso] [libccmio-VERSION]
+Usage: ${0##*/} [OPTION] [lib|libso] [kahip-VERSION]
 options:
   -gcc              Force gcc/g++ instead of the values from \$WM_CC, \$WM_CXX
   -help
 
-* Compile the proprietary libccmio library
-      $ccmioPACKAGE
-
-  Users wishing to obtain the library should contact Siemens PLM (cd-adapco)
-  for terms of use.
-
-  After obtaining the $ccmioPACKAGE library, place in folder
-
-      $WM_THIRD_PARTY_DIR/$ccmioPACKAGE/
-
-  prior to running this script.
+* Compile KaHIP
+      $kahipPACKAGE
 
 USAGE
     exit 1
@@ -91,8 +106,10 @@ do
     lib|libso)
         targetType="$1"
         ;;
-    libccmio-[1-9]*)
-        ccmioPACKAGE="${1%%/}"
+
+    kahip-[1-9]* | kahip-git)
+        kahipPACKAGE="${1%%/}"
+        unset KAHIP_ARCH_PATH  # Avoid inconsistency
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -101,15 +118,33 @@ do
     shift
 done
 
+[ -n "$kahipPACKAGE" ] || die "The kahip-VERSION was not specified"
+
+# Nothing to build
+if _foamIsNone $kahipPACKAGE
+then
+    echo "Using kahip-none (skip ThirdParty build of KAHIP)"
+    exit 0
+elif _foamIsSystem $kahipPACKAGE
+then
+    echo "Using kahip-system"
+    exit 0
+fi
+
 #------------------------------------------------------------------------------
 #
-# Build LIBCCMIO
+# Build KaHIP
 #
-CCMIO_SOURCE_DIR=$sourceBASE/$ccmioPACKAGE
-CCMIO_ARCH_PATH=$installBASE/$ccmioPACKAGE
+#   KAHIP_ARCH_PATH  : installation directory
+#   KAHIP_SOURCE_DIR : location of the original sources
 
-# Sources must be available
-[ -d "$CCMIO_SOURCE_DIR" ] || die "Missing sources: '$ccmioPACKAGE'"
+KAHIP_SOURCE_DIR=$sourceBASE/$kahipPACKAGE
+KAHIP_ARCH_PATH=$installBASE/$kahipPACKAGE
+
+[ -d "$KAHIP_SOURCE_DIR" ] || {
+    echo "Missing sources: '$kahipPACKAGE'"
+    exit 1
+}
 
 #
 # Manual installation
@@ -119,26 +154,34 @@ install()
     # Ensure a clean build next time
     wclean
 
-    local incdir=$CCMIO_ARCH_PATH/include/libccmio
+    local bindir=$KAHIP_ARCH_PATH/bin
+    local incdir=$KAHIP_ARCH_PATH/include
+    local libdir=$KAHIP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH
 
-    # Make headers available:
     mkdir -m 0755 -p $incdir
 
-    /bin/cp -pv libccmio/ccmio*.h $incdir
+    /bin/cp -pv \
+        $KAHIP_SOURCE_DIR/interface/kaHIP_interface.h \
+        $incdir
 }
 
-echo "Starting build: $ccmioPACKAGE ($targetType)"
+echo "Starting build: $kahipPACKAGE ($targetType)"
 echo
 (
-    cd $CCMIO_SOURCE_DIR || exit 1
-    export GIT_DIR=$PWD/.git # Mask seeing our own git-repo
+    cd $KAHIP_SOURCE_DIR/lib || exit 1
+    export GIT_DIR=$KAHIP_SOURCE_DIR/.git # Mask seeing our own git-repo
 
-    rm -rf $CCMIO_ARCH_PATH
-    rm -f $FOAM_EXT_LIBBIN/libccmio.so
+    rm -rf $KAHIP_ARCH_PATH
+    rm -f $FOAM_EXT_LIBBIN/libkahip.so
 
-    libdir=$CCMIO_ARCH_PATH/lib
+    libdir=$KAHIP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH
 
-    cpMakeFiles libccmio 2>/dev/null
+    cpMakeFiles kahip 2>/dev/null
+
+    if [ -e ../interface -a ! -e interface ]
+    then
+        ln -s ../interface interface
+    fi
 
     # Place static libraries in sub-directory:
     if [ "$targetType" = lib ]
@@ -147,12 +190,16 @@ echo
         export FOAM_EXT_LIBBIN=$libdir
     fi
 
+    # Location of lib sources for wmake
+    export KAHIP_LIB_SRC=$PWD
+
     wmake -j $WM_NCOMPPROCS -s $targetType \
-    && echo "Built: ccmio" \
+    && echo "Built: kahip" \
     && install
 ) || {
-    echo "Error building: ccmio"
+    echo "Error building: kahip"
     exit 1
 }
+
 
 #------------------------------------------------------------------------------
