COMP: adjust to use non-gcc compilers for scotch and ptscotch

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -38,7 +38,7 @@ cd ${0%/*} && wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
     exit 1
 }
 [ -n "$FOAM_EXT_LIBBIN" ] || {
-    echo "Error (${0##*/}) : \$FOAM_EXT_LIBBIN not set"
+    echo "Error (${0##*/}) : \$FOAM_EXT_LIBBIN not set for ThirdParty"
     echo "    Check your OpenFOAM environment and installation"
     exit 1
 }
@@ -51,6 +51,7 @@ cd ${0%/*} && wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
 [ -n "$WM_CXXFLAGS" ]   &&  export CXXFLAGS="$WM_CXXFLAGS"
 [ -n "$WM_LDFLAGS" ]    &&  export LDFLAGS="$WM_LDFLAGS"
 
+useGccFlag $@           # Scan arguments for a '-gcc' option
 
 warnBuildIssues()
 {
@@ -131,9 +132,6 @@ then
     mkdir -p $incDIR    2>/dev/null
     mkdir -p $libDIR    2>/dev/null
 
-    # 'CC' already set (eg, from WM_CC) - set scotch-specific 'CCS' too
-    [ -n "$CC" ] && export CCS="$CC"
-
     if [ -f $scotchMakefile ]
     then
         rm -f Makefile.inc
@@ -144,8 +142,10 @@ then
         exit 1
     }
 
-    make realclean 2>/dev/null                  # Extra safety
+    export CCS="${CC:-$WM_CC}"  # CCS (serial compiler)   default=$(CC)
+    export CCP=$(whichMpicc)    # CCP (parallel compiler) default=mpicc
 
+    make realclean 2>/dev/null  # Extra safety
     make -j $WM_NCOMPPROCS scotch \
      && make \
         prefix=$prefixDIR \
@@ -153,7 +153,7 @@ then
         libdir=$libDIR \
         install
 
-    make realclean 2>/dev/null || true          # Failed cleanup is uncritical
+    make realclean 2>/dev/null || true      # Failed cleanup is uncritical
 ) || warnBuildIssues SCOTCH
 else
     warnNotFound SCOTCH
@@ -196,9 +196,6 @@ then
         mkdir -p $incDIR    2>/dev/null
         mkdir -p $libDIR    2>/dev/null
 
-        # 'CC' already set (eg, from WM_CC) - set scotch-specific 'CCS' too
-        [ -n "$CC" ] && export CCS="$CC"
-
         if [ -f $scotchMakefile ]
         then
             rm -f Makefile.inc
@@ -209,8 +206,10 @@ then
             exit 1
         }
 
-        make realclean 2>/dev/null              # Extra safety
+        export CCS="${CC:-$WM_CC}"  # CCS (serial compiler)   default=$(CC)
+        export CCP=$(whichMpicc)    # CCP (parallel compiler) default=mpicc
 
+        make realclean 2>/dev/null  # Extra safety
         make -j $WM_NCOMPPROCS ptscotch \
          && make \
             prefix=$prefixDIR \
@@ -218,7 +217,7 @@ then
             libdir=$libDIR \
             install
 
-        make realclean 2>/dev/null || true      # Failed cleanup is uncritical
+        make realclean 2>/dev/null || true  # Failed cleanup is uncritical
     ) || warnBuildIssues PTSCOTCH
     fi
 
