CONFIG: harmonize makeAdios1, makeAdios2 files
- remove old dependency of adios2 on the adios1 library

diff --git a/makeAdios2 b/makeAdios2
--- a/makeAdios2
+++ b/makeAdios2
@@ -3,14 +3,14 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2018 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2018-2019 OpenCFD Ltd.
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # This file is part of OpenFOAM, licensed under the GNU General Public License
 # <http://www.gnu.org/licenses/>.
 #
 # Script
-#     makeADIOS2
+#     makeAdios2
 #
 # Description
 #     Build script for ADIOS2
@@ -27,9 +27,9 @@ cd ${0%/*} && wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
 . etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 # ADIOS2 version from OpenFOAM etc/config.sh file:
-_foamConfig ADIOS2
+_foamConfig adios2
 
-adios2PACKAGE=${adios2_version:-adios-none}
+adiosPACKAGE=${adios2_version:-adios-none}
 
 #------------------------------------------------------------------------------
 usage() {
@@ -44,13 +44,13 @@ options:
   -help
 
 * Build ADIOS2
-      $adios2PACKAGE
+      $adiosPACKAGE
 
 USAGE
     exit 1
 }
 #------------------------------------------------------------------------------
-exportCompiler true     # Compiler info + flags for CMake/configure
+exportCompiler minimal  # Minimal compiler info for CMake/configure
 
 # Parse options
 while [ "$#" -gt 0 ]
@@ -65,8 +65,11 @@ do
         CMAKE_PATH="${2%%/}"
         shift
         ;;
-    ADIOS2-[1-9]* | adios2-[1-9]* | ADIOS2-git* | adios2-git*)
-        adios2PACKAGE="${1%%/}"
+    ADIOS2-[1-9]* | ADIOS2-git* | adios-[1-9]* | ADIOS-git*)
+        adiosPACKAGE="${1%%/}"
+        ;;
+    adios2-[1-9]* | adios2-git* | adios-[1-9]* | adios-git*)
+        adiosPACKAGE="${1%%/}"
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -75,14 +78,14 @@ do
     shift
 done
 
-[ -n "$adios2PACKAGE" ] || die "The adios2-VERSION was not specified"
+[ -n "$adiosPACKAGE" ] || die "The adios2-VERSION was not specified"
 
 # nothing to build
-if _foamIsNone "$adios2PACKAGE"
+if _foamIsNone "$adiosPACKAGE"
 then
     echo "Using adios-none (skip ThirdParty build of ADIOS)"
     exit 0
-elif _foamIsSystem "$adios2PACKAGE"
+elif _foamIsSystem "$adiosPACKAGE"
 then
     echo "Using adios-system"
     exit 0
@@ -94,20 +97,8 @@ fi
 #   ADIOS2_SOURCE_DIR : location of the original sources
 #   ADIOS2_ARCH_PATH  : installation directory
 
-ADIOS2_SOURCE_DIR=$sourceBASE/$adios2PACKAGE
-ADIOS2_ARCH_PATH=$installBASE/$adios2PACKAGE
-
-# Some hacked in value, for binding in ADIOS1 as well (for the reader)
-# Don't know if this is still needed
-if [ -n "$ADIOS1_ARCH_PATH" ]
-then
-    ADIOS1_ARCH_PATH=$installBASE/ADIOS-1.13.0
-fi
-if [ -d "$ADIOS1_ARCH_PATH" ]
-then
-    export ADIOS1_ROOT="$ADIOS1_ARCH_PATH"
-fi
-
+ADIOS2_SOURCE_DIR=$sourceBASE/$adiosPACKAGE
+ADIOS2_ARCH_PATH=$installBASE/$adiosPACKAGE
 
 : ${FOAM_MPI:=dummy}
 
@@ -128,14 +119,14 @@ then
     echo "    ADIOS2 libs   in $ADIOS2_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH" # static
 else
     # CMake options often lag the configure ones
-    echo "Starting build: $adios2PACKAGE (using cmake)"
+    echo "Starting build: $adiosPACKAGE (using cmake)"
     echo
     (
-        buildDIR=$buildBASE/$adios2PACKAGE
+        buildDIR=$buildBASE/$adiosPACKAGE
         cd $ADIOS2_SOURCE_DIR || exit 1
         export GIT_DIR=$PWD/.git # Mask seeing our own git-repo
 
-        applyPatch $adios2PACKAGE $ADIOS2_SOURCE_DIR
+        applyPatch $adiosPACKAGE $ADIOS2_SOURCE_DIR
 
         # Remove any existing build folder and recreate
         rm -rf $ADIOS2_ARCH_DIR
@@ -158,14 +149,13 @@ else
             -DCMAKE_INSTALL_PREFIX=$ADIOS2_ARCH_PATH \
             -DCMAKE_BUILD_TYPE=Release \
             -DADIOS2_USE_Fortran=FALSE \
-            -DADIOS1_USE_STATIC_LIBS=TRUE \
             ${WM_QUIET:+-DCMAKE_RULE_MESSAGES=OFF} \
             $ADIOS2_SOURCE_DIR \
         && make -j $WM_NCOMPPROCS all \
         && make install \
-        && echo "Built: $adios2PACKAGE"
+        && echo "Built: $adiosPACKAGE"
     ) || {
-        echo "Error building: $adios2PACKAGE"
+        echo "Error building: $adiosPACKAGE"
     }
 fi
 
