ENH: support building of paraview with Qt5
- this is the upcoming default Qt version

diff --git a/etc/tools/ParaViewFunctions b/etc/tools/ParaViewFunctions
--- a/etc/tools/ParaViewFunctions
+++ b/etc/tools/ParaViewFunctions
@@ -3,7 +3,7 @@
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright (C) 2011-2016 OpenFOAM Foundation
-#    \\/     M anipulation  | Copyright (C) 2016 OpenCFD Ltd.
+#    \\/     M anipulation  | Copyright (C) 2016-2017 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
@@ -29,7 +29,20 @@
 #
 #------------------------------------------------------------------------------
 
-# sourceBASE, buildBASE, installBASE defined in tools/ThirdPartyFunctions
+# Variables referenced by the functions. Initialization at the end of the file.
+unset CMAKE_VARIABLES
+unset withVERBOSE
+unset withMPI     MPI_MAX_PROCS
+unset withQT      QT_VERSION      QMAKE_PATH
+unset withMESA    MESA_INCLUDE    MESA_LIBRARY    withOSMESA
+unset withPYTHON  PYTHON_INCLUDE  PYTHON_LIBRARY
+unset OBJ_ADD
+
+BUILD_TYPE=Release  # The cmake build type
+
+# sourceBASE, buildBASE, installBASE
+#   are defined in tools/ThirdPartyFunctions
+#------------------------------------------------------------------------------
 
 #
 # Where things are or should be put
@@ -74,7 +87,7 @@ setParaViewDirs()
     echo "ParaView_BINARY_DIR=$ParaView_BINARY_DIR"
     echo "ParaView_DIR=$ParaView_DIR"
 
-    # Forcefully override the .git path for the ParaView source code directory
+    # Prevent git queries from using the ThirdParty repository
     export GIT_DIR=$ParaView_SOURCE_DIR/.git
 }
 
@@ -123,6 +136,7 @@ checkVersion()
     fi
 }
 
+
 #
 # Set CMake cache variables
 #
@@ -143,7 +157,7 @@ addVerbosity()
 {
     if [ "${withVERBOSE:=false}" = true ]
     then
-        addCMakeVariable  "CMAKE_VERBOSE_MAKEFILE=TRUE"
+        addCMakeVariable "CMAKE_VERBOSE_MAKEFILE=TRUE"
     fi
 }
 
@@ -160,10 +174,10 @@ addMpiSupport()
 
     OBJ_ADD="$OBJ_ADD-mpi"
 
-    addCMakeVariable  "PARAVIEW_USE_MPI=ON VTK_USE_MPI=ON"
+    addCMakeVariable "PARAVIEW_USE_MPI=ON VTK_USE_MPI=ON"
     if [ "${MPI_MAX_PROCS:=0}" -gt 1 ]
     then
-        addCMakeVariable  "VTK_MPI_MAX_NUMPROCS=$MPI_MAX_PROCS"
+        addCMakeVariable "VTK_MPI_MAX_NUMPROCS=$MPI_MAX_PROCS"
     fi
 }
 
@@ -219,9 +233,9 @@ addPythonSupport()
             exit 1
         }
 
-        addCMakeVariable  "PARAVIEW_ENABLE_PYTHON=ON"
-        addCMakeVariable  "PYTHON_INCLUDE_DIRS=$pythonInclude"
-        addCMakeVariable  "PYTHON_LIBRARY=$PYTHON_LIBRARY"
+        addCMakeVariable "PARAVIEW_ENABLE_PYTHON=ON"
+        addCMakeVariable "PYTHON_INCLUDE_DIRS=$pythonInclude"
+        addCMakeVariable "PYTHON_LIBRARY=$PYTHON_LIBRARY"
 
         echo "----"
         echo "Python information:"
@@ -254,17 +268,17 @@ addMesaSupport()
     then
         OBJ_ADD="$OBJ_ADD-mesa"
 
-        addCMakeVariable  "VTK_OPENGL_HAS_OSMESA:BOOL=ON"
-        addCMakeVariable  "OSMESA_INCLUDE_DIR=$MESA_INCLUDE"
-        addCMakeVariable  "OSMESA_LIBRARY=$MESA_LIBRARY"
+        addCMakeVariable "VTK_OPENGL_HAS_OSMESA:BOOL=ON"
+        addCMakeVariable "OSMESA_INCLUDE_DIR=$MESA_INCLUDE"
+        addCMakeVariable "OSMESA_LIBRARY=$MESA_LIBRARY"
 
     else
-       echo "*** Error: no MESA information found"
-       echo "***        Deactivate MESA support by not using the -mesa option, "
-       echo "***        or set the correct paths for:"
-       echo "***        -mesa-include ($MESA_INCLUDE)"
-       echo "***        -mesa-lib ($MESA_LIBRARY)"
-       exit 1
+        echo "*** Error: no MESA information found"
+        echo "***   Deactivate MESA support by not using the -mesa option, "
+        echo "***   or set the correct paths for:"
+        echo "***       -mesa-include ($MESA_INCLUDE)"
+        echo "***       -mesa-lib ($MESA_LIBRARY)"
+        exit 1
     fi
 }
 
@@ -276,45 +290,42 @@ addGL2Support()
 {
     if [ "${withGL2:=false}" = true ]
     then
-        addCMakeVariable  "VTK_RENDERING_BACKEND=OpenGL2"
+        addCMakeVariable "VTK_RENDERING_BACKEND=OpenGL2"
     fi
 }
 
 
+#
+# Qt 4/5 support
+#
 addQtSupport()
 {
-    QtVersion=none
+    QT_VERSION=none
+    : ${withQT:=true}  # default is on
 
-    if [ "${withQT:=false}" != true ]
+    if [ "$withQT" = false ]
     then
+        # Explicitly disabled
+        addCMakeVariable "PARAVIEW_BUILD_QT_GUI=OFF"
         return
     fi
 
-    addCMakeVariable "PARAVIEW_BUILD_QT_GUI=ON"
+    local qmake qtLib
 
-    local qmake=$(findQtMake)
-
-    # From somewhere other than in the path
-    if [ "${qmake:=qmake}" != qmake ]
+    # Check qmake can be found and handle version differences
+    qmake=$(findQtMake)
+    if QT_VERSION=$($qmake -query QT_VERSION 2>/dev/null)
     then
-        addCMakeVariable "QT_QMAKE_EXECUTABLE:FILEPATH=$qmake"
-    fi
+        addCMakeVariable "PARAVIEW_BUILD_QT_GUI=ON"
 
-    # Check qmake can be found
-    if type $qmake >/dev/null 2>&1
-    then
-        # Check the Qt version selected
-        # parse -> "Using Qt version X.Y.Z in ..."
-        QtVersion=$($qmake -query QT_VERSION)
-
-        case "$QtVersion" in
-        3.* | 4.[0-4]*)
+        case "$QT_VERSION" in
+        (3.* | 4.[0-4]*)
             # QT is too old
             cat <<ERROR
 ----
 Error: ${0##*/}
 
-QT version ($QtVersion) provided < 4.5
+QT version ($QT_VERSION) provided < 4.5
 Please use the -qmake option to specify the location of a newer QT version
 For example,
     ... -qmake /usr/local/qt-4.6.2/bin/qmake
@@ -324,12 +335,32 @@ ERROR
             exit 1
             ;;
 
-        5.*)
-            # QT4 is the default, must specify QT5 explicitly
-            addCMakeVariable "PARAVIEW_QT_VERSION:STRING=5"
+        (4.*)
+            # Default changed to Qt5 with paraview 5.2.1, so specify explicitly
+            addCMakeVariable "PARAVIEW_QT_VERSION=4"
+
+            # Non-system installation - specify location of qmake
+            if [ "$qmake" != /usr/bin/qmake ]
+            then
+                addCMakeVariable "QT_QMAKE_EXECUTABLE=$qmake"
+            fi
+            ;;
+
+        (5.*)
+            # Default changed to Qt5 with paraview 5.2.1, so specify explicitly
+            addCMakeVariable "PARAVIEW_QT_VERSION=5"
+
+            # Non-system installation - find CMake config files
+            if [ "$qmake" != /usr/bin/qmake ] \
+               && qtLib="$($qmake -query QT_INSTALL_LIBS)/cmake/Qt5" \
+               && [ -d "$qtLib" ]
+            then
+                addCMakeVariable "Qt5_DIR=$qtLib"
+            fi
             ;;
         esac
     else
+        QT_VERSION=none
         echo "Error: cannot find qmake either at \$QMAKE_PATH or in current \$PATH"
         echo
         exit 1
@@ -362,7 +393,7 @@ configParaView()
     fi
     mkdir -p $ParaView_BINARY_DIR
 
-    addCMakeVariable  "CMAKE_BUILD_TYPE:STRING=$buildType"
+    addCMakeVariable "CMAKE_BUILD_TYPE=$BUILD_TYPE"
 
     cd $ParaView_BINARY_DIR || exit 1  # Change to build folder
 
@@ -372,16 +403,15 @@ configParaView()
     echo "    Python support : ${withPYTHON:-false}"
     echo "    MESA   support : ${withMESA:-false}"
     echo "    GL2  rendering : ${withGL2:-false}"
-    echo "    Qt dev support : ${withQT:-false}"
+    echo "    QT dev support : ${withQT:-true}"
     echo "    Source         : $ParaView_SOURCE_DIR"
     echo "    Build          : $ParaView_BINARY_DIR"
     echo "    Target         : $ParaView_DIR"
-    echo "    Build type     : $buildType"
-    echo "    Cmake          : $cmake"
+    echo "    cmake          : $cmake"
     echo "----"
     echo
     echo "$cmake" \
-        -DCMAKE_INSTALL_PREFIX:PATH=$ParaView_DIR \
+        -DCMAKE_INSTALL_PREFIX=$ParaView_DIR \
         $CMAKE_VARIABLES \
         $ParaView_SOURCE_DIR
     echo
@@ -390,7 +420,7 @@ configParaView()
 
     # Run cmake to create Makefiles
     $cmake \
-        -DCMAKE_INSTALL_PREFIX:PATH=$ParaView_DIR \
+        -DCMAKE_INSTALL_PREFIX=$ParaView_DIR \
         $CMAKE_VARIABLES \
         $ParaView_SOURCE_DIR
 }
@@ -426,38 +456,44 @@ installParaView()
 
     make install
 
-cat<< INFO
+    # System or non-system installation of QT?
+    local qmake qtLib QT_VERSION
+    if qmake=$(findQtMake 2>/dev/null)
+    then
+        qtLib=$($qmake -query QT_INSTALL_LIBS)
+        QT_VERSION=$($qmake -query QT_VERSION 2>/dev/null)
+    fi
 
-    ---
-    Installation complete for paraview-$ParaView_VERSION
+    /bin/cat<<INFO
+
+====
+Installation complete for paraview-$ParaView_VERSION with qt-${QT_VERSION:-none}
     ParaView_DIR=$ParaView_DIR
 
-    You may need to update the OpenFOAM environment by running:
-        wmRefresh
-    ---
+You may need to update the OpenFOAM environment by running:
+    wmRefresh
 INFO
+
+    # Non-system installation of QT?
+    if [ "$qmake" != /usr/bin/qmake -a -d "$qtLib" ]
+    then
+        cat<< INFO
+
+And adjust your LD_LIBRARY_PATH to include the following:
+    $qtLib
+INFO
+    fi
+
+    echo "===="
 }
 
 
 #------------------------------------------------------------------------------
 
-# Clear the referenced variables before using any of the functions
-unset withMPI  withVERBOSE
-unset withQT      QMAKE_PATH
-unset withMESA    MESA_INCLUDE    MESA_LIBRARY
-unset withPYTHON  PYTHON_INCLUDE  PYTHON_LIBRARY
-unset CMAKE_VARIABLES
-unset OBJ_ADD
-unset buildType
-
 # Start with these general settings
-addCMakeVariable  "BUILD_SHARED_LIBS:BOOL=ON  VTK_USE_RPATH:BOOL=OFF"
+addCMakeVariable "BUILD_SHARED_LIBS=ON" "BUILD_TESTING=OFF"
 
 # Include development files in "make install"
-addCMakeVariable  "PARAVIEW_INSTALL_DEVELOPMENT_FILES:BOOL=ON"
-
-# Don't build test tree
-addCMakeVariable  "BUILD_TESTING:BOOL=OFF"
-
+addCMakeVariable "PARAVIEW_INSTALL_DEVELOPMENT_FILES=ON"
 
 #------------------------------------------------------------------------------
diff --git a/etc/tools/ThirdPartyFunctions b/etc/tools/ThirdPartyFunctions
--- a/etc/tools/ThirdPartyFunctions
+++ b/etc/tools/ThirdPartyFunctions
@@ -86,18 +86,19 @@ _foamIsSystem()
 
 
 #
-# try to locate cmake according to the CMAKE_PATH
-# or just use what is found in the path
+# Try to locate cmake according to the CMAKE_PATH.
+#
+# On success: return the resolved value as output.
+# On failure: just report what is found in the path.
 #
 unset CMAKE_PATH # clear when first loaded
 findCMake()
 {
-    local candidate
-    local foundExe
+    local candidate foundExe
 
     if [ -n "$CMAKE_PATH" ]
     then
-        # check as directory
+        # Check as directory
         if [ -d "$CMAKE_PATH" ]
         then
             for candidate in \
@@ -113,7 +114,7 @@ findCMake()
             done
         fi
 
-        # check as file, include ThirdParty installation in the search
+        # Check as file, include ThirdParty installation in the search
         if [ -z "$foundExe" ]
         then
             for candidate in \
@@ -137,9 +138,8 @@ findCMake()
             then
                 foundExe="$(cd ${foundExe%/cmake} 2>/dev/null && pwd)/cmake"
             fi
-
             echo "Using cmake=$foundExe" 1>&2
-            echo "$foundExe"
+            echo $foundExe
             return 0
         else
             cat << NOT_FOUND 1>&2
@@ -150,26 +150,27 @@ NOT_FOUND
         fi
     fi
 
-    # Default to use the path, try resolving (so we know what we are using)
-    foundExe=$(command -v cmake 2> /dev/null) || foundExe=cmake
-    echo "Using cmake=${foundExe:-NotFound}"  1>&2
-    echo "${foundExe:-cmake}"
+    # Default to use the path. Resolve so we know what we are using.
+    foundExe=$(command -v cmake 2> /dev/null) || foundExe=false
+    echo "Using cmake=$foundExe" 1>&2
+    echo $foundExe
 }
 
 
 #
 # try to locate qmake according to the QMAKE_PATH
-# or just use what is found in the path
+#
+# On success: return the resolved value as output.
+# On failure: just report what is found in the path.
 #
 unset QMAKE_PATH # clear when first loaded
 findQtMake()
 {
-    local candidate
-    local foundExe
+    local candidate foundExe
 
     if [ -n "$QMAKE_PATH" ]
     then
-        # check as directory
+        # Check as directory
         if [ -d "$QMAKE_PATH" ]
         then
             for candidate in \
@@ -185,7 +186,7 @@ findQtMake()
             done
         fi
 
-        # check as file, include ThirdParty installation in the search
+        # Check as file, include ThirdParty installation in the search
         if [ -z "$foundExe" ]
         then
             for candidate in \
@@ -209,9 +210,8 @@ findQtMake()
             then
                 foundExe="$(cd ${foundExe%/qmake} 2>/dev/null && pwd)/qmake"
             fi
-
             echo "Using qmake=$foundExe" 1>&2
-            echo "$foundExe"
+            echo $foundExe
             return 0
         else
             cat << NOT_FOUND 1>&2
@@ -223,9 +223,9 @@ NOT_FOUND
     fi
 
     # Default to use the path, try resolving (so we know what we are using)
-    foundExe=$(command -v qmake 2> /dev/null) || foundExe=qmake
-    echo "Using qmake=${foundExe:-NotFound}"  1>&2
-    echo "${foundExe:-qmake}"
+    foundExe=$(command -v qmake 2> /dev/null) || foundExe=false
+    echo "Using qmake=$foundExe" 1>&2
+    echo $foundExe
 }
 
 
