ENH: makeParaView now accepts paraview-VERSION directly as argument
- Symmetrical with the usage for most other ThirdParty build
  scripts. For example,

      "makeParaView ParaView-5.0.1"

- As a convenience, also allow a number directly. For example,

      "makeParaView 5.0.1"

  This should be clearer than the old instruction and does not
  rely on an alias:

      "foamPV 5.0.1; ./makeParaView"

BUG: heuristics for activating GL2 rendering backend missed when
     paraview version was specified from the command-line

diff --git a/etc/tools/ParaView3Functions b/etc/tools/ParaView3Functions
--- a/etc/tools/ParaView3Functions
+++ b/etc/tools/ParaView3Functions
@@ -3,7 +3,7 @@
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright (C) 2011-2016 OpenFOAM Foundation
-#    \\/     M anipulation  |
+#    \\/     M anipulation  | Copyright (C) 2016 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
@@ -72,12 +72,16 @@ setDirs()
 #
 # Set ParaView_VERSION and adjust ParaView_MAJOR accordingly
 #
+# $1 can contain something something like 4.4.0, paraview-4.4.0, ParaView-4.0.0
+#
 setVersion()
 {
-    if [ "$#" -ge 1 ]
-    then
-        ParaView_VERSION="${1##paraview-}"
-    fi
+    [ $# -gt 0 ] || {
+        echo "Error: function setVersion() called without an argument"
+        exit 1
+    }
+
+    ParaView_VERSION="${1##*-}"
 
     # The major version is "<digits>.<digits>"
     ParaView_MAJOR=$(echo $ParaView_VERSION | \
@@ -410,7 +414,7 @@ configParaView()
     echo
 
     # Run cmake to create Makefiles
-    $cmakeExe \
+    $cmakeExe -Wno-dev \
         -DCMAKE_INSTALL_PREFIX:PATH=$ParaView_DIR \
         $CMAKE_VARIABLES \
         $ParaView_SOURCE_DIR
diff --git a/etc/tools/ParaViewFunctions b/etc/tools/ParaViewFunctions
--- a/etc/tools/ParaViewFunctions
+++ b/etc/tools/ParaViewFunctions
@@ -72,12 +72,16 @@ setDirs()
 #
 # Set ParaView_VERSION and adjust ParaView_MAJOR accordingly
 #
+# $1 can contain something something like 4.4.0, paraview-4.4.0, ParaView-4.0.0
+#
 setVersion()
 {
-    if [ "$#" -ge 1 ]
-    then
-        ParaView_VERSION="${1##paraview-}"
-    fi
+    [ $# -gt 0 ] || {
+        echo "Error: function setVersion() called without an argument"
+        exit 1
+    }
+
+    ParaView_VERSION="${1##*-}"
 
     # The major version is "<digits>.<digits>"
     ParaView_MAJOR=$(echo $ParaView_VERSION | \
