ENH: improve flexibility of make scripts
- the various make scripts now also search hierarchical sources,
  which makes it easier to organize sources. The secondary
  sub-directory is the lower-case value of the package stripped of
  trailing non-alphabet characters.

  For example, searching for ParaView-v5.9.1

    sources/
    |-- adios
    |   |-- ...
    |   |-- ADIOS2-2.7.1
    |   \-- adios-1.13.1
    |-- cgal
    |   |-- CGAL-4.12.2
    |   \-- CGAL-4.14.2
    |   ...
    |-- openmpi
    |   |-- openmpi-4.0.3
    |   \-- openmpi-4.1.1
    |-- paraview
    |   |-- ParaView-v5.6.1
    |   \-- ParaView-v5.9.1
    \-- scotch
        ...

- additional out-of-source build options

  FOAM_THIRD_PARTY_BUILDROOT :
     Replace WM_THIRD_PARTY_DIR as the root for build/ and platforms/

  FOAM_THIRD_PARTY_SOURCES :
     Alternative to WM_THIRD_PARTY_DIR/sources/

- rationalise internal package variable names for easier maintenance

diff --git a/etc/tools/ThirdPartyFunctions b/etc/tools/ThirdPartyFunctions
--- a/etc/tools/ThirdPartyFunctions
+++ b/etc/tools/ThirdPartyFunctions
@@ -38,6 +38,85 @@ installBASE="$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER"
 # Synthetic value combining precision and label size (Eg, DPInt32)
 WM_SIZE_OPTIONS="${WM_PRECISION_OPTION}Int${WM_LABEL_SIZE}"
 
+#------------------------------------------------------------------------------
+# Make adjustments for non-standard build locations
+
+# Specified a build-root
+if [ -n "$FOAM_THIRD_PARTY_BUILDROOT" ]
+then
+    if [ ! -d "$FOAM_THIRD_PARTY_BUILDROOT" ]
+    then
+        dir="$(dirname "$FOAM_THIRD_PARTY_BUILDROOT")"
+        if [ -d "$dir" ] && [ -w "$dir" ]
+        then
+            mkdir -m 0755 -p "$FOAM_THIRD_PARTY_BUILDROOT"
+        fi
+        # Also checks for failure of previous mkdir
+        if [ ! -d "$FOAM_THIRD_PARTY_BUILDROOT" ]
+        then
+            echo "Build-root: $FOAM_THIRD_PARTY_BUILDROOT" 1>&2
+            echo "Has invalid parent: $dir" 1>&2
+            exit 2
+        fi
+    fi
+    echo "Using build-root: $FOAM_THIRD_PARTY_BUILDROOT" 1>&2
+
+    # build/
+    _buildDir="${FOAM_THIRD_PARTY_BUILDROOT}/build"
+    mkdir -m 0755 -p "$_buildDir"
+
+    # Fully resolved
+    dir="$(cd "$_buildDir" 2>/dev/null && pwd -L)"
+    if [ -n "$dir" ]
+    then
+        buildBASE="$dir/$WM_ARCH$WM_COMPILER"
+        echo "Using build-dir: $dir" 1>&2
+    else
+        echo "Invalid build-dir: $_buildDir" 1>&2
+        exit 2
+    fi
+
+    # platforms/
+    _platformsDir="${FOAM_THIRD_PARTY_BUILDROOT}/platforms"
+    mkdir -m 0755 -p "$_platformsDir"
+
+    # Fully resolved
+    dir="$(cd "$_platformsDir" 2>/dev/null && pwd -L)"
+    if [ -n "$dir" ]
+    then
+        installBASE="$dir/$WM_ARCH$WM_COMPILER"
+        echo "Using platforms-dir: $dir" 1>&2
+    else
+        echo "Invalid platforms-dir: $_platformsDir" 1>&2
+        exit 2
+    fi
+
+    # Installation with non-standard platforms location
+    nonStandardPlatforms() { true; }
+else
+    # Installation with standard platforms location
+    nonStandardPlatforms() { false; }
+fi
+
+
+# sources/
+if [ -n "$FOAM_THIRD_PARTY_SOURCES" ]
+then
+    # Fully resolved
+    dir="$(cd "$FOAM_THIRD_PARTY_SOURCES" 2>/dev/null && pwd -L)"
+    if [ -n "$dir" ]
+    then
+        sourceBASE="$dir"
+        echo "Using sources-dir: $dir" 1>&2
+    else
+        echo "Invalid sources-dir: $FOAM_THIRD_PARTY_SOURCES" 1>&2
+        exit 2
+    fi
+fi
+
+
+#------------------------------------------------------------------------------
+
 # Dynamic library ending (default is .so)
 EXT_SO="$(wmake -show-ext-so 2>/dev/null)"
 if [ -z "$EXT_SO" ]
@@ -53,6 +132,13 @@ then
     esac
 fi
 
+# True if OS is <darwin>.
+# Test EXT_SO for ".dylib" - avoid repeated uname system call
+isDarwin()
+{
+    [ "$EXT_SO" = .dylib ]
+}
+
 
 # Fallback values, needed for our scotch Makefile which uses
 # WM_CFLAGS and WM_LDFLAGS for arch information
@@ -67,6 +153,7 @@ then
 fi
 
 unset BUILD_SUFFIX
+
 
 #------------------------------------------------------------------------------
 # Check for existence of shared library (without .so extension)
@@ -237,15 +324,29 @@ useGccFlag()
 # Final fallback is <gcc>
 whichCC()
 {
+    local fallback='gcc'
     local comp="$CC"
+    local warn
 
     if [ -z "$comp" ]
     then
         comp="$(wmake -show-c 2>/dev/null)" || comp="$WM_CC"
-        test -n "$comp" && command -v "$comp" >/dev/null || unset comp
+        if [ -n "$comp" ]
+        then
+            if ! command -v "$comp" >/dev/null
+            then
+                warn="C compiler '$comp' not found in path."
+                unset comp
+            fi
+        else
+            warn="No C compiler found via wmake."
+        fi
+        if [ -n "$warn" ]
+        then
+            echo "${warn} Defaulting to '${fallback}'" 1>&2
+        fi
     fi
-
-    echo "${comp:-gcc}"
+    echo "${comp:-$fallback}"
 }
 
 
@@ -254,15 +355,29 @@ whichCC()
 # Final fallback is <g++>
 whichCXX()
 {
+    local fallback='g++'
     local comp="$CXX"
+    local warn
 
     if [ -z "$comp" ]
     then
         comp="$(wmake -show-cxx 2>/dev/null)" || comp="$WM_CXX"
-        test -n "$comp" && command -v "$comp" >/dev/null || unset comp
+        if [ -n "$comp" ]
+        then
+            if ! command -v "$comp" >/dev/null
+            then
+                warn="CXX compiler '$comp' not found in path."
+                unset comp
+            fi
+        else
+            warn="No CXX compiler found via wmake."
+        fi
+        if [ -n "$warn" ]
+        then
+            echo "${warn} Defaulting to '${fallback}'" 1>&2
+        fi
     fi
-
-    echo "${comp:-g++}"
+    echo "${comp:-$fallback}"
 }
 
 
@@ -275,7 +390,8 @@ whichCXX()
 # NOTE: could further refine based on "wmake -show-c", but not yet needed
 whichMpicc()
 {
-    local comp="$(command -v mpicc)"
+    local fallback='mpicc'
+    local comp="$(command -v $fallback)"
     case "$WM_MPLIB" in
     (FJMPI)
         comp="$(command -v mpifcc)"     # Fujitsu <mpifcc> available?
@@ -287,7 +403,7 @@ whichMpicc()
         : "${comp:=cc}"                 # Cray <cc> if there is no <mpicc>
         ;;
     esac
-    echo "${comp:-mpicc}"
+    echo "${comp:-$fallback}"
 }
 
 
@@ -300,7 +416,8 @@ whichMpicc()
 # NOTE: could further refine based on "wmake -show-cxx", but not yet needed
 whichMpicxx()
 {
-    local comp="$(command -v mpicxx)"
+    local fallback='mpicxx'
+    local comp="$(command -v $fallback)"
     case "$WM_MPLIB" in
     (FJMPI)
         comp="$(command -v mpiFCC)"     # Fujitsu <mpiFCC> available?
@@ -309,10 +426,10 @@ whichMpicxx()
         comp="$(command -v mpiicpc)"    # Intel <mpiicpc> available?
         ;;
     (CRAY-MPI*)
-        : "${comp:=CC}"                 # Cray <CC> if there is no <mpicc>
+        : "${comp:=CC}"                 # Cray <CC> if there is no <mpicxx>
         ;;
     esac
-    echo "${comp:-mpicxx}"
+    echo "${comp:-$fallback}"
 }
 
 # Require wmkdepend etc when building with wmake
@@ -426,6 +543,7 @@ findSourceDir()
 
         for check in \
             "$package" \
+            "$subdir/$package" \
             "sources/$package" \
             "sources/$subdir/$package" \
         ;
@@ -501,7 +619,7 @@ listPackageVersions()
 
             [ -n "$package" ] || continue
 
-            for dir in . sources sources/"$package"
+            for dir in . ./"$package" sources sources/"$package"
             do
                 # Find package-version (ie, when it has separators)
                 find "$dir" -maxdepth 1 \
diff --git a/makeAdios2 b/makeAdios2
--- a/makeAdios2
+++ b/makeAdios2
@@ -5,7 +5,7 @@
 #   \\  /    A nd           | www.openfoam.com
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
-#     Copyright (C) 2018-2020 OpenCFD Ltd.
+#     Copyright (C) 2018-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -49,19 +49,21 @@ then
     exit 2
 fi
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
-# ADIOS2 version from OpenFOAM etc/config.sh file:
+# Obtain version from OpenFOAM etc/config.sh file:
 _foamConfig adios2
 
-adiosPACKAGE=${adios2_version:-adios-none}
+PACKAGE="${adios2_version:-none}"
 
 # Hint for cmake findMPI
 if [ -d "$MPI_ARCH_PATH" ]
@@ -70,25 +72,25 @@ then
 fi
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions adios; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [adios-VERSION]
+Usage: ${0##*/} [OPTION] [adios-VERSION]
 options:
   -force            Force compilation, even if include/library already exists
   -gcc              Force use of gcc/g++
   -cmake PATH       With cmake from the given path
   -mpi-home PATH    With hint for MPI_HOME
-  -help
+  -list             List available unpacked source versions
+  -help             Display usage help
 
 * Build ADIOS2
-      $adiosPACKAGE
+      ${PACKAGE:-[unspecified]}
 
 USAGE
-    showDownloadHint ADIOS2
-    exit 1
+    showDownloadHint adios2
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler minimal  # Minimal compiler info for CMake/configure
@@ -100,7 +102,8 @@ while [ "$#" -gt 0 ]
 do
     case "$1" in
     '') ;;      # Ignore empty
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
     -force)     optForce=true ;;
 
@@ -115,9 +118,11 @@ do
         case "${MPI_HOME:-none}" in (false|none) unset MPI_HOME;; esac
         shift
         ;;
+
+    adios/* | sources/ADIOS* | sources/adios* | \
     ADIOS2-[0-9]* | ADIOS2-git* | ADIOS-[0-9]* | ADIOS-git* | \
     adios2-[0-9]* | adios2-git* | adios-[0-9]* | adios-git*)
-        adiosPACKAGE="${1%%/}"
+        PACKAGE="${1%%/}"
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -126,16 +131,12 @@ do
     shift
 done
 
-[ -n "$adiosPACKAGE" ] || die "The adios2-VERSION was not specified"
-
-# nothing to build
-if _foamIsNone "$adiosPACKAGE"
+if [ -z "$PACKAGE" ]
 then
-    echo "Using adios-none (skip ThirdParty build of ADIOS)"
-    exit 0
-elif _foamIsSystem "$adiosPACKAGE"
+    die "The ADIOS package/version not specified"
+elif _foamIsNone "$PACKAGE" || _foamIsSystem "$PACKAGE"
 then
-    echo "Using adios-system"
+    echo "Using none/system (skip ThirdParty build of ADIOS)"
     exit 0
 fi
 
@@ -155,44 +156,46 @@ esac
 #------------------------------------------------------------------------------
 #
 # Build ADIOS
-#   ADIOS2_SOURCE_DIR : location of the original sources
-#   ADIOS2_ARCH_PATH  : installation directory
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
 
-ADIOS2_SOURCE_DIR=$sourceBASE/$adiosPACKAGE
-ADIOS2_ARCH_PATH=$installBASE/$adiosPACKAGE
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
+PACKAGE="$(basename "$PACKAGE")"
+PKG_PREFIX="$installBASE/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"
 
-: ${FOAM_MPI:=dummy}
+: "${FOAM_MPI:=dummy}"
 
 echo
 echo ========================================
-echo "Build adios library $adiosPACKAGE for $FOAM_MPI"
+echo "Build adios library $PACKAGE for $FOAM_MPI"
 echo
 
 # Needs future adjustment
 # - for mpi-specific library locations
 if [ -z "$optForce" ] \
-&& [ -f "$ADIOS2_ARCH_PATH/include/adios2.h" ] \
+&& [ -f "$PKG_PREFIX/include/adios2.h" ] \
 && {
-    [ -r "$ADIOS2_ARCH_PATH/lib/libadios2$EXT_SO" ] \
- || [ -r "$ADIOS2_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH/libadios2$EXT_SO" ]
+    [ -r "$PKG_PREFIX/lib/libadios2$EXT_SO" ] \
+ || [ -r "$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH/libadios2$EXT_SO" ]
 }
 then
-    echo "    ADIOS2 already built : $ADIOS2_ARCH_PATH"
+    echo "    ADIOS2 already built : $PKG_PREFIX"
 else
     # CMake options often lag the configure ones
-    echo "Starting build: $adiosPACKAGE (using cmake)"
+    echo "Starting build: $PACKAGE (using cmake)"
     echo
     (
-        buildDIR=$buildBASE/$adiosPACKAGE
-        cd "$ADIOS2_SOURCE_DIR" || exit
-        export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
+        PKG_BUILD="$buildBASE/$PACKAGE"
+        cd "$PKG_SOURCE" || exit
 
-        applyPatch $adiosPACKAGE $ADIOS2_SOURCE_DIR
+        applyPatch "$PACKAGE" "$PKG_SOURCE"
 
         # Remove any existing build folder and recreate
-        rm -rf $ADIOS2_ARCH_DIR
-        rm -rf $buildDIR 2>/dev/null
-        mkdir -p $buildDIR
+        rm -rf "$PKG_PREFIX"
+        rm -rf "$PKG_BUILD"
+        mkdir -p "$PKG_BUILD"
 
         # May not work properly with FOAM_MPI = dummy
         if [ "$FOAM_MPI" != dummy ]
@@ -203,19 +206,20 @@ else
 
         cmake=$(findCMake)
 
-        # Install into lib64/
-        cd $buildDIR && $cmake \
-            -DCMAKE_INSTALL_PREFIX=$ADIOS2_ARCH_PATH \
+        # Installs into lib64/
+        cd "$PKG_BUILD" && set -x && \
+        ${cmake:?} \
+            -DCMAKE_INSTALL_PREFIX="$PKG_PREFIX" \
             -DCMAKE_BUILD_TYPE=Release \
             -DADIOS2_USE_Fortran=FALSE \
             -DADIOS2_BUILD_EXAMPLES=FALSE \
             ${WM_QUIET:+-DCMAKE_RULE_MESSAGES=OFF} \
-            $ADIOS2_SOURCE_DIR \
+            "$PKG_SOURCE" \
         && make -j $WM_NCOMPPROCS all \
         && make install \
-        && echo "Built: $adiosPACKAGE"
+        && echo "Built: $PACKAGE"
     ) || {
-        echo "Error building: $adiosPACKAGE"
+        echo "Error building: $PACKAGE"
         exit 1
     }
 fi
diff --git a/makeCCMIO b/makeCCMIO
--- a/makeCCMIO
+++ b/makeCCMIO
@@ -7,7 +7,7 @@
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 #     Copyright (C) 2011-2016 OpenFOAM Foundation
-#     Copyright (C) 2016-2020 OpenCFD Ltd.
+#     Copyright (C) 2016-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -21,49 +21,51 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 
 # libccmio version from OpenFOAM etc/config.sh file:
 _foamConfig ccmio
 
-ccmioPACKAGE=${ccmio_version:-libccmio-2.6.1}
+PACKAGE="${ccmio_version:-libccmio-2.6.1}"
 targetType=lib  # Default is static linkage
 
 #------------------------------------------------------------------------------
-usage()
-{
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
-    /bin/cat<<USAGE
+printVersions() { listPackageVersions ccmio libccmio; exit 0; }
+printHelp() {
+    cat<<USAGE
 
 Usage: ${0##*/} [OPTION] [lib|libso] [libccmio-VERSION]
 options:
   -gcc          Force use of gcc/g++
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
 * Compile the proprietary libccmio library
-      $ccmioPACKAGE
+      $PACKAGE
 
   Users wishing to obtain the library should contact Siemens PLM (cd-adapco)
   for terms of use.
 
-  After obtaining the $ccmioPACKAGE library, place in folder
+  After obtaining the $PACKAGE library, place in folder
 
-      $WM_THIRD_PARTY_DIR/$ccmioPACKAGE/
+      $sourceBASE/$PACKAGE/
+  or  $sourceBASE/sources/$PACKAGE/
 
   prior to running this script.
 
 USAGE
-    showDownloadHint CCMIO
-    exit 1
+    showDownloadHint ccmio
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 
@@ -72,14 +74,17 @@ while [ "$#" -gt 0 ]
 do
     case "$1" in
     '') ;;      # Ignore empty
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGccWmake ;;
 
     lib|libso)
         targetType="$1"
         ;;
+
+    libccmio/* | sources/libccmio* | \
     libccmio-[0-9]*)
-        ccmioPACKAGE="${1%%/}"
+        PACKAGE="${1%%/}"
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -94,54 +99,62 @@ requireExtLibBin
 #------------------------------------------------------------------------------
 #
 # Build LIBCCMIO
-#
-CCMIO_SOURCE_DIR=$sourceBASE/$ccmioPACKAGE
-CCMIO_ARCH_PATH=$installBASE/$ccmioPACKAGE
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
+
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
+PACKAGE="$(basename "$PACKAGE")"
+PKG_PREFIX="$installBASE/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"
 
 # Sources must be available
-[ -d "$CCMIO_SOURCE_DIR" ] || die "Missing sources: '$ccmioPACKAGE'"
+[ -d "$PKG_SOURCE" ] || die "Missing sources: '$PACKAGE'"
 
 #
 # Manual installation
 #
 install()
 {
-    # Ensure a clean build next time
+    local incdir="$PKG_PREFIX"/include/libccmio
+
+    # Remove build artifacts from the source directory
+    # (for a clean build next time)
     wclean
 
-    local incdir=$CCMIO_ARCH_PATH/include/libccmio
+    echo
+    echo "Adjusting installation"
+    echo "Installing headers: $incdir"
 
-    # Make headers available:
-    mkdir -m 0755 -p $incdir
-
-    /bin/cp -pv libccmio/ccmio*.h $incdir
+    # Make headers available
+    mkdir -m 0755 -p "$incdir"
+    /bin/cp -pv "$PKG_SOURCE"/libccmio/ccmio*.h "$incdir"
 }
 
-echo "Starting build: $ccmioPACKAGE ($targetType)"
+echo "Starting build: $PACKAGE ($targetType)"
 echo
 (
-    cd "$CCMIO_SOURCE_DIR" || exit
-    export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-
-    rm -rf $CCMIO_ARCH_PATH
-    rm -f $FOAM_EXT_LIBBIN/libccmio$EXT_SO
-
-    libdir=$CCMIO_ARCH_PATH/lib
+    cd "$PKG_SOURCE" || exit
+    rm -rf "$PKG_PREFIX"
+    rm -f "$FOAM_EXT_LIBBIN/libccmio$EXT_SO"
 
     cpMakeFiles libccmio 2>/dev/null
 
-    # Place static libraries in sub-directory:
-    if [ "$targetType" = lib ]
+    # Static libraries in sub-directory
+    export CCMIO_LIB_DIR="$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH"
+
+    # Dynamic libraries directly into FOAM_EXT_LIBBIN
+    if [ "$targetType" = libso ]
     then
-        mkdir -m 0755 -p $libdir 2>/dev/null
-        export FOAM_EXT_LIBBIN=$libdir
+        CCMIO_LIB_DIR="$FOAM_EXT_LIBBIN"
     fi
+    mkdir -m 0755 -p "$CCMIO_LIB_DIR" 2>/dev/null
 
     wmake -j $WM_NCOMPPROCS -s $targetType \
-    && echo "Built: ccmio" \
+    && echo "Built: $PACKAGE" \
     && install
 ) || {
-    echo "Error building: ccmio"
+    echo "Error building: $PACKAGE"
     exit 1
 }
 
diff --git a/makeCGAL b/makeCGAL
--- a/makeCGAL
+++ b/makeCGAL
@@ -7,7 +7,7 @@
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 #     Copyright (C) 2012-2016 OpenFOAM Foundation
-#     Copyright (C) 2016-2020 OpenCFD Ltd.
+#     Copyright (C) 2016-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -60,34 +60,41 @@ then
     fi
 fi
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 unset BOOST_ARCH_PATH CGAL_ARCH_PATH GMP_ARCH_PATH MPFR_ARCH_PATH   # Purge old
+unset GMP_DIR MPFR_DIR  # Purge hints used by CGAL cmake
 
 # CGAL, boost and gmp/mpfr versions from OpenFOAM etc/config.sh files.
 # Get compiler first and let CGAL config override GMP and MPFR
 _foamConfig compiler
 _foamConfig CGAL
 
-boostPACKAGE=${boost_version:-boost-system}
-gmpPACKAGE=${gmp_version:-gmp-system}
-mpfrPACKAGE=${mpfr_version:-mpfr-system}
-cgalPACKAGE=$cgal_version
+BOOST_PACKAGE="${boost_version:-boost-system}"
+GMP_PACKAGE="${gmp_version:-gmp-system}"
+MPFR_PACKAGE="${mpfr_version:-mpfr-system}"
+CGAL_PACKAGE="$cgal_version"
+
+if nonStandardPlatforms  # Possibly unreliable inherited values
+then
+    unset BOOST_ARCH_PATH CGAL_ARCH_PATH
+fi
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions boost cgal; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [CGAL-VERSION] [boost-VERSION] [gmp-VERSION] [mpfr-VERSION]
+Usage: ${0##*/} [OPTION] [CGAL-VERSION] [boost-VERSION] [gmp-VERSION] [mpfr-VERSION]
 options:
   -gcc          Force use of gcc/g++
   -cmake PATH   Use cmake from the given path
@@ -95,13 +102,14 @@ options:
   -with-lib     Configure CGAL with library
   -toolset=NAME Use named toolset in bootstrap
   -system       Use system versions for boost/gmp/mpfr
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
 * build CGAL with
-      ${cgalPACKAGE:-'unspecified CGAL version'}
-      $boostPACKAGE
-      $gmpPACKAGE
-      $mpfrPACKAGE
+      ${CGAL_PACKAGE:-[cgal unspecified]}
+      ${BOOST_PACKAGE:-[boost unspecified]}
+      ${GMP_PACKAGE:-[gmp unspecified]}
+      ${MPFR_PACKAGE:-[mpfr unspecified]}
 
 Normally builds against ThirdParty boost and gmp/mpfr when possible.
 To override this behaviour (and use the system boost and/or gmp/mpfr),
@@ -111,9 +119,9 @@ simply specify a 'system' version. For example,
 Use gmp-none to disable use of gmp/mpfr (eg, not available)
 
 USAGE
-    showDownloadHint BOOST
-    showDownloadHint CGAL
-    exit 1
+    showDownloadHint boost
+    showDownloadHint cgal
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler          # Compiler info for CMake/configure
@@ -125,7 +133,8 @@ while [ "$#" -gt 0 ]
 do
     case "$1" in
     '') ;;      # Ignore empty
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
     -force)     optForce=true ;;
 
@@ -138,9 +147,9 @@ do
         optToolset="${1#*=}"
         ;;
     -sys*)
-        gmpPACKAGE="gmp-system"
-        mpfrPACKAGE="mpfr-system"
-        boostPACKAGE="boost-system"
+        GMP_PACKAGE="gmp-system"
+        MPFR_PACKAGE="mpfr-system"
+        BOOST_PACKAGE="boost-system"
         unset BOOST_ARCH_PATH GMP_ARCH_PATH MPFR_ARCH_PATH
         ;;
     -no-lib)
@@ -150,19 +159,23 @@ do
         optHeadersOnly=false
         ;;
     gmp-[0-9]* | gmp-system | gmp-none)
-        gmpPACKAGE="${1%%/}"
+        GMP_PACKAGE="${1%%/}"
         unset GMP_ARCH_PATH
         ;;
     mpfr-[0-9]* | mpfr-system | mpfr-none)
-        mpfrPACKAGE="${1%%/}"
+        MPFR_PACKAGE="${1%%/}"
         unset MPFR_ARCH_PATH
         ;;
+
+    boost/* | sources/boost* | \
     boost-[0-9]* | boost_[0-9]* | boost-system )
-        boostPACKAGE="${1%%/}"
+        BOOST_PACKAGE="${1%%/}"
         unset BOOST_ARCH_PATH
         ;;
+
+    cgal/* | sources/cgal* | \
     CGAL-[0-9]*)
-        cgalPACKAGE="${1%%/}"
+        CGAL_PACKAGE="${1%%/}"
         unset CGAL_ARCH_PATH
         ;;
     *)
@@ -172,15 +185,15 @@ do
     shift
 done
 
-[ -n "$cgalPACKAGE" ] || die "The cgal-VERSION was not specified"
+[ -n "$CGAL_PACKAGE" ] || die "The cgal-VERSION was not specified"
 
 # Nothing to build
-if _foamIsNone "$boostPACKAGE"
+if _foamIsNone "$BOOST_PACKAGE"
 then
     echo "Using boost-none (skip ThirdParty build of BOOST/CGAL)"
     exit 0
 fi
-if _foamIsNone "$cgalPACKAGE"
+if _foamIsNone "$CGAL_PACKAGE"
 then
     echo "Using cgal-none (skip ThirdParty build of CGAL)"
     exit 0
@@ -200,29 +213,36 @@ fi
 # Headers-only - might be able to avoid gmp/mpfr?
 ## if [ "${optHeadersOnly:-false}" = true ]
 ## then
-##     gmpPACKAGE=none
-##     mpfrPACKAGE=none
+##     GMP_PACKAGE=none
+##     MPFR_PACKAGE=none
 ##     unset GMP_ARCH_PATH MPFR_ARCH_PATH
 ## fi
 
 #------------------------------------------------------------------------------
 #
 # Build Boost
+#   BOOST_ARCH_PATH : installation directory (as per config file)
+#
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
+#
 # For 64-bit:
 # - system is normally built into 'lib64'
 # - use Third-Party 'lib64' for consistency.
 # Boost 1_62_0 and older normally build into 'lib'.
-#
-#   BOOST_ARCH_PATH  : installation directory
-#   BOOST_SOURCE_DIR : location of the original sources
 
-BOOST_SOURCE_DIR="$sourceBASE/$boostPACKAGE"
-: "${BOOST_ARCH_PATH:=$installBASE/$boostPACKAGE}"
+BOOST_SOURCE="$(findSourceDir "$BOOST_PACKAGE")"
+BOOST_PACKAGE="$(basename "$BOOST_PACKAGE")"
+BOOST_PREFIX="$installBASE/$BOOST_PACKAGE"
 
-boostInc="$BOOST_ARCH_PATH/include"
-boostLib="$BOOST_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH"
+# Override as per config file (if any)
+[ -n "$BOOST_ARCH_PATH" ] && BOOST_PREFIX="$BOOST_ARCH_PATH"
 
-if _foamIsSystem "$boostPACKAGE"
+boostInc="$BOOST_PREFIX/include"
+boostLib="$BOOST_PREFIX/lib$WM_COMPILER_LIB_ARCH"
+
+if _foamIsSystem "$BOOST_PACKAGE"
 then
     echo "Using boost-system (skip ThirdParty build of BOOST)"
 
@@ -230,16 +250,16 @@ then
 
     if [ -d "$boostInc" ]
     then
-        if BOOST_ARCH_PATH=$(cd "$BOOST_ARCH_PATH" 2>/dev/null && pwd -P)
+        if BOOST_PREFIX=$(cd "$BOOST_PREFIX" 2>/dev/null && pwd -P)
         then
-            boostPACKAGE="${BOOST_ARCH_PATH##*/}"
+            BOOST_PACKAGE="$(basename "$BOOST_PREFIX")"
         else
-            echo "ERROR: bad path for BOOST_ARCH_PATH"
+            echo "ERROR: bad path for BOOST_PREFIX"
             echo "stopping build"
             exit 1
         fi
 
-        libdir="$BOOST_ARCH_PATH/lib"
+        libdir="$BOOST_PREFIX/lib"
     else
         boostInc="/usr/include"
         boostLib="/usr/lib$WM_COMPILER_LIB_ARCH"
@@ -252,22 +272,23 @@ then
 elif [ -z "$optForce" ] \
   && [ -f "$boostInc/boost/version.hpp" ]
 then
-    echo "Using $boostPACKAGE"
+    echo "Using $BOOST_PACKAGE"
 
-    libdir="$BOOST_ARCH_PATH/lib"
+    libdir="$BOOST_PREFIX/lib"
 
     # Use lib when lib64 does not exist
     [ -d "$libdir" -a ! -d "$boostLib" ] && boostLib="$libdir"
 
 else
-    echo "Starting build: $boostPACKAGE"
+    echo "Starting build: $BOOST_PACKAGE"
     echo
     # Absolute path for --libdir
 
     (
         # Write user-config.jam into source directory
-        cd "$BOOST_SOURCE_DIR" || exit
-        export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
+        # this is not great, but project-config.jam is written there too
+        cd "$BOOST_SOURCE" || exit
+        export GIT_DIR="$PWD/.git"    # Avoid seeing our own git-repo
 
         # Configuration options:
         unset buildOpt
@@ -314,25 +335,26 @@ else
         # End of configuration options
         # ----------------------------
 
-        rm -rf "$BOOST_ARCH_PATH"
+        rm -rf "$BOOST_PREFIX"
 
         ./bootstrap.sh \
-            --prefix="$BOOST_ARCH_PATH" \
+            --prefix="$BOOST_PREFIX" \
             --libdir="$boostLib" \
             --with-libraries=thread \
             --with-libraries=system \
             --with-toolset="$optToolset" \
         && ./b2 $buildOpt -j $WM_NCOMPPROCS install \
-        && echo "Built: boost"
+        && echo "Built: $BOOST_PACKAGE"
     ) || {
-        echo "Error building: boost"
+        echo "Error building: $BOOST_PACKAGE"
         exit 1
     }
+
 fi
 
 
 # Nothing left to build
-if _foamIsSystem "$cgalPACKAGE"
+if _foamIsSystem "$CGAL_PACKAGE"
 then
     echo "Using cgal-system (skip ThirdParty build of CGAL)"
     exit 0
@@ -360,23 +382,28 @@ fi
 # - use Third-Party 'lib64' for consistency.
 # CGAL-4.9 normally builds into 'lib64', older versions into 'lib'.
 #
-#   CGAL_SOURCE_DIR : location of the original sources
-#   CGAL_BUILD_DIR  : location of the build
-#   CGAL_ARCH_PATH  : installation directory
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
+#   CGAL_ARCH_PATH : installation directory (as per config file)
 
-CGAL_SOURCE_DIR="$sourceBASE/$cgalPACKAGE"
-CGAL_BUILD_DIR="$buildBASE/$cgalPACKAGE"
-: "${CGAL_ARCH_PATH:=$installBASE/$cgalPACKAGE}"
+CGAL_SOURCE="$(findSourceDir "$CGAL_PACKAGE")"
+CGAL_PACKAGE="$(basename "$CGAL_PACKAGE")"
+CGAL_PREFIX="$installBASE$WM_SIZE_OPTIONS/$CGAL_PACKAGE"
+
+# Override as per config file (if any)
+[ -n "$CGAL_ARCH_PATH" ] && CGAL_PREFIX="$CGAL_ARCH_PATH"
+
 
 # gmp/mpfr are installed without compiler name
-mpfrBASE="$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH"
+archBASE="$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH"
 
 # Enable/disable gmp/mpfr together
-if _foamIsNone "$gmpPACKAGE" || _foamIsNone "$mpfrPACKAGE"
+if _foamIsNone "$GMP_PACKAGE" || _foamIsNone "$MPFR_PACKAGE"
 then
     GMP_ARCH_PATH=none
     MPFR_ARCH_PATH=none
-elif _foamIsSystem "$gmpPACKAGE" || _foamIsSystem "$mpfrPACKAGE"
+elif _foamIsSystem "$GMP_PACKAGE" || _foamIsSystem "$MPFR_PACKAGE"
 then
     # May really be system, but could also by a central installation
     # Ensure everything is accurately recorded. Resolve paths etc.
@@ -385,7 +412,7 @@ then
     then
         if GMP_ARCH_PATH=$(cd "$GMP_ARCH_PATH" 2>/dev/null && pwd -P)
         then
-            gmpPACKAGE="${GMP_ARCH_PATH##*/}"
+            GMP_PACKAGE="${GMP_ARCH_PATH##*/}"
         else
             echo "ERROR: bad path for GMP_ARCH_PATH"
             echo "stopping build"
@@ -399,7 +426,7 @@ then
     then
         if MPFR_ARCH_PATH=$(cd "$MPFR_ARCH_PATH" 2>/dev/null && pwd -P)
         then
-            mpfrPACKAGE="${MPFR_ARCH_PATH##*/}"
+            MPFR_PACKAGE="${MPFR_ARCH_PATH##*/}"
         else
             echo "ERROR: bad path for MPFR_ARCH_PATH"
             echo "stopping build"
@@ -409,8 +436,10 @@ then
         MPFR_ARCH_PATH=system
     fi
 else
-    GMP_ARCH_PATH="$mpfrBASE/$gmpPACKAGE"
-    MPFR_ARCH_PATH="$mpfrBASE/$mpfrPACKAGE"
+
+    # Respect the *ARCH_PATH if set
+    [ -d "$GMP_ARCH_PATH" ]  || GMP_ARCH_PATH="$archBASE/$GMP_PACKAGE"
+    [ -d "$MPFR_ARCH_PATH" ] || MPFR_ARCH_PATH="$archBASE/$MPFR_PACKAGE"
 fi
 
 #------------------------------------------------------------------------------
@@ -418,27 +447,27 @@ fi
 cat<<SUMMARY
 CGAL configuration
 ------------------
-    CGAL    = $cgalPACKAGE
-    BOOST   = $boostPACKAGE
-    GMP     = $gmpPACKAGE
-    MPFR    = $mpfrPACKAGE
+    CGAL    = $CGAL_PACKAGE
+    BOOST   = $BOOST_PACKAGE
+    GMP     = $GMP_PACKAGE
+    MPFR    = $MPFR_PACKAGE
 ------------------
 SUMMARY
 
 #
 # build information recorded for later use
 #
-buildInfoFile=$CGAL_ARCH_PATH/share/openfoam-build
+buildInfoFile="$CGAL_PREFIX"/share/openfoam-build
 
 recordCGALinfo()
 {
-    CGAL_VERSION=$(sed -ne 's/^ *# *define *CGAL_VERSION_NR *\([0-9][0-9]*\).*$/\1/p' $CGAL_ARCH_PATH/include/CGAL/version.h 2>/dev/null)
+    CGAL_VERSION=$(sed -ne 's/^ *# *define *CGAL_VERSION_NR *\([0-9][0-9]*\).*$/\1/p' $CGAL_PREFIX/include/CGAL/version.h 2>/dev/null)
 
-    cat<<BUILD_INFO > $buildInfoFile
+    cat<<BUILD_INFO > "$buildInfoFile"
 # Information from OpenFOAM build on '$(date)'
 #
-CGAL=${CGAL_ARCH_PATH##*/}
-BOOST=${BOOST_ARCH_PATH##*/}
+CGAL=${CGAL_PREFIX##*/}
+BOOST=${BOOST_PREFIX##*/}
 GMP=${GMP_ARCH_PATH##*/}
 MPFR=${MPFR_ARCH_PATH##*/}
 CGAL_VERSION=$CGAL_VERSION
@@ -477,10 +506,10 @@ cgalIsCurrent()
     local libDirName="lib$WM_COMPILER_LIB_ARCH"
 
     echo "checking information from existing build ..."
-    echo "  ${CGAL_ARCH_PATH}"
+    echo "  ${CGAL_PREFIX}"
 
-    infoValueEq CGAL  "${CGAL_ARCH_PATH##*/}"     "$info" || return 1
-    infoValueEq BOOST "${BOOST_ARCH_PATH##*/}"    "$info" || return 1
+    infoValueEq CGAL  "${CGAL_PREFIX##*/}"     "$info" || return 1
+    infoValueEq BOOST "${BOOST_PREFIX##*/}"    "$info" || return 1
     infoValueEq GMP   "${GMP_ARCH_PATH##*/}"      "$info" || return 1
     infoValueEq MPFR  "${MPFR_ARCH_PATH##*/}"     "$info" || return 1
     infoValueEq BOOST_VERSION "${BOOST_VERSION}"  "$info" || return 1
@@ -494,48 +523,44 @@ cgalIsCurrent()
 if [ -z "$optForce" ] \
  && cgalIsCurrent
 then
-    echo "    ${CGAL_ARCH_PATH##*/} build appears to be up-to-date - skipping"
+    echo "    ${CGAL_PREFIX##*/} build appears to be up-to-date - skipping"
     echo
     exit 0
 else
 (
-    # Remove any existing build folder and recreate
-    if [ -d "$CGAL_BUILD_DIR" ]
-    then
-        echo "removing old build directory"
-        echo "    $CGAL_BUILD_DIR"
-        rm -rf "$CGAL_BUILD_DIR"
-    fi
-    mkdir -p "$CGAL_BUILD_DIR"
+    export GIT_DIR="$CGAL_SOURCE/.git"
+    PKG_BUILD="$buildBASE/$CGAL_PACKAGE"
 
-    cd "$CGAL_BUILD_DIR" || exit
-    export GIT_DIR="$CGAL_SOURCE_DIR/.git" # Mask seeing our own git-repo
+    # Remove existing build
+    rm -rf "$PKG_BUILD"
+    mkdir -p "$PKG_BUILD"
+    cd "$PKG_BUILD" || exit
 
     unset configBoost configGmp configMpfr
     echo "----"
-    echo "Configuring $cgalPACKAGE with boost $BOOST_VERSION"
-    echo "    Source         : $CGAL_SOURCE_DIR"
-    echo "    Build          : $CGAL_BUILD_DIR"
-    echo "    Target         : $CGAL_ARCH_PATH"
+    echo "Configuring $CGAL_PACKAGE with boost $BOOST_VERSION"
+    echo "    Source         : $CGAL_SOURCE"
+    echo "    Build          : $CGAL_BUILD"
+    echo "    Target         : $CGAL_PREFIX"
 
 
     # See http://doc.cgal.org/latest/Manual/installation.html
-    if _foamIsSystem "$boostPACKAGE"
+    if _foamIsSystem "$BOOST_PACKAGE"
     then
         # Tagged as 'system' but could actually point to a central location
-        if [ -d "$BOOST_ARCH_PATH/include" ]
+        if [ -d "$BOOST_PREFIX/include" ]
         then
-            echo "    boost          : ${BOOST_ARCH_PATH##*/}"
-            configBoost="-DBOOST_ROOT=$BOOST_ARCH_PATH"
+            echo "    boost          : ${BOOST_PREFIX##*/}"
+            configBoost="-DBOOST_ROOT=$BOOST_PREFIX"
         else
             echo "    boost          : system"
         fi
 
         ## For system - possible that /usr/lib64 not being found?
         ## configBoost="-DBoost_LIBRARY_DIRS=$boostLib"
-    elif [ -d "$BOOST_ARCH_PATH" ]
+    elif [ -d "$BOOST_PREFIX" ]
     then
-        echo "    boost          : $boostPACKAGE"
+        echo "    boost          : $BOOST_PACKAGE"
         configBoost=$(cat <<CMAKE_OPTIONS
  -DBoost_INCLUDE_DIR=$boostInc
  -DBoost_LIBRARY_DIRS=$boostLib
@@ -557,11 +582,12 @@ CMAKE_OPTIONS
         configGmp="-DCGAL_DISABLE_GMP=TRUE"  # Also used for mpfr
     elif [ -d "$GMP_ARCH_PATH" ]
     then
-        echo "    gmp            : $gmpPACKAGE"
+        echo "    gmp            : $GMP_PACKAGE"
 
+        # Alternative: export GMP_DIR=...  hint
         for libdir in \
-            $GMP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH \
-            $GMP_ARCH_PATH/lib \
+            "$GMP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH" \
+            "$GMP_ARCH_PATH"/lib \
         ;
         do
             if [ -f "$libdir/libgmp$EXT_SO" ]
@@ -588,11 +614,12 @@ CMAKE_OPTIONS
         configGmp="-DCGAL_DISABLE_GMP=TRUE"  # Also used for mpfr
     elif [ -d "$MPFR_ARCH_PATH" ]
     then
-        echo "    mpfr           : $mpfrPACKAGE"
+        echo "    mpfr           : $MPFR_PACKAGE"
 
+        # Alternative: export MPFR_DIR=...  hint
         for libdir in \
-            $MPFR_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH \
-            $MPFR_ARCH_PATH/lib \
+            "$MPFR_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH" \
+            "$MPFR_ARCH_PATH/lib" \
         ;
         do
             if [ -f "$libdir/libmpfr$EXT_SO" ]
@@ -633,10 +660,10 @@ CMAKE_OPTIONS
     # For CGAL < 4.9, for installation into lib64/, not lib/
     # Name only (not path) for CGAL_INSTALL_LIB_DIR
     echo "----"
-    set -x
-    $cmake \
-        -DCMAKE_INSTALL_PREFIX=$CGAL_ARCH_PATH \
-        -DCGAL_INSTALL_LIB_DIR=lib$WM_COMPILER_LIB_ARCH \
+    set -x && \
+    ${cmake:?} \
+        -DCMAKE_INSTALL_PREFIX="$CGAL_PREFIX" \
+        -DCGAL_INSTALL_LIB_DIR="lib$WM_COMPILER_LIB_ARCH" \
         -DCMAKE_BUILD_TYPE=Release \
         -DWITH_CGAL_Core=OFF \
         -DWITH_CGAL_ImageIO=OFF \
@@ -644,25 +671,26 @@ CMAKE_OPTIONS
         $cmakeDefs \
         $configBoost $configGmp $configMpfr \
         ${WM_QUIET:+-DCMAKE_RULE_MESSAGES=OFF} \
-        $CGAL_SOURCE_DIR \
-    && set +x \
+        "$CGAL_SOURCE" \
     && make -j $WM_NCOMPPROCS \
+    && set +x \
     && make install || exit 1
 
     echo "----"
-    echo "create '\$CGAL_ARCH_PATH/share/files'"
+    echo "create '\$CGAL_PREFIX/share/files'"
     echo "----"
-    mkdir -p $CGAL_ARCH_PATH/share/src
-    rm -f $CGAL_ARCH_PATH/share/files
+    mkdir -p "$CGAL_PREFIX"/share/src
+    rm -f "$CGAL_PREFIX"/share/files
 
     for i in assertions.cpp io.cpp MP_Float.cpp Random.cpp
     do
-        if [ -e "$CGAL_SOURCE_DIR/src/CGAL/$i" ]
+        if [ -e "$CGAL_SOURCE/src/CGAL/$i" ]
         then
-            \cp $CGAL_SOURCE_DIR/src/CGAL/$i $CGAL_ARCH_PATH/share/src/
-            echo "\${CGAL_ARCH_PATH}/share/src/$i" >> $CGAL_ARCH_PATH/share/files
+            \cp "$CGAL_SOURCE/src/CGAL/$i" "$CGAL_PREFIX"/share/src/
+            echo "\${CGAL_PREFIX}/share/src/$i" >> "$CGAL_PREFIX"/share/files
         fi
     done
+
 
     # Record our build-status
     recordCGALinfo
diff --git a/makeCmake b/makeCmake
--- a/makeCmake
+++ b/makeCmake
@@ -7,7 +7,7 @@
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 #     Copyright (C) 2011 OpenFOAM Foundation
-#     Copyright (C) 2016-2020 OpenCFD Ltd.
+#     Copyright (C) 2016-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -24,38 +24,40 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 
-# Special purpose script - no default version.
-unset cmakePACKAGE
+# Special purpose script - no default version
+unset PACKAGE
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions cmake; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] cmake-VERSION
+Usage: ${0##*/} [OPTION] cmake-VERSION
 options:
   -force        Force compilation, even if binary already exists
   -gcc          Force use of gcc/g++
   -link         Create additional symlink as 'cmake-system'
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
-* build cmake
-      ${cmakePACKAGE:-'unspecified'}
+* Build cmake
+      ${PACKAGE:-[unspecified]}
 
 USAGE
-    showDownloadHint CMAKE
-    exit 1
+    showDownloadHint cmake
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler          # Compiler info for CMake/configure
@@ -67,13 +69,15 @@ while [ "$#" -gt 0 ]
 do
     case "$1" in
     '') ;;      # Ignore empty
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
     -force)     optForce=true ;;
     -link)      optLink=true ;;
 
+    cmake/* | sources/cmake* | \
     cmake-[0-9]*)
-        cmakePACKAGE="${1%%/}"
+        PACKAGE="${1%%/}"
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -82,55 +86,60 @@ do
     shift
 done
 
-[ -n "$cmakePACKAGE" ] || die "The cmake-VERSION was not specified"
-
-if _foamIsSystem "$cmakePACKAGE"
+if [ -z "$PACKAGE" ]
 then
-    unset optLink # basic sanity - cannot
+    die "The CMAKE package/version not specified"
+fi
+
+if _foamIsSystem "$PACKAGE"
+then
+    unset optLink # basic sanity - cannot create a link
 fi
 
 #------------------------------------------------------------------------------
 #
 # Build CMAKE
-#   CMAKE_SOURCE_DIR : location of the original sources
-#   CMAKE_ARCH_PATH  : installation directory
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
 
-CMAKE_SOURCE_DIR=$sourceBASE/$cmakePACKAGE
-CMAKE_ARCH_PATH=$installBASE/$cmakePACKAGE
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
+PACKAGE="$(basename "$PACKAGE")"
+PKG_PREFIX="$installBASE/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"
+
 
 if [ -z "$optForce" ] \
-&& [ -d "$CMAKE_ARCH_PATH" ] \
-&& [ -r "$CMAKE_ARCH_PATH/bin/cmake" ]
+&& [ -d "$PKG_PREFIX" ] \
+&& [ -r "$PKG_PREFIX/bin/cmake" ]
 then
-    echo "Already built: $cmakePACKAGE"
+    echo "Already built: $PACKAGE"
 else
-    echo "Starting build: $cmakePACKAGE"
+    echo "Starting build: $PACKAGE"
     (
-        buildDIR=$buildBASE/$cmakePACKAGE
+        PKG_BUILD="$buildBASE/$PACKAGE"
+        cd "$PKG_SOURCE" || exit
+        make distclean 2>/dev/null || true
 
-        cd "$CMAKE_SOURCE_DIR" || exit
-        export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-        make distclean 2>/dev/null
+        rm -rf "$PKG_BUILD"
+        mkdir -p "$PKG_BUILD"
 
-        rm -rf $buildDIR
-        mkdir -p $buildDIR
-        cd $buildDIR
-
-        $CMAKE_SOURCE_DIR/bootstrap \
-            --prefix=$CMAKE_ARCH_PATH \
+        cd "$PKG_BUILD" && \
+        "$PKG_SOURCE"/bootstrap \
+            --prefix="$PKG_PREFIX" \
         && time make -j $WM_NCOMPPROCS \
         && make install \
-        && echo "Built: $cmakePACKAGE"
+        && echo "Built: $PACKAGE"
     ) || {
-        echo "Error building: $cmakePACKAGE"
+        echo "Error building: $PACKAGE"
         exit 1
     }
 fi
 
-if [ "$optLink" = true ] && [ -x "$CMAKE_ARCH_PATH/bin/cmake" ]
+if [ "$optLink" = true ] && [ -x "$PKG_PREFIX/bin/cmake" ]
 then
 (
-    cd "${CMAKE_ARCH_PATH%/*}" || exit
+    cd "${PKG_PREFIX%/*}" || exit
     if [ -L cmake-system ]
     then
         rm cmake-system
@@ -138,7 +147,7 @@ then
     then
         exit 2
     fi
-    ln -svf "$cmakePACKAGE" cmake-system
+    ln -svf "$PACKAGE" cmake-system
 )
 fi
 
diff --git a/makeFFTW b/makeFFTW
--- a/makeFFTW
+++ b/makeFFTW
@@ -6,7 +6,7 @@
 #   \\  /    A nd           | www.openfoam.com
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
-#     Copyright (C) 2016-2020 OpenCFD Ltd.
+#     Copyright (C) 2016-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -47,39 +47,40 @@ then
     exit 2
 fi
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
-
-# FFTW version from OpenFOAM etc/config.sh file:
+# Obtain version from OpenFOAM etc/config.sh file:
 _foamConfig FFTW
 
-fftwPACKAGE="${fftw_version:-fftw-system}"
+PACKAGE="${fftw_version:-none}"
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions fftw; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [fftw-VERSION] [-- configure-options]
+Usage: ${0##*/} [OPTION] [fftw-VERSION] [-- configure-options]
 options:
   -force        Force compilation, even if include/library already exists
   -gcc          Force use of gcc/g++
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
 * build FFTW with
-      ${fftwPACKAGE:-'unspecified FFTW version'}
+      ${PACKAGE:-[unspecified]}
 
 USAGE
-    showDownloadHint FFTW
-    exit 1
+    showDownloadHint fftw
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler          # Compiler info for CMake/configure
@@ -92,12 +93,14 @@ do
     case "$1" in
     '') ;;      # Ignore empty
     --) break;; # Extra configure options (leave on $@ for later detection)
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
     -force)     optForce=true ;;
 
+    fftw/* | sources/fftw* | \
     fftw-[0-9]* | fftw_[0-9]* | fftw-system )
-        fftwPACKAGE="${1%%/}"
+        PACKAGE="${1%%/}"
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -106,44 +109,43 @@ do
     shift
 done
 
-[ -n "$fftwPACKAGE" ] || die "The fftw-VERSION was not specified"
-
-# Nothing to build
-if _foamIsNone "$fftwPACKAGE"
+if [ -z "$PACKAGE" ]
 then
-    echo "Using fftw-none (skip ThirdParty build of FFTW)"
-    exit 0
-elif _foamIsSystem "$fftwPACKAGE"
+    die "The FFTW package/version not specified"
+elif _foamIsNone "$PACKAGE" || _foamIsSystem "$PACKAGE"
 then
-    echo "Using fftw-system (skip ThirdParty build of FFTW)"
+    echo "Using none/system (skip ThirdParty build of FFTW)"
     exit 0
 fi
 
 #------------------------------------------------------------------------------
 #
 # Build FFTW
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
+#
 # For 64-bit
 # - FFTW itself will normally build into 'lib64',
 #   but provide --libdir on configure to be 100% certain
 # - Third-Party builds into 'lib64'
 # - system is normally built into 'lib64'
-#
-#   FFTW_SOURCE_DIR : location of the original sources
-#   FFTW_ARCH_PATH  : installation directory
 
-FFTW_SOURCE_DIR="$sourceBASE/$fftwPACKAGE"
-FFTW_ARCH_PATH="$installBASE/$fftwPACKAGE"
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
+PACKAGE="$(basename "$PKG_SOURCE")"
+PKG_PREFIX="$installBASE/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"
 
 if [ -z "$optForce" ] \
 && {
-    [ -r "$FFTW_ARCH_PATH/lib/libfftw3$EXT_SO" ] \
- || [ -r "$FFTW_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH/libfftw3$EXT_SO" ] \
- || [ -r "$FFTW_ARCH_PATH/bin/libfftw3-3$EXT_SO" ]  # Windows
+    [ -r "$PKG_PREFIX/lib/libfftw3$EXT_SO" ] \
+ || [ -r "$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH/libfftw3$EXT_SO" ] \
+ || [ -r "$PKG_PREFIX/bin/libfftw3-3$EXT_SO" ]  # Windows
 }
 then
-    echo "FFTW already built : $FFTW_ARCH_PATH"
+    echo "FFTW already built : $PKG_PREFIX"
 else
-    echo "Starting build: FFTW ($fftwPACKAGE)"
+    echo "Starting build: FFTW ($PACKAGE)"
     echo
 
     (
@@ -174,32 +176,30 @@ else
 
         # End of configuration options
         # ----------------------------
-        buildDIR="$buildBASE/$fftwPACKAGE"
+        PKG_BUILD="$buildBASE/$PACKAGE"
+        cd "$PKG_SOURCE" || exit
 
-        cd "$FFTW_SOURCE_DIR" || exit
-        export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
+        rm -rf "$PKG_PREFIX"
+        rm -rf "$PKG_BUILD"
+        mkdir -p "$PKG_BUILD"
 
-        rm -rf "$FFTW_ARCH_PATH"
-        rm -rf "$buildDIR"
-        mkdir -p "$buildDIR"
-        cd "$buildDIR"
-
-        set -x
-        "$FFTW_SOURCE_DIR"/configure \
-            --prefix="$FFTW_ARCH_PATH" \
-            --libdir="$FFTW_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH" \
+        cd "$PKG_BUILD" && set -x && \
+        "$PKG_SOURCE"/configure \
+            --prefix="$PKG_PREFIX" \
+            --libdir="$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH" \
             --enable-shared --disable-static \
             --disable-fortran \
             $configOpt \
         && set +x \
         && make -j $WM_NCOMPPROCS \
         && make install \
-        && echo "Built $fftwPACKAGE" \
-        && pkgconfigAdjust "$FFTW_ARCH_PATH"
+        && echo "Built: $PACKAGE" \
+        && pkgconfigAdjust "$PKG_PREFIX"
     ) || {
-        echo "Error building: FFTW"
+        echo "Error building: $PACKAGE"
         exit 1
     }
+
 fi
 
 #------------------------------------------------------------------------------
diff --git a/makeGcc b/makeGcc
--- a/makeGcc
+++ b/makeGcc
@@ -7,7 +7,7 @@
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 #     Copyright (C) 2011-2016 OpenFOAM Foundation
-#     Copyright (C) 2016-2020 OpenCFD Ltd.
+#     Copyright (C) 2016-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -33,14 +33,16 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 unset GMP_ARCH_PATH MPFR_ARCH_PATH                                  # Purge old
 
@@ -50,18 +52,17 @@ WM_COMPILER_TYPE=ThirdParty                # Ensure we get the correct settings
 # Default GCC, mpfr, gmp and mpc versions from OpenFOAM etc/config.sh file:
 _foamConfig compiler
 
-gmpPACKAGE=${gmp_version:-gmp-system}
-mpfrPACKAGE=${mpfr_version:-mpfr-system}
-mpcPACKAGE=${mpc_version:-mpc-system}
-gccPACKAGE=$gcc_version
+GMP_PACKAGE="${gmp_version:-gmp-system}"
+MPFR_PACKAGE="${mpfr_version:-mpfr-system}"
+MPC_PACKAGE="${mpc_version:-mpc-system}"
+GCC_PACKAGE="$gcc_version"
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions gcc gmp mpfr mpc; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [gcc-VERSION] [gmp-VERSION] [mpfr-VERSION] [mpc-VERSION]
+Usage: ${0##*/} [OPTION] [gcc-VERSION] [gmp-VERSION] [mpfr-VERSION] [mpc-VERSION]
 options:
   -clang            Force clang/clang++ for building
   -m32 | -m64       32-bit or 64-bit (default) ABI
@@ -69,20 +70,21 @@ options:
   -no-multilib      for 64-bit systems without 32-bit support (DEFAULT)
   -no-threadsafe    disable mpfr thread-safe (default is auto-detect)
   -system           use system versions for gmp/mpfr/mpc
-  -help
+  -list             List available unpacked source versions
+  -help             Display usage help
 
-* build combinations of gmp, mpfr, mpc and gcc
-      $gmpPACKAGE
-      $mpfrPACKAGE
-      $mpcPACKAGE
-      ${gccPACKAGE:-'unspecified GCC version'}
+* Build combinations of gmp, mpfr, mpc and gcc
+      ${GMP_PACKAGE:-[gmp unspecified]}
+      ${MPFR_PACKAGE:-[mpfr unspecified]}
+      ${MPC_PACKAGE:-[mpc unspecified]}
+      ${GCC_PACKAGE:-[gcc unspecified]}
 
 USAGE
-    showDownloadHint GCC
-    showDownloadHint GMP
-    showDownloadHint MPFR
-    showDownloadHint MPC
-    exit 1
+    showDownloadHint gcc
+    showDownloadHint gmp
+    showDownloadHint mpfr
+    showDownloadHint mpc
+    exit 0 # Clean exit
 }
 #------------------------------------------------------------------------------
 optArch=64      # Use 64-bit ABI
@@ -96,7 +98,8 @@ while [ "$#" -gt 0 ]
 do
     case "$1" in
     '') ;;      # Ignore empty
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -clang)     # Force use of clang/clang++ for building
         export CC=clang
         export CXX=clang++
@@ -115,27 +118,35 @@ do
         optThreadSafe=disable
         ;;
     -sys*)
-        gmpPACKAGE="gmp-system"
-        mpfrPACKAGE="mpfr-system"
-        mpcPACKAGE="mpc-system"
+        GMP_PACKAGE="gmp-system"
+        MPFR_PACKAGE="mpfr-system"
+        MPC_PACKAGE="mpc-system"
         unset GMP_ARCH_PATH MPFR_ARCH_PATH
         ;;
+
+    gmp/* | sources/gmp* |\
     gmp-[0-9]* | gmp-system)
-        gmpPACKAGE="${1%%/}"
+        GMP_PACKAGE="${1%%/}"
         unset GMP_ARCH_PATH
         ;;
+
+    mpfr/* | sources/mpfr* |\
     mpfr-[0-9]* | mpfr-system)
-        mpfrPACKAGE="${1%%/}"
+        MPFR_PACKAGE="${1%%/}"
         unset MPFR_ARCH_PATH
         ;;
+
+    mpc/* | sources/mpc* |\
     mpc-[0-9]* | mpc-system)
-        mpcPACKAGE="${1%%/}"
+        MPC_PACKAGE="${1%%/}"
         ;;
+
+    gcc/* | sources/gcc* |\
     gcc-[0-9]* | gcc-system)
-        gccPACKAGE="${1%%/}"
+        GCC_PACKAGE="${1%%/}"
         ;;
     [0-9]*)
-        gccPACKAGE="gcc-${1%%/}"
+        GCC_PACKAGE="gcc-${1%%/}"
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -144,37 +155,58 @@ do
     shift
 done
 
-[ -n "$gccPACKAGE" ] || die "The gcc-VERSION was not specified"
+[ -n "$GCC_PACKAGE" ] || die "The gcc-VERSION was not specified"
 
 cat<<SUMMARY
 GCC configuration
 ------------------
-    GCC     = $gccPACKAGE
     ABI     = $optArch
-    GMP     = $gmpPACKAGE
-    MPFR    = $mpfrPACKAGE
-    MPC     = $mpcPACKAGE
+    GCC     = $GCC_PACKAGE
+    GMP     = $GMP_PACKAGE
+    MPFR    = $MPFR_PACKAGE
+    MPC     = $MPC_PACKAGE
 ------------------
 Using CC    = $CC $CFLAGS
 Using CXX   = $CXX $CXXFLAGS
 SUMMARY
 
 #------------------------------------------------------------------------------
-# Build/install without compiler name
-buildBASE=$WM_THIRD_PARTY_DIR/build/$WM_ARCH$WM_COMPILER_ARCH
-installBASE=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH
+# !Build/install locations with arch name only (NO compiler name)!
+buildBASE="$(dirname "$buildBASE")/$WM_ARCH$WM_COMPILER_ARCH"
+installBASE="$(dirname "$installBASE")/$WM_ARCH$WM_COMPILER_ARCH"
 
-GCC_ARCH_PATH=$installBASE/$gccPACKAGE
-GMP_ARCH_PATH=$installBASE/$gmpPACKAGE
-MPFR_ARCH_PATH=$installBASE/$mpfrPACKAGE
-MPC_ARCH_PATH=$installBASE/$mpcPACKAGE
+# gcc
+GCC_SOURCE="$(findSourceDir "$GCC_PACKAGE")"
+GCC_PACKAGE="$(basename "$GCC_PACKAGE")"
+GCC_PREFIX="$installBASE/$GCC_PACKAGE"
+
+# gmp
+GMP_SOURCE="$(findSourceDir "$GMP_PACKAGE")"
+GMP_PACKAGE="$(basename "$GMP_PACKAGE")"
+GMP_PREFIX="$installBASE/$GMP_PACKAGE"
+
+# mpc
+MPC_SOURCE="$(findSourceDir "$MPC_PACKAGE")"
+MPC_PACKAGE="$(basename "$MPC_PACKAGE")"
+MPC_PREFIX="$installBASE/$MPC_PACKAGE"
+
+# mpfr
+MPFR_SOURCE="$(findSourceDir "$MPFR_PACKAGE")"
+MPFR_PACKAGE="$(basename "$MPFR_PACKAGE")"
+MPFR_PREFIX="$installBASE/$MPFR_PACKAGE"
+
+
+# Override as per config file (if any)
+[ -n "$GMP_ARCH_PATH" ]  && GMP_PREFIX="$GMP_ARCH_PATH"
+[ -n "$MPFR_ARCH_PATH" ] && MPFR_PREFIX="$MPFR_ARCH_PATH"
+
 
 # Prefix <dir> to LD_LIBRARY_PATH, if it exists. 0 on success, 1 on failure
 addLib()
 {
     if [ -d "$1" ]
     then
-        export LD_LIBRARY_PATH=$1:$LD_LIBRARY_PATH
+        export LD_LIBRARY_PATH="$1:$LD_LIBRARY_PATH"
         return 0
     else
         return 1
@@ -186,47 +218,47 @@ addLib()
 # Build GMP
 # ================
 echo "---------------"
-if [ -d "$GMP_ARCH_PATH" ]
+if [ -d "$GMP_PREFIX" ]
 then
-    echo "Already built: $gmpPACKAGE"
-elif _foamIsSystem $GMP_ARCH_PATH
+    echo "Already built: $GMP_PREFIX"
+elif _foamIsSystem "$GMP_PREFIX"
 then
-    echo "Using gmp-system"
+    echo "Using system gmp"
 else
-    echo "Starting build: $gmpPACKAGE"
+    echo "Starting build: $GMP_PACKAGE"
     echo
 (
-    sourceDIR=$sourceBASE/$gmpPACKAGE
-    buildDIR=$buildBASE/$gmpPACKAGE
+    PKG_SOURCE="$GMP_SOURCE"
+    PKG_PREFIX="$GMP_PREFIX"
+    PKG_BUILD="$buildBASE/$GMP_PACKAGE"
+    export GIT_DIR="$PKG_SOURCE/.git"
 
-    cd "$sourceDIR" || exit
-    export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-    make distclean 2>/dev/null
+    cd "$PKG_SOURCE" || exit
+    make distclean 2>/dev/null || true
 
-    rm -rf $buildDIR
-    mkdir -p $buildDIR
-    cd $buildDIR
+    rm -rf "$PKG_BUILD"
+    mkdir -p "$PKG_BUILD"
 
-    set -x
-    $sourceDIR/configure ABI=$optArch \
-        --prefix=$GMP_ARCH_PATH \
-        --libdir=$GMP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH \
+    cd "$PKG_BUILD" && set -x && \
+    "$PKG_SOURCE"/configure ABI="$optArch" \
+        --prefix="$PKG_PREFIX" \
+        --libdir="$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH" \
         --enable-cxx \
     && set +x \
     && make -j $WM_NCOMPPROCS \
     && make install \
-    && echo "Built: $gmpPACKAGE"
+    && echo "Built: $GMP_PACKAGE"
 ) || {
-    echo "Error building: $gmpPACKAGE"
+    echo "Error building: $GMP_PACKAGE"
     exit 1
 }
 fi
 
-if addLib "$GMP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH"
+if addLib "$GMP_PREFIX/lib$WM_COMPILER_LIB_ARCH"
 then
     configGMP=$(cat <<CONFIG_OPTIONS
-    --with-gmp-include=$GMP_ARCH_PATH/include
-    --with-gmp-lib=$GMP_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH
+    --with-gmp-include=$GMP_PREFIX/include
+    --with-gmp-lib=$GMP_PREFIX/lib$WM_COMPILER_LIB_ARCH
 CONFIG_OPTIONS
 )
 else
@@ -238,51 +270,51 @@ fi
 # Build MPFR
 # ================
 echo "---------------"
-if [ -d "$MPFR_ARCH_PATH" ]
+if [ -d "$MPFR_PREFIX" ]
 then
-    echo "Already built: $mpfrPACKAGE"
-elif _foamIsSystem $MPFR_ARCH_PATH
+    echo "Already built: $MPFR_PACKAGE"
+elif _foamIsSystem "$MPFR_PREFIX"
 then
-    echo "Using mpfr-system"
+    echo "Using system mpfr"
 else
-    echo "Starting build: $mpfrPACKAGE"
+    echo "Starting build: $MPFR_PACKAGE"
     echo
 (
-    sourceDIR=$sourceBASE/$mpfrPACKAGE
-    buildDIR=$buildBASE/$mpfrPACKAGE
+    PKG_SOURCE="$MPFR_SOURCE"
+    PKG_PREFIX="$MPFR_PREFIX"
+    PKG_BUILD="$buildBASE/$MPFR_PACKAGE"
+    export GIT_DIR="$PKG_SOURCE/.git"
 
-    cd "$sourceDIR" || exit
-    export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-    make distclean 2>/dev/null
+    cd "$PKG_SOURCE" || exit
+    make distclean 2>/dev/null || true
 
-    rm -rf $buildDIR
-    mkdir -p $buildDIR
-    cd $buildDIR
+    rm -rf "$PKG_BUILD"
+    mkdir -p "$PKG_BUILD"
 
     unset configOpt
     # explicitly enable/disable thread-safe
     [ -n "$optThreadSafe" ] && configOpt="--${optThreadSafe}-thread-safe"
 
-    set -x
-    $sourceDIR/configure ABI=$optArch \
-        --prefix=$MPFR_ARCH_PATH \
-        --libdir=$MPFR_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH \
+    cd "$PKG_BUILD" && set -x && \
+    "$PKG_SOURCE"/configure ABI="$optArch" \
+        --prefix="$PKG_PREFIX" \
+        --libdir="$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH" \
         $configGMP $configOpt \
     && set +x \
     && make -j $WM_NCOMPPROCS \
     && make install \
-    && echo "Built: $mpfrPACKAGE"
+    && echo "Built: $MPFR_PACKAGE"
 ) || {
-    echo "Error building: $mpfrPACKAGE"
+    echo "Error building: $MPFR_PACKAGE"
     exit 1
 }
 fi
 
-if addLib "$MPFR_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH"
+if addLib "$MPFR_PREFIX/lib$WM_COMPILER_LIB_ARCH"
 then
     configMPFR=$(cat <<CONFIG_OPTIONS
-    --with-mpfr-include=$MPFR_ARCH_PATH/include \
-    --with-mpfr-lib=$MPFR_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH
+    --with-mpfr-include=$MPFR_PREFIX/include \
+    --with-mpfr-lib=$MPFR_PREFIX/lib$WM_COMPILER_LIB_ARCH
 CONFIG_OPTIONS
 )
 else
@@ -294,47 +326,47 @@ fi
 # Build MPC
 # ================
 echo "---------------"
-if [ -d "$MPC_ARCH_PATH" ]
+if [ -d "$MPC_PREFIX" ]
 then
-    echo "Already built: $mpcPACKAGE"
-elif _foamIsSystem $MPC_ARCH_PATH
+    echo "Already built: $MPC_PACKAGE"
+elif _foamIsSystem "$MPC_PREFIX"
 then
-    echo "Using mpc-system"
+    echo "Using system mpc"
 else
-    echo "Starting build: $mpcPACKAGE"
+    echo "Starting build: $MPC_PACKAGE"
     echo
 (
-    sourceDIR=$sourceBASE/$mpcPACKAGE
-    buildDIR=$buildBASE/$mpcPACKAGE
+    PKG_SOURCE="$MPC_SOURCE"
+    PKG_PREFIX="$MPC_PREFIX"
+    PKG_BUILD="$buildBASE/$MPC_PACKAGE"
+    export GIT_DIR="$PKG_SOURCE/.git"
 
-    cd "$sourceDIR" || exit
-    export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-    make distclean 2>/dev/null
+    cd "$PKG_SOURCE" || exit
+    make distclean 2>/dev/null || true
 
-    rm -rf $buildDIR
-    mkdir -p $buildDIR
-    cd $buildDIR
+    rm -rf "$PKG_BUILD"
+    mkdir -p "$PKG_BUILD"
 
-    set -x
-    $sourceDIR/configure ABI=$optArch \
-        --prefix=$MPC_ARCH_PATH \
-        --libdir=$MPC_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH \
+    cd "$PKG_BUILD" && set -x && \
+    "$PKG_SOURCE"/configure ABI="$optArch" \
+        --prefix="$PKG_PREFIX" \
+        --libdir="$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH" \
         $configGMP $configMPFR \
     && set +x \
     && make -j $WM_NCOMPPROCS \
     && make install \
-    && echo "Built: $mpcPACKAGE"
+    && echo "Built: $MPC_PACKAGE"
 ) || {
-    echo "Error building: $mpcPACKAGE"
+    echo "Error building: $MPC_PACKAGE"
     exit 1
 }
 fi
 
-if addLib "$MPC_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH"
+if addLib "$MPC_PREFIX/lib$WM_COMPILER_LIB_ARCH"
 then
     configMPC=$(cat <<CONFIG_OPTIONS
-    --with-mpc-include=$MPC_ARCH_PATH/include \
-    --with-mpc-lib=$MPC_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH
+    --with-mpc-include=$MPC_PREFIX/include \
+    --with-mpc-lib=$MPC_PREFIX/lib$WM_COMPILER_LIB_ARCH
 CONFIG_OPTIONS
 )
 else
@@ -350,35 +382,35 @@ fi
 # or specify -no-multilib on the command-line
 #
 echo "---------------"
-if [ -d "$GCC_ARCH_PATH" ]
+if [ -d "$GCC_PREFIX" ]
 then
-    echo "Already built: $gccPACKAGE"
-elif _foamIsSystem $GCC_ARCH_PATH
+    echo "Already built: $GCC_PACKAGE"
+elif _foamIsSystem "$GCC_PREFIX"
 then
-    echo "Using gcc-system"
+    echo "Using system gcc"
 else
-    echo "Starting build: $gccPACKAGE"
+    echo "Starting build: $GCC_PACKAGE"
     echo
 (
-    sourceDIR=$sourceBASE/$gccPACKAGE
-    buildDIR=$buildBASE/$gccPACKAGE
+    PKG_SOURCE="$GCC_SOURCE"
+    PKG_PREFIX="$GCC_PREFIX"
+    PKG_BUILD="$buildBASE/$GCC_PACKAGE"
+    export GIT_DIR="$PKG_SOURCE/.git"
 
-    cd "$sourceDIR" || exit
-    export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-    make distclean 2>/dev/null
+    cd "$PKG_SOURCE" || exit
+    make distclean 2>/dev/null || true
 
-    rm -rf $buildDIR
-    mkdir -p $buildDIR
-    cd $buildDIR
+    rm -rf "$PKG_BUILD"
+    mkdir -p "$PKG_BUILD"
 
     unset configOpt
     # with/without multi-lib (32-bit support on 64-bit systems)
     [ -n "$optMultilib" ] && configOpt="--${optMultilib}-multilib"
 
-    set -x
-    $sourceDIR/configure \
-        --prefix=$GCC_ARCH_PATH \
-        --with-pkgversion=OpenFOAM \
+    cd "$PKG_BUILD" && set -x && \
+    "$PKG_SOURCE"/configure \
+        --prefix="$PKG_PREFIX" \
+        --with-pkgversion=www.openfoam.com \
         --enable-languages=c,c++ \
         --enable-__cxa_atexit \
         --enable-libstdcxx-allocator=new \
@@ -388,9 +420,9 @@ else
     && set +x \
     && make -j $WM_NCOMPPROCS \
     && make install \
-    && echo "Built: $gccPACKAGE"
+    && echo "Built: $GCC_PACKAGE"
 ) || {
-    echo "Error building: $gccPACKAGE"
+    echo "Error building: $GCC_PACKAGE"
     exit 1
 }
 fi
diff --git a/makeGperftools b/makeGperftools
--- a/makeGperftools
+++ b/makeGperftools
@@ -7,7 +7,7 @@
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 #     Copyright (C) 2012 OpenFOAM Foundation
-#     Copyright (C) 2016-2020 OpenCFD Ltd.
+#     Copyright (C) 2016-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -21,52 +21,59 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
-
-# Gperftools version from OpenFOAM etc/config.sh file:
+# Obtain version from OpenFOAM etc/config.sh file:
 _foamConfig gperftools
 
-gperftoolsPACKAGE=${gperftools_version:-gperftools-system}
+PACKAGE="${gperftools_version:-none}"
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions gperf; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [gperftools-VERSION]
+Usage: ${0##*/} [gperftools-VERSION]
 options:
+  -force        Force compilation, even if include/library already exists
   -gcc          Force use of gcc/g++
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
-* build gperftools
-      $gperftoolsPACKAGE
+* Build gperftools
+      ${PACKAGE:-[unspecified]}
 
 USAGE
-    showDownloadHint GPERFTOOLS
-    exit 1
+    showDownloadHint gperftools
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler          # Compiler info for CMake/configure
+
+unset optForce
 
 # Parse options
 while [ "$#" -gt 0 ]
 do
     case "$1" in
     '') ;;      # Ignore empty
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
+    -force)     optForce=true ;;
 
+    gperftools/* | sources/gperftools* |\
     gperftools-[0-9]* | gperftools-svn* | gperftools-git)
-        gperftoolsPACKAGE="${1%%/}"
+        PACKAGE="${1%%/}"
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -75,55 +82,56 @@ do
     shift
 done
 
-[ -n "$gperftoolsPACKAGE" ] || die "The gperftools-VERSION was not specified"
-
-# Nothing to build
-if _foamIsNone $gperftoolsPACKAGE
+if [ -z "$PACKAGE" ]
 then
-    echo "Using gperftools-none (skip ThirdParty build of gperftools)"
-    exit 0
-elif _foamIsSystem $gperftoolsPACKAGE
+    die "The GPERFTOOLS package/version not specified"
+elif _foamIsNone "$PACKAGE" || _foamIsSystem "$PACKAGE"
 then
-    echo "Using gperftools-system (skip ThirdParty build of gperftools)"
+    echo "Using none/system (skip ThirdParty build of GPERFTOOLS)"
     exit 0
 fi
 
 #------------------------------------------------------------------------------
 #
 # Build gperftools
-#
-GPERFTOOLS_SOURCE_DIR=$sourceBASE/$gperftoolsPACKAGE
-GPERFTOOLS_ARCH_PATH=$installBASE/$gperftoolsPACKAGE
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
+
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
+PACKAGE="$(basename "$PACKAGE")"
+PKG_PREFIX="$installBASE/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"
 
 echo "---------------"
-if [ -d "$GPERFTOOLS_ARCH_PATH" ]
+if [ -z "$optForce" ] \
+&& [ -d "$PKG_PREFIX" ]
 then
-    echo "Already built: $gperftoolsPACKAGE"
+    echo "Already built: $PACKAGE"
 else
-    echo "Starting build: $gperftoolsPACKAGE"
+    echo "Starting build: $PACKAGE"
     (
-        buildDIR=$buildBASE/$gperftoolsPACKAGE
+        PKG_BUILD="$buildBASE/$PACKAGE"
+        cd "$PKG_SOURCE" || exit
 
-        cd "$GPERFTOOLS_SOURCE_DIR" || exit
-        export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-        [ -e Makefile ] && make distclean 2>/dev/null
+        make distclean 2>/dev/null || true
 
-        rm -rf $GPERFTOOLS_ARCH_PATH
-        rm -rf $buildDIR
-        mkdir -p $buildDIR
-        cd $buildDIR
+        rm -rf "$PKG_PREFIX"
+        rm -rf "$PKG_BUILD"
+        mkdir -p "$PKG_BUILD"
 
-        set -x
-        $GPERFTOOLS_SOURCE_DIR/configure \
-            --prefix=$GPERFTOOLS_ARCH_PATH \
+        cd "$PKG_BUILD" && set -x && \
+        "$PKG_SOURCE"/configure \
+            --prefix="$PKG_PREFIX" \
         && set +x \
         && make -j $WM_NCOMPPROCS \
         && make install \
-        && echo "Built: $gperftoolsPACKAGE" \
+        && echo "Built: $PACKAGE" \
     ) || {
-        echo "Error building: $gperftoolsPACKAGE"
+        echo "Error building: $PACKAGE"
         exit 1
     }
+
 fi
 
 #------------------------------------------------------------------------------
diff --git a/makeHYPRE b/makeHYPRE
--- a/makeHYPRE
+++ b/makeHYPRE
@@ -6,7 +6,7 @@
 #   \\  /    A nd           | www.openfoam.com
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
-#     Copyright (C) 2018-2020 OpenCFD Ltd.
+#     Copyright (C) 2018-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -20,39 +20,46 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
+# Obtain version from etc/config.sh file:
 _foamConfig hypre
 
-hyprePACKAGE="${hypre_version:-hypre-system}"
+PACKAGE="${hypre_version:-none}"
 targetType=libso
 
+if nonStandardPlatforms  # Possibly unreliable inherited values
+then
+    unset HYPRE_ARCH_PATH
+fi
+
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions hypre; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [lib|libso] [HYPRE-VERSION] [-- configure-options]
+Usage: ${0##*/} [OPTION] [lib|libso] [HYPRE-VERSION] [-- configure-options]
 options:
   -force        Force compilation, even if include/library already exists
   -gcc          Force use of gcc/g++
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
-* build HYPRE with
-      ${hyprePACKAGE:-'unspecified hypre version'}
+* Build HYPRE with
+      ${PACKAGE:-[unspecified]}
 
 USAGE
-    showDownloadHint HYPRE
-    exit 1
+    showDownloadHint hypre
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler          # Compiler info for CMake/configure
@@ -65,7 +72,8 @@ do
     case "$1" in
     '') ;;      # Ignore empty
     --) break;; # Extra configure options (leave on $@ for later detection)
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
     -force)     optForce=true ;;
 
@@ -73,8 +81,9 @@ do
         targetType="$1"
         ;;
 
+    hypre/* | sources/hypre* |\
     hypre-[0-9]* | hypre-git)
-        hyprePACKAGE="${1%%/}"
+        PACKAGE="${1%%/}"
         unset HYPRE_ARCH_PATH  # Avoid inconsistency
         ;;
     *)
@@ -84,16 +93,12 @@ do
     shift
 done
 
-[ -n "$hyprePACKAGE" ] || die "The hypre-VERSION was not specified"
-
-# Nothing to build
-if _foamIsNone "$hyprePACKAGE"
+if [ -z "$PACKAGE" ]
 then
-    echo "Using hypre-none (skip ThirdParty build of HYPRE)"
-    exit 0
-elif _foamIsSystem "$hyprePACKAGE"
+    die "The HYPRE package/version not specified"
+elif _foamIsNone "$PACKAGE" || _foamIsSystem "$PACKAGE"
 then
-    echo "Using hypre-system"
+    echo "Using none/system (skip ThirdParty build of HYPRE)"
     exit 0
 fi
 
@@ -101,15 +106,23 @@ fi
 #
 # Build HYPRE
 #
-#   HYPRE_ARCH_PATH  : installation directory
-#   HYPRE_SOURCE_DIR : location of the original sources
+#   HYPRE_ARCH_PATH : installation directory (as per config file)
+#
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
 
-HYPRE_SOURCE_DIR="$sourceBASE/$hyprePACKAGE"
-: "${HYPRE_ARCH_PATH:=$installBASE$WM_SIZE_OPTIONS/$hyprePACKAGE}"
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
+PACKAGE="$(basename "$PACKAGE")"
+PKG_PREFIX="$installBASE$WM_SIZE_OPTIONS/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"
 
-[ -d "$HYPRE_SOURCE_DIR" ] || {
-    echo "Missing sources: '$hyprePACKAGE'"
-    showDownloadHint HYPRE
+# Override as per config file (if any)
+[ -n "$HYPRE_ARCH_PATH" ] && PKG_PREFIX="$HYPRE_ARCH_PATH"
+
+[ -d "$PKG_SOURCE" ] || {
+    echo "Missing sources: '$PACKAGE'"
+    showDownloadHint hypre
     exit 1
 }
 
@@ -118,7 +131,7 @@ HYPRE_SOURCE_DIR="$sourceBASE/$hyprePACKAGE"
 CC="$(whichMpicc)"
 CXX="$(whichMpicxx)"
 
-echo "Starting build: $hyprePACKAGE ($targetType)"
+echo "Starting build: $PACKAGE ($targetType)"
 echo
 (
     # Configuration options
@@ -131,25 +144,24 @@ echo
         configOpt="$configOpt $@"
     fi
 
-    cd "$HYPRE_SOURCE_DIR/src" || exit
-    export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
+    cd "$PKG_SOURCE/src" || exit
 
-    rm -rf "$HYPRE_ARCH_PATH"
-    [ -e Makefile ] && make distclean 2>/dev/null
+    rm -rf "$PKG_PREFIX"
+    make distclean 2>/dev/null || true
 
+    set -x && \
     ./configure \
-       --prefix="$HYPRE_ARCH_PATH" \
+       --prefix="$PKG_PREFIX" \
        --disable-fortran \
        --enable-shared \
        $configOpt \
     && make -j $WM_NCOMPPROCS \
     && echo "Built: hypre" \
     && make install \
-    && echo "Installed: hypre"
+    && echo "Installed: $PACKAGE"
 ) || {
-    echo "Error building: hypre"
+    echo "Error building: $PACKAGE"
     exit 1
 }
-
 
 #------------------------------------------------------------------------------
diff --git a/makeKAHIP b/makeKAHIP
--- a/makeKAHIP
+++ b/makeKAHIP
@@ -50,13 +50,15 @@ then
     exit 2
 fi
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
 . "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 # Obtain version from OpenFOAM etc/config.sh file:
@@ -69,6 +71,11 @@ targetType=libso
 if [ -d "$MPI_ARCH_PATH" ]
 then
     export MPI_HOME="$MPI_ARCH_PATH"
+fi
+
+if nonStandardPlatforms  # Possibly unreliable inherited values
+then
+    unset KAHIP_ARCH_PATH
 fi
 
 #------------------------------------------------------------------------------
@@ -134,6 +141,7 @@ do
         targetType="$1"
         ;;
 
+    kahip/* | sources/kahip* | sources/KaHIP* |\
     kahip-[0-9]* | kahip-git | KaHIP_* |  KaHIP-[0-9]*)
         PACKAGE="${1%%/}"
         unset KAHIP_ARCH_PATH  # Avoid inconsistency
@@ -184,7 +192,7 @@ fi
 #   *SOURCE  : location of original sources
 #   *PREFIX  : installation directory
 
-PKG_SOURCE="$sourceBASE/$PACKAGE"
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
 PACKAGE="$(basename "$PACKAGE")"
 # Future:  PKG_PREFIX="$installBASE$WM_SIZE_OPTIONS/$PACKAGE"
 PKG_PREFIX="$installBASE/$PACKAGE"
@@ -395,7 +403,6 @@ install_wmake()
     return 0
 }
 
-
 if [ "${useWmakeWorkaround:-false}" = false ]
 then
 (
@@ -418,13 +425,15 @@ then
 
     cmake=$(findCMake)
 
-    cd "$PKG_BUILD" && $cmake \
+    cd "$PKG_BUILD" && set -x && \
+    ${cmake:?} \
         -B "$PKG_BUILD" \
         -S "$PKG_SOURCE" \
         -DCMAKE_INSTALL_PREFIX="$PKG_PREFIX" \
         -DCMAKE_BUILD_TYPE=Release \
         $buildOpt \
         ${WM_QUIET:+-DCMAKE_RULE_MESSAGES=OFF} \
+     && set +x \
      && make -j $WM_NCOMPPROCS \
      && make install \
      && install \
@@ -458,7 +467,7 @@ then
     && echo "Built: $PACKAGE" \
     && install_wmake
 ) || {
-    echo "Error building: kahip"
+    echo "Error building: $PACKAGE"
     exit 1
 }
 fi
diff --git a/makeLLVM b/makeLLVM
--- a/makeLLVM
+++ b/makeLLVM
@@ -7,7 +7,7 @@
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 #     Copyright (C) 2011-2016 OpenFOAM Foundation
-#     Copyright (C) 2016-2020 OpenCFD Ltd.
+#     Copyright (C) 2016-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -39,14 +39,16 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 
 [ "${WM_COMPILER#Clang}" = "$WM_COMPILER" ] && WM_COMPILER=Clang  # Force clang
@@ -55,26 +57,26 @@ WM_COMPILER_TYPE=ThirdParty                # Ensure we get the correct settings
 # LLVM/Clang version from OpenFOAM etc/config.sh file:
 _foamConfig compiler
 
-llvmPACKAGE=$clang_version
+PACKAGE="$clang_version"
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions llvm; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [llvm-VERSION]
+Usage: ${0##*/} [OPTION] [llvm-VERSION]
 options:
   -gcc          Force use of gcc/g++
   -cmake PATH   with cmake from the given path
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
-* build llvm/clang
-      ${llvmPACKAGE:-'unspecified LLVM version'}
+* Build llvm/clang
+      ${PACKAGE:-[unspecified]}
 
 USAGE
-    showDownloadHint LLVM
-    exit 1
+    showDownloadHint llvm
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler          # Compiler info for CMake/configure
@@ -84,7 +86,8 @@ while [ "$#" -gt 0 ]
 do
     case "$1" in
     '') ;;      # Ignore empty
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
 
     -cmake)
@@ -92,11 +95,13 @@ do
         CMAKE_PATH="${2%%/}"
         shift
         ;;
+
+    llvm/* | sources/llvm* |\
     llvm-[0-9]* | llvm-svn*)
-        llvmPACKAGE="${1%%/}"
+        PACKAGE="${1%%/}"
         ;;
     [0-9]*)
-        llvmPACKAGE="llvm-${1%%/}"
+        PACKAGE="llvm-${1%%/}"
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -105,97 +110,97 @@ do
     shift
 done
 
-[ -n "$llvmPACKAGE" ] || die "The llvm-VERSION was not specified"
+if [ -z "$PACKAGE" ]
+then
+    die "The LLVM package/version not specified"
+fi
 
 #------------------------------------------------------------------------------
-# Build/install locations without a compiler name
-buildBASE=$WM_THIRD_PARTY_DIR/build/$WM_ARCH$WM_COMPILER_ARCH
-installBASE=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH
+# !Build/install locations with arch name only (NO compiler name)!
+buildBASE="$(dirname "$buildBASE")/$WM_ARCH$WM_COMPILER_ARCH"
+installBASE="$(dirname "$installBASE")/$WM_ARCH$WM_COMPILER_ARCH"
 
 # Build LLVM (clang)
-#   LLVM_SOURCE_DIR : location of the original sources
-#   LLVM_BUILD_DIR  : location of the build
-#   LLVM_ARCH_PATH  : location of the installed program
-# - Strip any trailing '.src' from the proper names
+#   *PACKAGE   : name-version of the package
+#   *SOURCEDIR : location of original sources
+#   *PREFIXDIR : installation directory
+# Note: strip trailing '.src' from package name
 
-LLVM_SOURCE_DIR=$sourceBASE/$llvmPACKAGE
-LLVM_BUILD_DIR=$buildBASE/${llvmPACKAGE%%.src}
-LLVM_ARCH_PATH=$installBASE/${llvmPACKAGE%%.src}
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
+PACKAGE="$(basename "$PACKAGE" .src)"   # Strip of trailing .src
+PKG_PREFIX="$installBASE/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"    # Avoid seeing our own git-repo
 
-#
-# Build LLVM
-#
+
+# Building...
 echo "---------------"
-if [ -d $LLVM_ARCH_PATH ]
+if [ -d "$PKG_PREFIX" ]
 then
-    echo "Already built: $llvmPACKAGE"
-elif [ -z "$CMAKE_PATH" ] && $LLVM_SOURCE_DIR/configure -help >/dev/null 2>&1
+    echo "Already built: $PACKAGE"
+elif [ -z "$CMAKE_PATH" ] && "$PKG_SOURCE"/configure -help >/dev/null 2>&1
 then
     # configure can be used prior to 3.9.0
     # but use cmake if someone explicitly mentioned -cmake on the command-line
 
-    echo "Starting build: $llvmPACKAGE (using configure)"
+    echo "Starting build: $PACKAGE (using configure)"
     echo
     (
-        cd "$LLVM_SOURCE_DIR" || exit
-        export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-        make distclean 2>/dev/null
+        PKG_BUILD="$buildBASE/$PACKAGE"
+        cd "$PKG_SOURCE" || exit
+        make distclean 2>/dev/null || true
 
-        rm -rf $LLVM_BUILD_DIR
-        mkdir -p $LLVM_BUILD_DIR
-        cd $LLVM_BUILD_DIR
+        rm -rf "$PKG_BUILD"
+        mkdir -p "$PKG_BUILD"
 
-        set -x
-        $LLVM_SOURCE_DIR/configure \
-            --prefix=$LLVM_ARCH_PATH \
+        cd "$PKG_BUILD" && set -x && \
+        "$PKG_SOURCE"/configure \
+            --prefix="$PKG_PREFIX" \
             --with-gcc-toolchain="$(command -v gcc | sed 's%/bin/gcc%%')" \
             --enable-optimized \
             --enable-shared \
         && set +x \
         && make -j $WM_NCOMPPROCS \
         && make install \
-        && echo "Built: $llvmPACKAGE"
+        && echo "Built: $PACKAGE"
     ) || {
-        echo "Error building: $llvmPACKAGE"
+        echo "Error building: $PACKAGE"
         exit 1
     }
 
 else
     # CMake used with 3.9.0 and later
 
-    echo "Starting build: $llvmPACKAGE (using cmake)"
+    echo "Starting build: $PACKAGE (using cmake)"
     echo
     (
+        PKG_BUILD="$buildBASE/$PACKAGE"
+        cd "$PKG_SOURCE" || exit
+
         # Configuration options:
         unset configOpt
-
-        cd "$LLVM_SOURCE_DIR" || exit
-        export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-
         if [ -f tools/openmp/CMakeLists.txt ]
         then
             configOpt="$configOpt -DLLVM_TOOL_OPENMP_BUILD=ON"
         fi
 
-        rm -rf $LLVM_BUILD_DIR
-        mkdir -p $LLVM_BUILD_DIR
-        cd $LLVM_BUILD_DIR
+        rm -rf "$PKG_BUILD"
+        mkdir -p "$PKG_BUILD"
 
         cmake=$(findCMake)
 
-        set -x
-        $cmake \
-            -DCMAKE_INSTALL_PREFIX=$LLVM_ARCH_PATH \
+        cd "$PKG_BUILD" && set -x && \
+        ${cmake:?} \
+            -DCMAKE_INSTALL_PREFIX="$PKG_PREFIX" \
             -DCMAKE_BUILD_TYPE=Release \
             -DBUILD_SHARED_LIBS=ON \
             $configOpt \
-            $LLVM_SOURCE_DIR \
+            "$PKG_SOURCE" \
         && set +x \
         && make -j $WM_NCOMPPROCS \
         && make install \
-        && echo "Built: $llvmPACKAGE"
+        && echo "Built: $PACKAGE"
     ) || {
-        echo "Error building: $llvmPACKAGE"
+        echo "Error building: $PACKAGE"
         exit 1
     }
 
diff --git a/makeMETIS b/makeMETIS
--- a/makeMETIS
+++ b/makeMETIS
@@ -50,13 +50,15 @@ then
     exit 2
 fi
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
 . "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 # Obtain version from OpenFOAM etc/config.sh file:
@@ -64,6 +66,11 @@ _foamConfig metis
 
 PACKAGE="${METIS_VERSION:-system}"
 targetType=libso
+
+if nonStandardPlatforms  # Possibly unreliable inherited values
+then
+    unset METIS_ARCH_PATH
+fi
 
 #------------------------------------------------------------------------------
 printVersions() { listPackageVersions metis; exit 0; }
@@ -114,6 +121,7 @@ do
         targetType="$1"
         ;;
 
+    metis/* | sources/metis* | \
     metis-[0-9]*)
         PACKAGE="${1%%/}"
         unset METIS_ARCH_PATH  # Avoid inconsistency
@@ -161,7 +169,7 @@ fi
 #   *SOURCE  : location of original sources
 #   *PREFIX  : installation directory
 
-PKG_SOURCE="$sourceBASE/$PACKAGE"
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
 PACKAGE="$(basename "$PACKAGE")"
 PKG_PREFIX="$installBASE$WM_SIZE_OPTIONS/$PACKAGE"
 export GIT_DIR="$PKG_SOURCE/.git"
diff --git a/makeMGridGen b/makeMGridGen
--- a/makeMGridGen
+++ b/makeMGridGen
@@ -6,7 +6,7 @@
 #   \\  /    A nd           | www.openfoam.com
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
-#     Copyright (C) 2017-2020 OpenCFD Ltd.
+#     Copyright (C) 2017-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -20,40 +20,40 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from ThirdParty directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
-    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
-    echo "    The environment variables are inconsistent with the installation."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
-
-# mgridgen version from OpenFOAM etc/config.sh file:
+# Obtain version from OpenFOAM etc/config.sh file:
 _foamConfig mgridgen
 
-mgridgenPACKAGE=${MGRIDGEN_VERSION:-mgridgen-none}
+PACKAGE="${MGRIDGEN_VERSION:-none}"
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions mgridgen parmgridgen; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [mgridgen-VERSION]
+Usage: ${0##*/} [OPTION] [mgridgen-VERSION]
 options:
   -force        Force compilation, even if include/library already exists
   -gcc          Force use of gcc/g++
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
-* Build MGridGen
-      $mgridgenPACKAGE
+* Build MGridGen with
+      ${PACKAGE:-[unspecified]}
 
 USAGE
-    # showDownloadHint GRIDGEN
-    exit 1
+    # showDownloadHint gridgen
+    exit 0   # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler          # Compiler info for CMake/configure
@@ -65,12 +65,15 @@ while [ "$#" -gt 0 ]
 do
     case "$1" in
     '') ;;      # Ignore empty
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
     -force)     optForce=true ;;
 
-    mgridgen-[0-9]* | MGridGen-[0-9]* | parmgridgen-[0-9]* | ParMGridGen-[0-9]*)
-        mgridgenPACKAGE="${1%%/}"
+    mgridgen/* | sources/*gridgen* | sources/*GridGen* | \
+    mgridgen-[0-9]* | MGridGen-[0-9]* | \
+    parmgridgen-[0-9]* | ParMGridGen-[0-9]*)
+        PACKAGE="${1%%/}"
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -79,34 +82,32 @@ do
     shift
 done
 
-[ -n "$mgridgenPACKAGE" ] || die "The mgridgen-VERSION was not specified"
-
-# Nothing to build
-if _foamIsNone "$mgridgenPACKAGE"
+if [ -z "$PACKAGE" ]
 then
-    echo "Using mgridgen-none (skip ThirdParty build of MGridGen)"
-    exit 0
-elif _foamIsSystem "$mgridgenPACKAGE"
+    die "The MGRIDGEN package/version not specified"
+elif _foamIsNone "$PACKAGE" || _foamIsSystem "$PACKAGE"
 then
-    echo "Using mgridgen-system"
+    echo "Using none/system (skip ThirdParty build of MGRIDGEN)"
     exit 0
 fi
 
 #------------------------------------------------------------------------------
 #
 # Build MGridGen
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
 
-#   MGRIDGEN_SOURCE_DIR : location of the original sources
-#   MGRIDGEN_ARCH_PATH  : installation directory
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
+PACKAGE="$(basename "$PACKAGE")"
+PKG_PREFIX="$installBASE$WM_SIZE_OPTIONS/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"
 
-MGRIDGEN_SOURCE_DIR=$WM_THIRD_PARTY_DIR/$mgridgenPACKAGE
-MGRIDGEN_ARCH_PATH="$installBASE$WM_SIZE_OPTIONS/$mgridgenPACKAGE"
-
-: ${FOAM_MPI:=dummy}
+: "${FOAM_MPI:=dummy}"
 
 echo
 echo ========================================
-echo "Build mgridgen library $mgridgenPACKAGE"
+echo "Build mgridgen library $PACKAGE"
 echo
 
 #
@@ -114,23 +115,23 @@ echo
 #
 install()
 {
-    echo "Install into $MGRIDGEN_ARCH_PATH"
+    echo "Install into $PKG_PREFIX"
 
-    local bindir=$MGRIDGEN_ARCH_PATH/bin
-    local incdir=$MGRIDGEN_ARCH_PATH/include
-    local libdir=$MGRIDGEN_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH
+    local bindir="$PKG_PREFIX"/bin
+    local incdir="$PKG_PREFIX"/include
+    local libdir="$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH"
 
-    for dir in $MGRIDGEN_ARCH_PATH $bindir $incdir $libdir
+    for dir in "$PKG_PREFIX" "$bindir" "$incdir" "$libdir"
     do
-        mkdir -m 0755 -p $dir
+        mkdir -m 0755 -p "$dir"
     done
 
-    cp -vf mgridgen.h   $incdir
-    cp -vf libmgrid.a   $libdir
-    cp -vf mgridgen     $bindir
+    cp -vf mgridgen.h   "$incdir"
+    cp -vf libmgrid.a   "$libdir"
+    cp -vf mgridgen     "$bindir"
 
-    chmod -R 0644 $incdir/* $libdir/*
-    chmod -R 0755 $bindir/*
+    chmod -R 0644 "$incdir"/* "$libdir"/*
+    chmod -R 0755 "$bindir"/*
 }
 
 
@@ -138,20 +139,20 @@ install()
 # - for shared library
 # - for mpi-specific library locations
 if [ -z "$optForce" ] \
-&& [ -f "$MGRIDGEN_ARCH_PATH/include/mgridgen.h" ] \
+&& [ -f "$PKG_PREFIX/include/mgridgen.h" ] \
 && {
-     [ -r "$MGRIDGEN_ARCH_PATH/lib/libmgrid.a" ] \
-  || [ -r "$MGRIDGEN_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH/libmgrid.a" ]
+     [ -r "$PKG_PREFIX/lib/libmgrid.a" ] \
+  || [ -r "$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH/libmgrid.a" ]
 }
 then
-    echo "    MGridGen already built : $MGRIDGEN_ARCH_PATH"
+    echo "    MGridGen already built : $PKG_PREFIX"
 else
 (
-    cd "$MGRIDGEN_SOURCE_DIR" || exit
+    cd "$PKG_SOURCE" || exit
     [ -e Makefile ] && make realclean 2>/dev/null
 
     # Remove any existing build folder and recreate
-    rm -rf $MGRIDGEN_ARCH_PATH
+    rm -rf "$PKG_PREFIX"
 
     serial="$(whichCC)"             # CC (serial compiler) default=gcc
     # parallel=$(whichMpicc)        # PARCC (parallel compiler) default=mpicc
@@ -169,9 +170,9 @@ else
         make=make \
         serial \
     && install \
-    && echo "Built: $mgridgenPACKAGE"
+    && echo "Built: $PACKAGE"
 ) || {
-    echo "Error building: $mgridgenPACKAGE"
+    echo "Error building: $PACKAGE"
     exit 1
 }
 fi
diff --git a/makeMPICH b/makeMPICH
--- a/makeMPICH
+++ b/makeMPICH
@@ -6,7 +6,7 @@
 #   \\  /    A nd           | www.openfoam.com
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
-#     Copyright (C) 2017-2020 OpenCFD Ltd.
+#     Copyright (C) 2017-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -48,46 +48,45 @@ then
     exit 2
 fi
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 # Transition
-# ~~~~~~~~~~
 _foamAddLib()  { true; }
 _foamAddMan()  { true; }
 _foamAddPath() { true; }
 #------------------------------------------------------------------------------
-
-WM_MPLIB=MPICH                                  # Ensure we get the correct MPI
-
-# mpich version from OpenFOAM etc/config.sh file:
+# Obtain version from OpenFOAM etc/config.sh file:
+WM_MPLIB=MPICH      # Ensure we get the correct MPI
 _foamConfig mpi
 
-mpiPACKAGE=${FOAM_MPI:-mpich-system}
+PACKAGE="${FOAM_MPI:-system}"
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions mpich; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [mpich-VERSION] [-- configure-options]
+Usage: ${0##*/} [OPTION] [mpich-VERSION] [-- configure-options]
 options:
   -force        Force compilation, even if include/library already exists
   -gcc          Force use of gcc/g++
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
 * build mpich with
-      ${mpiPACKAGE:-'unspecified mpich version'}
+      ${PACKAGE:-[unspecified]}
 
 USAGE
-    showDownloadHint MPICH
-    exit 1
+    showDownloadHint mpich
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler          # Compiler info for CMake/configure
@@ -100,12 +99,14 @@ do
     case "$1" in
     '') ;;      # Ignore empty
     --) break;; # Extra configure options (leave on $@ for later detection)
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
     -force)     optForce=true ;;
 
+    mpich/* | sources/mpich* | \
     mpich*)
-        mpiPACKAGE="${1%%/}"
+        PACKAGE="${1%%/}"
         ;;
 
     *)
@@ -115,45 +116,43 @@ do
     shift
 done
 
-[ -n "$mpiPACKAGE" ] || die "The mpich-VERSION was not specified"
-
-# Nothing to build
-if _foamIsNone "$mpiPACKAGE"
+if [ -z "$PACKAGE" ]
 then
-    echo "Using mpich-none (skip ThirdParty build of mpich)"
-    exit 0
-elif _foamIsSystem "$mpiPACKAGE"
+    die "The MPICH package/version not specified"
+elif _foamIsNone "$PACKAGE" || _foamIsSystem "$PACKAGE"
 then
-    echo "Using mpich-system (skip ThirdParty build of mpich)"
+    echo "Using none/system (skip ThirdParty build of MPICH)"
     exit 0
 fi
 
 #------------------------------------------------------------------------------
 #
-# Build mpich
-#
-#   MPI_SOURCE_DIR : location of the original sources
-#   MPI_ARCH_PATH  : installation directory
+# Build MPICH
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
 
-MPI_SOURCE_DIR=$sourceBASE/$mpiPACKAGE
-MPI_ARCH_PATH=$installBASE/$mpiPACKAGE
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
+PACKAGE="$(basename "$PACKAGE")"
+PKG_PREFIX="$installBASE/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"
 
 if [ -z "$optForce" ] \
 && {
-     [ -r "$MPI_ARCH_PATH/lib/libmpi$EXT_SO" ] \
-  || [ -r "$MPI_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH/libmpi$EXT_SO" ]
+     [ -r "$PKG_PREFIX/lib/libmpi$EXT_SO" ] \
+  || [ -r "$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH/libmpi$EXT_SO" ]
 }
 then
-    echo "Already has shared library: $MPI_ARCH_PATH"
+    echo "Already has shared library: $PKG_PREFIX"
 elif [ -z "$optForce" ] \
 && {
-     [ -r "$MPI_ARCH_PATH/lib/libmpi.a" ] \
-  || [ -r "$MPI_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH/libmpi.a" ]
+     [ -r "$PKG_PREFIX/lib/libmpi.a" ] \
+  || [ -r "$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH/libmpi.a" ]
 }
 then
-    echo "Already has static library: $MPI_ARCH_PATH"
+    echo "Already has static library: $PKG_PREFIX"
 else
-    echo "Starting build: $WM_MPLIB ($mpiPACKAGE)"
+    echo "Starting build: $WM_MPLIB ($PACKAGE)"
     echo
 
     (
@@ -170,33 +169,32 @@ else
         # End of configuration options
         # ----------------------------
 
-        buildDIR=$buildBASE/$mpiPACKAGE
+        PKG_BUILD="$buildBASE/$PACKAGE"
 
-        cd "$MPI_SOURCE_DIR" || exit
-        export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-        [ -e Makefile ] && make distclean 2>/dev/null
+        cd "$PKG_SOURCE" || exit
+        make distclean 2>/dev/null || true
 
-        rm -rf $MPI_ARCH_PATH
-        rm -rf $buildDIR
-        mkdir -p $buildDIR
-        cd $buildDIR
+        rm -rf "$PKG_PREFIX"
+        rm -rf "$PKG_BUILD"
+        mkdir -p "$PKG_BUILD"
 
-        set -x
-        $MPI_SOURCE_DIR/configure \
-            --prefix=$MPI_ARCH_PATH \
+        cd "$PKG_BUILD" && set -x && \
+        "$PKG_SOURCE"/configure \
+            --prefix="$PKG_PREFIX" \
+            --libdir="$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH" \
             --disable-fortran --disable-g \
-            --libdir=$MPI_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH \
             --enable-shared --disable-static \
             $configOpt \
         && set +x \
         && make -j $WM_NCOMPPROCS \
         && make install \
-        && echo "Built: $mpiPACKAGE" \
-        && pkgconfigAdjust $MPI_ARCH_PATH
+        && echo "Built: $PACKAGE" \
+        && pkgconfigAdjust "$PKG_PREFIX"
     ) || {
-        echo "Error building: $mpiPACKAGE"
+        echo "Error building: $PACKAGE"
         exit 1
     }
+
 fi
 
 #------------------------------------------------------------------------------
diff --git a/makeMesa b/makeMesa
--- a/makeMesa
+++ b/makeMesa
@@ -15,7 +15,7 @@
 #     makeMesa
 #
 # Description
-#     Build script for Mesa
+#     Build script for MESA
 #
 # Note
 #     Building with mesa-12.x.x fails to create an include/GL directory and
@@ -34,41 +34,41 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
-
-unset vtk_version mesa_version mesa_llvm              # Purge current values
-
-# mesa version from OpenFOAM etc/config.sh file:
+# Obtain version from OpenFOAM etc/config.sh file:
+unset vtk_version mesa_version mesa_llvm    # Purge current values
 _foamConfig vtk
 
-mesaPACKAGE=$mesa_version
+PACKAGE="$mesa_version"
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions mesa; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] mesa-VERSION [-- configure-options]
+Usage: ${0##*/} [OPTION] mesa-VERSION [-- configure-options]
 options:
   -gcc          Force use of gcc/g++
   -llvm VER     llvm version (in ThirdParty) or 'system' to use system
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
-* build Mesa with
-      ${mesaPACKAGE:-'unspecified MESA version'}
+* build MESA with
+      ${PACKAGE:-[unspecified]}
 
 USAGE
-    showDownloadHint MESA
-    exit 1
+    showDownloadHint mesa
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler          # Compiler info for CMake/configure
@@ -101,7 +101,8 @@ do
     case "$1" in
     '') ;;      # Ignore empty
     --) break;; # Extra configure options (leave on $@ for later detection)
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)
         useGcc
         unset withLLVM
@@ -114,8 +115,10 @@ do
     llvm-*)
         withLLVM="$1"
         ;;
+
+    mesa/* | sources/mesa* |\
     mesa-*)
-        mesaPACKAGE="${1%%/}"
+        PACKAGE="${1%%/}"
         ;;
     *)
         die "unknown option/argument: '$1'"
@@ -124,16 +127,12 @@ do
     shift
 done
 
-[ -n "$mesaPACKAGE" ] || die "The mesa-VERSION was not specified"
-
-# Nothing to build
-if _foamIsNone "$mesaPACKAGE"
+if [ -z "$PACKAGE" ]
 then
-    echo "Using mesa-none (skip ThirdParty build of MESA)"
-    exit 0
-elif _foamIsSystem "$mesaPACKAGE"
+    die "The MESA package/version not specified"
+elif _foamIsNone "$PACKAGE" || _foamIsSystem "$PACKAGE"
 then
-    echo "Using mesa-system (skip ThirdParty build of MESA)"
+    echo "Using none/system (skip ThirdParty build of MESA)"
     exit 0
 fi
 
@@ -142,7 +141,7 @@ fi
 case "$withLLVM" in
 ('' | none | false)
     withLLVM=none
-    echo "No llvm"
+    echo "Without llvm"
     ;;
 
 (true | system)
@@ -182,29 +181,32 @@ esac
 #------------------------------------------------------------------------------
 #
 # Build MESA
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
+#
 # For 64-bit
 # - MESA itself will normally build into 'lib64' (depends on autoconfig).
-#
-#   MESA_SOURCE_DIR : location of the original sources
-#   MESA_ARCH_DIR   : installation directory
 
-MESA_SOURCE_DIR="$sourceBASE/$mesaPACKAGE"
-MESA_ARCH_PATH="$installBASE/$mesaPACKAGE"
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
+PACKAGE="$(basename "$PACKAGE")"
+PKG_PREFIX="$installBASE/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"
 
-#
+
 # Manual adjustments to mesa
 # - avoid GLES (GLES1) since <GLES/gl.h> may mask the <GL/gl.h> header
 adjustMESA()
 {
-    pkgconfigAdjust "$MESA_ARCH_PATH"
+    pkgconfigAdjust "$PKG_PREFIX"
 
-    \rm -rf "$MESA_ARCH_PATH"/include/GLES "$MESA_ARCH_PATH"/include/GLES1
+    rm -rf "$PKG_PREFIX"/include/GLES "$PKG_PREFIX"/include/GLES1
     echo "removed all gles1 includes"
 }
 
 # Old MESA with autoconfig
 
-if [ -e "$MESA_SOURCE_DIR"/configure ]
+if [ -e "$PKG_SOURCE"/configure ]
 then
 (
     # Configuration options:
@@ -230,21 +232,14 @@ then
 
     # End of configuration options
     # ----------------------------
-    buildDIR="$buildBASE/$mesaPACKAGE"
+    PKG_BUILD="$buildBASE/$PACKAGE"
 
-    cd "$MESA_SOURCE_DIR" || exit
-    export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-
-    # Remove any existing build
-    rm -rf "$MESA_ARCH_PATH"
-    rm -rf "$buildDIR"
-    mkdir -p "$buildDIR"
-    cd "$buildDIR"
+    cd "$PKG_SOURCE" || exit
 
     echo "----"
-    echo "Building $mesaPACKAGE"
-    echo "    Source  : $MESA_SOURCE_DIR"
-    echo "    Target  : $MESA_ARCH_PATH"
+    echo "Building $PACKAGE (with autoconf)"
+    echo "    Source  : $PKG_SOURCE"
+    echo "    Target  : $PKG_PREFIX"
     if [ -d "$LLVM_ARCH_PATH" ]
     then
         echo "    llvm    : $LLVM_ARCH_PATH"
@@ -258,9 +253,14 @@ then
     fi
 
     ## autoreconf -fi
-    set -x
-    $MESA_SOURCE_DIR/configure \
-        --prefix="$MESA_ARCH_PATH" \
+
+    rm -rf "$PKG_PREFIX"
+    rm -rf "$PKG_BUILD"
+    mkdir -p "$PKG_BUILD"
+
+    cd "$PKG_BUILD" && set -x && \
+    "$PKG_SOURCE"/configure \
+        --prefix="$PKG_PREFIX" \
         --disable-xvmc \
         --disable-glx \
         --disable-dri \
@@ -273,14 +273,14 @@ then
     && set +x \
     && make -j $WM_NCOMPPROCS \
     && make install \
-    && echo "Built $mesaPACKAGE" \
+    && echo "Built $PACKAGE" \
     && adjustMESA
 ) || {
     echo "Error building: MESA"
     exit 1
 }
 
-elif [ -e "$MESA_SOURCE_DIR"/meson.build ]
+elif [ -e "$PKG_SOURCE"/meson.build ]
 then
 (
     # Configuration options:
@@ -301,21 +301,13 @@ then
 
     # End of configuration options
     # ----------------------------
-    buildDIR="$buildBASE/$mesaPACKAGE"
-
-    cd "$MESA_SOURCE_DIR" || exit
-    export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
-
-    # Remove any existing build
-    rm -rf $MESA_ARCH_PATH
-    rm -rf $buildDIR
-    mkdir -p $buildDIR
-    cd $MESA_SOURCE_DIR
+    PKG_BUILD="$buildBASE/$PACKAGE"
+    cd "$PKG_SOURCE" || exit
 
     echo "----"
-    echo "Building $mesaPACKAGE"
-    echo "    Source  : $MESA_SOURCE_DIR"
-    echo "    Target  : $MESA_ARCH_PATH"
+    echo "Building $PACKAGE (with meson)"
+    echo "    Source  : $PKG_SOURCE"
+    echo "    Target  : $PKG_PREFIX"
     if [ -d "$LLVM_ARCH_PATH" ]
     then
         echo "    llvm    : $LLVM_ARCH_PATH"
@@ -331,9 +323,13 @@ then
     # Needs c++14 not c++11
     CXXFLAGS="$(echo "$CXXFLAGS" | sed 's/c++11/c++14/')"
 
-    set -x
-    meson "$buildDIR" \
-        --prefix="$MESA_ARCH_PATH" \
+    rm -rf "$PKG_PREFIX"
+    rm -rf "$PKG_BUILD"
+    mkdir -p "$PKG_BUILD"
+
+    cd "$PKG_SOURCE" && set -x && \
+    meson "$PKG_BUILD" \
+        --prefix="$PKG_PREFIX" \
         -Dplatforms=x11 \
         -Dosmesa=gallium \
         -Dgallium-drivers=swrast \
@@ -341,9 +337,9 @@ then
         -Dvulkan-drivers=[] \
         $configOpt \
     && set +x \
-    && ninja -j $WM_NCOMPPROCS -C "$buildDIR" \
-    && ninja -C "$buildDIR" install \
-    && echo "Built $mesaPACKAGE" \
+    && ninja -j $WM_NCOMPPROCS -C "$PKG_BUILD" \
+    && ninja -C "$PKG_BUILD" install \
+    && echo "Built $PACKAGE" \
     && adjustMESA
 ) || {
     echo "Error building: MESA"
diff --git a/makePETSC b/makePETSC
--- a/makePETSC
+++ b/makePETSC
@@ -20,31 +20,36 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 _foamConfig petsc
 
-petscPACKAGE="${petsc_version:-petsc-system}"
+PETSC_PACKAGE="${petsc_version:-none}"
 targetType=libso
 
-unset hyprePACKAGE
+unset HYPRE_PACKAGE
 unset HYPRE_ARCH_PATH   # Avoid inconsistency
 
+if nonStandardPlatforms  # Possibly unreliable inherited values
+then
+    unset PETSC_ARCH_PATH
+fi
+
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions petsc; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [lib|libso] [HYPRE-VERSION] [PETSC-VERSION] [-- configure-options]
+Usage: ${0##*/} [OPTION] [lib|libso] [HYPRE-VERSION] [PETSC-VERSION] [-- configure-options]
 options:
   -force        Force compilation, even if include/library already exists
   -gcc          Force use of gcc/g++
@@ -52,19 +57,20 @@ options:
   -debug        Build with debugging enabled
   -hypre=URL    Specify hypre download location
   -no-hypre     Disable automatic hypre download/detection
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
 * build PETSC with
-      ${petscPACKAGE:-'unspecified petsc version'}
+      ${PACKAGE:-[unspecified]}
 
 USAGE
-    showDownloadHint PETSC
+    showDownloadHint petsc
 
     echo
     echo "Many people who have downloaded PETSC have also downloaded HYPRE :"
-    showDownloadHint HYPRE
+    showDownloadHint hypre
 
-    exit 1
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler          # Compiler info for CMake/configure
@@ -77,7 +83,8 @@ do
     case "$1" in
     '') ;;      # Ignore empty
     --) break;; # Extra configure options (leave on $@ for later detection)
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
     -force)     optForce=true ;;
     -inplace)   optInplace=true ;;
@@ -87,21 +94,23 @@ do
 
     -hypre=*)
         optHypre="${1#*=}"      # URL for download
-        unset hyprePACKAGE HYPRE_ARCH_PATH
+        unset HYPRE_PACKAGE HYPRE_ARCH_PATH
         ;;
 
     -no-hypre)
         optHypre=false
-        unset hyprePACKAGE HYPRE_ARCH_PATH
+        unset HYPRE_PACKAGE HYPRE_ARCH_PATH
         ;;
 
     hypre-[0-9]* | hypre-git)
-        hyprePACKAGE="${1%%/}"
+        HYPRE_PACKAGE="${1%%/}"
         unset optHypre
         unset HYPRE_ARCH_PATH   # Avoid inconsistency
         ;;
+
+    petsc/* | sources/petsc* |\
     petsc-[0-9]* | petsc-git)
-        petscPACKAGE="${1%%/}"
+        PETSC_PACKAGE="${1%%/}"
         unset PETSC_ARCH_PATH   # Avoid inconsistency
         ;;
     *)
@@ -111,16 +120,12 @@ do
     shift
 done
 
-[ -n "$petscPACKAGE" ] || die "The petsc-VERSION was not specified"
-
-# Nothing to build
-if _foamIsNone "$petscPACKAGE"
+if [ -z "$PETSC_PACKAGE" ]
 then
-    echo "Using petsc-none (skip ThirdParty build of PETSC)"
-    exit 0
-elif _foamIsSystem "$petscPACKAGE"
+    die "The PETSC package/version not specified"
+elif _foamIsNone "$PETSC_PACKAGE" || _foamIsSystem "$PETSC_PACKAGE"
 then
-    echo "Using petsc-system"
+    echo "Using none/system (skip ThirdParty build of PETSC)"
     exit 0
 fi
 
@@ -128,11 +133,11 @@ fi
 # Integrations
 
 # Clunky
-if [ -z "$optHypre" ] && [ -n "$hyprePACKAGE" ] \
-&& ! _foamIsNone "$hyprePACKAGE"
+if [ -z "$optHypre" ] && [ -n "$HYPRE_PACKAGE" ] \
+&& ! _foamIsNone "$HYPRE_PACKAGE"
 then
-    echo "Using $hyprePACKAGE"
-    : "${HYPRE_ARCH_PATH:=$installBASE$WM_SIZE_OPTIONS/$hyprePACKAGE}"
+    echo "Using $HYPRE_PACKAGE"
+    : "${HYPRE_ARCH_PATH:=$installBASE$WM_SIZE_OPTIONS/$HYPRE_PACKAGE}"
 fi
 
 
@@ -140,15 +145,22 @@ fi
 #
 # Build PETSC
 #
-#   PETSC_ARCH_PATH  : installation directory
-#   PETSC_SOURCE_DIR : location of the original sources
+#   PETSC_ARCH_PATH : installation directory (as per config file)
+#
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
 
-PETSC_SOURCE_DIR="$sourceBASE/$petscPACKAGE"
-: "${PETSC_ARCH_PATH:=$installBASE$WM_SIZE_OPTIONS/$petscPACKAGE}"
+PETSC_SOURCE="$(findSourceDir "$PETSC_PACKAGE")"
+PETSC_PACKAGE="$(basename "$PETSC_PACKAGE")"
+PETSC_PREFIX="$installBASE$WM_SIZE_OPTIONS/$PETSC_PACKAGE"
 
-[ -d "$PETSC_SOURCE_DIR" ] || {
-    echo "Missing sources: '$petscPACKAGE'"
-    showDownloadHint PETSC
+# Override as per config file (if any)
+[ -n "$PETSC_ARCH_PATH" ] && PETSC_PREFIX="$PETSC_ARCH_PATH"
+
+[ -d "$PETSC_SOURCE" ] || {
+    echo "Missing sources: '$PETSC_PACKAGE'"
+    showDownloadHint petsc
     exit 2
 }
 
@@ -158,29 +170,28 @@ archOpt="$WM_SIZE_OPTIONS"
 
 if [ -n "$optInplace" ]
 then
-    unset installPrefix
-    # No install stage requires
+    # Inplace installation. No install stage required
+    unset PETSC_PREFIX
     makeInstall() { true; }
 else
-
-    # Regular installation location
-    installPrefix="$PETSC_ARCH_PATH"
+    # Regular installation location (PETSC_PREFIX)
 
     makeInstall() {
-        make PETSC_DIR="$PETSC_SOURCE_DIR" PETSC_ARCH="$archOpt" install
+        make PETSC_DIR="$PETSC_SOURCE" PETSC_ARCH="$archOpt" install
+        pkgconfigAdjust "$PETSC_PREFIX"
     }
 fi
 
-echo "Starting build: $petscPACKAGE ($targetType)"
+echo "Starting build: $PETSC_PACKAGE ($targetType)"
 if [ "$WM_PRECISION_OPTION" = SP ]
 then
     optHypre=false  # No single-precision hypre
     echo "No single-precision hypre"
 fi
-if [ -d "$PETSC_SOURCE_DIR/$archOpt/externalpackages" ]
+if [ -d "$PETSC_SOURCE/$archOpt/externalpackages" ]
 then
     echo "Removing old $archOpt/externalpackages"
-    rm -rf "$PETSC_SOURCE_DIR/$archOpt/externalpackages"
+    rm -rf "$PETSC_SOURCE/$archOpt/externalpackages"
 fi
 echo
 (
@@ -233,7 +244,7 @@ echo
         # This is a really clunky way to use ThirdParty hypre
         if [ -f "$HYPRE_ARCH_PATH/include/HYPRE.h" ]
         then
-            echo "Has installed hypre: $hyprePACKAGE"
+            echo "Has installed hypre: $HYPRE_PACKAGE"
             configOpt="$configOpt --with-hypre-dir=$HYPRE_ARCH_PATH"
         else
             configOpt="$configOpt --download-hypre"
@@ -254,17 +265,20 @@ echo
     unset CC CXX
     unset CFLAGS CXXFLAGS
 
-    cd "$PETSC_SOURCE_DIR" || exit
+    cd "$PETSC_SOURCE" || exit
     unset GIT_DIR # No special git-repo handling
 
-    rm -rf "$PETSC_ARCH_PATH"
+    if [ -n "$PETSC_PREFIX" ]
+    then
+        rm -rf "$PETSC_PREFIX"
+    fi
     # No clean here, if we have multiple arch in the same directory
 
     echo
     set -x
     ./configure \
-        ${installPrefix:+--prefix="$installPrefix"} \
-       --PETSC_DIR="$PETSC_SOURCE_DIR" \
+        ${PETSC_PREFIX:+--prefix="$PETSC_PREFIX"} \
+       --PETSC_DIR="$PETSC_SOURCE" \
        --with-petsc-arch="$archOpt" \
        --with-clanguage=C \
        --with-fc=0 \
@@ -273,12 +287,12 @@ echo
      && set +x \
      && echo "Configured: petsc" \
      && make ${WM_NCOMPPROCS:+-j $WM_NCOMPPROCS} \
-            PETSC_DIR="$PETSC_SOURCE_DIR" PETSC_ARCH="$archOpt" all \
+            PETSC_DIR="$PETSC_SOURCE" PETSC_ARCH="$archOpt" all \
      && echo "Built: petsc" \
      && makeInstall \
-     && echo "Installed: petsc - may require etc/pkgconfigPrefix to relocate"
+     && echo "Installed: $PETSC_PACKAGE"
 ) || {
-    echo "Error building: petsc"
+    echo "Error building: $PETSC_PACKAGE"
     exit 1
 }
 
diff --git a/makeParaView b/makeParaView
--- a/makeParaView
+++ b/makeParaView
@@ -26,20 +26,21 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
-. etc/tools/ParaViewFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ParaViewFunctions
 #------------------------------------------------------------------------------
 
-unset ParaView_VERSION                                   # Purge current values
-
 # ParaView_VERSION from etc/config.sh file:
+unset ParaView_VERSION                  # Purge current values
 _foamConfig paraview
 
 # Avoid any potential conflicts (especially if building from git)
@@ -71,13 +72,12 @@ then
 fi
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
+printVersions() { listPackageVersions paraview; exit 0; }
+printHelp() {
     : ${ParaView_VERSION:=none} # some dummy value for usage information
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [paraview-VERSION] [CMAKE-OPTION]
+Usage: ${0##*/} [OPTION] [paraview-VERSION] [CMAKE-OPTION]
 options:
   -gcc              Force use of gcc/g++
   -cmake PATH       with cmake from the given path
@@ -105,7 +105,8 @@ options:
   -buildType NAME   specify the build type (default: Release)
   -suffix NAME      specify a suffix to distinguish the build
   -DNAME=VALUE      add cmake variable
-  -help
+  -list             List available unpacked source versions
+  -help             Display usage help
 
 The -no-FEATURE option can be used to forcibly disable these features:
   -no-gl2 | -no-mesa | -no-mpi | -no-python | -no-qt
@@ -134,8 +135,8 @@ For example,
 Or change the \$WM_PROJECT_DIR/etc/config.sh/paraview settings.
 
 USAGE
-    showDownloadHint PARAVIEW
-    exit 1
+    showDownloadHint paraview
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler minimal  # Minimal compiler info for CMake/configure
@@ -149,11 +150,14 @@ while [ "$#" -gt 0 ]
 do
     case "$1" in
     '') ;;      # Ignore empty
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
 
-    [0-9]* | paraview-[0-9]* | ParaView-[0-9]*) # paraview version
-        setParaViewVersion "${1%%/}"
+    # paraview version
+    paraview/* | vtk/* | sources/paraview* | sources/vtk* |\
+    [0-9]* | paraview-[0-9]* | ParaView-[0-9]* | ParaView-v[0-9]*)
+        setParaViewVersion "$(basename "$1")"
         ;;
     -D[A-Z]*=* | [A-Z]*=*)  # cmake variables
         addCMakeVariable "$1"
diff --git a/makeQt b/makeQt
--- a/makeQt
+++ b/makeQt
@@ -7,7 +7,7 @@
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 #     Copyright (C) 2011 OpenFOAM Foundation
-#     Copyright (C) 2016-2020 OpenCFD Ltd.
+#     Copyright (C) 2016-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -21,37 +21,40 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
-. etc/tools/QtFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/QtFunctions
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions qt; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [qt-VERSION] [-- configure-options]
+Usage: ${0##*/} [OPTION] [qt-VERSION] [-- configure-options]
 options:
   -force        Force compilation, even if it already exists
   -gcc          Force use of gcc/g++
-  -help
+  -list         List available unpacked source versions
+  -help         Display usage help
 
 * build $qtTYPE, version ${qtVERSION:-undefined}
 
 USAGE
-    showDownloadHint QT
-    exit 1
+    showDownloadHint qt
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler true     # Compiler info + flags for CMake/configure
 
 unset optForce
+unset PACKAGE qtVERSION
 
 # Parse options
 while [ "$#" -gt 0 ]
@@ -59,14 +62,22 @@ do
     case "$1" in
     '') ;;      # Ignore empty
     --) break;; # Extra configure options (leave on $@ for later detection)
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
     -force)     optForce=true ;;
+
+    qt/* | sources/qt*)
+        # -qt-VERSION, VERSION, qt-VERSION, qt-everywhere-opensource-src-VERSION
+        PACKAGE="${1%%/}";
+        qtVERSION="$(basename "$PACKAGE" | sed 's#^.*-##')"
+        ;;
 
     -qt-[0-9]* | [0-9]* | qt-*)
         # -qt-VERSION, VERSION, qt-VERSION, qt-everywhere-opensource-src-VERSION
         qtVERSION="${1%%/}";
         qtVERSION="${qtVERSION##*-}"
+        PACKAGE="$qtTYPE-$qtVERSION"
         ;;
 
     *)
@@ -75,38 +86,41 @@ do
     esac
     shift
 done
-qtPACKAGE=$qtTYPE-$qtVERSION
 
-# Nothing to build
-if _foamIsNone "$qtPACKAGE"
+if [ -z "$PACKAGE" ]
 then
-    echo "Using qt-none (skip ThirdParty build of QT)"
-    exit 0
-elif _foamIsSystem "$qtPACKAGE"
+    die "The QT package/version not specified"
+elif _foamIsNone "$PACKAGE" || _foamIsSystem "$PACKAGE"
 then
-    echo "Using qt-system"
+    echo "Using none/system (skip ThirdParty build of QT)"
     exit 0
 fi
 
 #------------------------------------------------------------------------------
 #
 # Build QT
+#
+#   *PACKAGE : name-version of the package
+#   *SOURCE  : location of original sources
+#   *PREFIX  : installation directory
 
-QT_SOURCE_DIR=$sourceBASE/$qtPACKAGE
-QT_ARCH_PATH=$installBASE/qt-$qtVERSION
+PKG_SOURCE="$(findSourceDir "$PACKAGE" "$qtTYPE-$qtVERSION")"
+PACKAGE="qt-$qtVERSION"
+PKG_PREFIX="$installBASE/$PACKAGE"
+export GIT_DIR="$PKG_SOURCE/.git"
 
 echo
 echo ========================================
-echo "Build Qt $qtPACKAGE"
+echo "Build Qt $PACKAGE"
 echo
 
 if [ -z "$optForce" ] \
-&& [ -d "$QT_ARCH_PATH" ] \
-&& [ -r "$QT_ARCH_PATH/bin/qmake" ]
+&& [ -d "$PKG_PREFIX" ] \
+&& [ -r "$PKG_PREFIX"/bin/qmake ]
 then
-    echo "Already built: Qt-$qtVERSION"
+    echo "Already built: $PACKAGE"
 else
-    echo "Starting build: Qt-$qtVERSION"
+    echo "Starting build: $PACKAGE"
     (
         # Configuration options:
         unset configOpt
@@ -140,35 +154,34 @@ else
 
         # End of configuration options
         # ----------------------------
-        buildDIR=$buildBASE/$qtPACKAGE
+        PKG_BUILD="$buildBASE/$PACKAGE"
 
-        cd "$QT_SOURCE_DIR" || exit
-        export GIT_DIR="$PWD/.git" # Mask seeing our own git-repo
+        cd "$PKG_SOURCE" || exit
         [ -e Makefile ] && make distclean 2>/dev/null
 
         # Remove any existing build folder and recreate
-        rm -rf $QT_ARCH_DIR
-        rm -rf $buildDIR 2>/dev/null
-        mkdir -p $buildDIR
+        rm -rf "$PKG_PREFIX"
+        rm -rf "$PKG_BUILD"
+        mkdir -p "$PKG_BUILD"
 
         # Remove any remnants from a previous shadow build
-        rm -f "$QT_SOURCE_DIR/.qmake.cache" 2>/dev/null
-        rm -f "$QT_SOURCE_DIR/src/corelib/global/qconfig.h" 2>/dev/null
-        rm -f "$QT_SOURCE_DIR/src/corelib/global/qconfig.cpp" 2>/dev/null
+        rm -f "$PKG_SOURCE"/.qmake.cache
+        rm -f "$PKG_SOURCE"/src/corelib/global/qconfig.h
+        rm -f "$PKG_SOURCE"/src/corelib/global/qconfig.cpp
 
-        cd "$buildDIR" || exit
+        cd "$PKG_BUILD" || exit
 
         # Compile as opensource, accepting LGPL conditions (yes)
-        echo yes | $QT_SOURCE_DIR/configure \
-            -prefix $QT_ARCH_PATH \
+        echo yes | "$PKG_SOURCE"/configure \
+            -prefix "$PKG_PREFIX" \
             -opensource \
             $configOpt \
         && time make -j $WM_NCOMPPROCS \
         && make install \
-        && echo "Built: Qt-$qtVERSION" \
-        && finalizeQt
+        && echo "Built: $PACKAGE" \
+        && finalizeQt "$PKG_PREFIX"
     ) || {
-        echo "Error building: Qt-$qtVERSION"
+        echo "Error building: $PACKAGE"
         exit 1
     }
 fi
diff --git a/makeSCOTCH b/makeSCOTCH
--- a/makeSCOTCH
+++ b/makeSCOTCH
@@ -20,13 +20,15 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
 . "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
 #------------------------------------------------------------------------------
 _foamConfig scotch  # Get SCOTCH_ARCH_PATH, SCOTCH_VERSION
@@ -35,6 +37,11 @@ PACKAGE="${SCOTCH_VERSION:-system}"
 
 unset withMPI
 case "$WM_MPLIB" in (*MPI*) [ "$FOAM_MPI" = dummy ] || withMPI=true ;; esac
+
+if nonStandardPlatforms  # Possibly unreliable inherited values
+then
+    unset SCOTCH_ARCH_PATH
+fi
 
 #------------------------------------------------------------------------------
 printVersions() { listPackageVersions scotch; exit 0; }
@@ -82,7 +89,8 @@ do
     -no-mpi)    unset withMPI ;;
     -no-extlib) optNoExtlib=true ;;  # Hidden option
 
-    scotch-[0-9]* | scotch-git | scotch_* )
+    scotch/ | sources/scotch* |\
+    scotch-[0-9]* | scotch-v[0-9]* | scotch-git | scotch_* )
         PACKAGE="${1%%/}"
         unset SCOTCH_ARCH_PATH  # Avoid inconsistency
         ;;
@@ -118,7 +126,7 @@ fi
 #   *SOURCE  : location of original sources
 #   *PREFIX  : installation directory
 
-PKG_SOURCE="$sourceBASE/$PACKAGE"
+PKG_SOURCE="$(findSourceDir "$PACKAGE")"
 PACKAGE="$(basename "$PACKAGE")"
 PKG_PREFIX="$installBASE$WM_SIZE_OPTIONS/$PACKAGE"
 export GIT_DIR="$PKG_SOURCE/.git"
diff --git a/makeVTK b/makeVTK
--- a/makeVTK
+++ b/makeVTK
@@ -27,21 +27,21 @@
 # ----------------------------------------------
 # NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
 #------------------------------------------------------------------------------
-# Run from third-party directory only
-cd "${0%/*}" || exit
-wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
-    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
-    echo "    Check your OpenFOAM environment and installation"
-    exit 1
-}
-. etc/tools/ThirdPartyFunctions
-. etc/tools/ParaViewFunctions
-. etc/tools/vtkFunctions
+if :    # Run from third-party directory
+then
+    cd "${0%/*}" || exit
+    wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
+        echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
+        echo "    Check your OpenFOAM environment and installation"
+        exit 1
+    }
+fi
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ParaViewFunctions
+. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/vtkFunctions
 #------------------------------------------------------------------------------
-
-unset vtk_version mesa_version                           # Purge current values
-
-# vtk version from OpenFOAM etc/config.sh file:
+# Obtain version from OpenFOAM etc/config.sh file:
+unset vtk_version mesa_version              # Purge current values
 _foamConfig vtk
 
 VTK_VERSION="$vtk_version"
@@ -63,12 +63,11 @@ then
 fi
 
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printVersions() { listPackageVersions vtk; exit 0; }
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [vtk-VERSION] [CMAKE-OPTION]
+Usage: ${0##*/} [OPTION] [vtk-VERSION] [CMAKE-OPTION]
 options:
   -gcc              Force use of gcc/g++
   -cmake PATH       with cmake from the given path
@@ -87,7 +86,8 @@ options:
   -buildType NAME   specify the build type (default: Release)
   -suffix NAME      specify a suffix to distinguish the build
   -DNAME=VALUE      add cmake variable
-  -help
+  -list             List available unpacked source versions
+  -help             Display usage help
 
 The -no-FEATURE option can be used to forcibly disable these features:
   -no-gl2 | -no-mesa | -no-mpi
@@ -109,8 +109,8 @@ For finer control, the build stages can be selected or deselected individually:
   ->  \$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER/VTK-$VTK_VERSION$BUILD_SUFFIX
 
 USAGE
-    # showDownloadHint VTK
-    exit 1
+    # showDownloadHint vtk
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 exportCompiler minimal  # Minimal compiler info for CMake/configure
@@ -124,11 +124,14 @@ while [ "$#" -gt 0 ]
 do
     case "$1" in
     '') ;;      # Ignore empty
-    -h | -help) usage   ;;
+    -h | -help*) printHelp;;
+    -list)      printVersions;;
     -gcc)       useGcc  ;;
 
-    [0-9]* | vtk-[0-9]* | VTK-[0-9]*) # VTK version
-        setVtkVersion "${1%%/}"
+    # VTK version
+    paraview/* | vtk/* | sources/paraview* | sources/vtk* |\
+    [0-9]* | vtk-[0-9]* | VTK-[0-9]*)
+        setVtkVersion "$(basename "$1")"
         ;;
     -D[A-Z]*=* | [A-Z]*=*)  # cmake variables
         addCMakeVariable "$1"
diff --git a/minCmake b/minCmake
--- a/minCmake
+++ b/minCmake
@@ -6,7 +6,7 @@
 #   \\  /    A nd           | www.openfoam.com
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
-#     Copyright (C) 2016-2020 OpenCFD Ltd.
+#     Copyright (C) 2016-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
@@ -28,12 +28,10 @@ wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
     exit 1
 }
 #------------------------------------------------------------------------------
-usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+printHelp() {
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] [dir1 ... dirN]
+Usage: ${0##*/} [OPTION] [dir1 ... dirN]
 options:
   -help
 
@@ -41,18 +39,17 @@ options:
 * Without any arguments, select all first level directories.
 
 USAGE
-    exit 1
+    exit 0  # Clean exit
 }
 #------------------------------------------------------------------------------
 # Parse options
 while [ "$#" -gt 0 ]
 do
     case "$1" in
-    -h | -help)
-        usage
-        ;;
+    -h | -help*) printHelp;;
     -*)
-        usage "unknown option: '$1'"
+        echo "$0: Error unknown option: '$1'" 1>&2
+        exit 1
         ;;
     *)
         break
@@ -62,22 +59,50 @@ do
 done
 
 # Nothing specified - use first level of unpacked directories
-[ "$#" -gt 0 ] || set -- $(find -mindepth 1 -maxdepth 1 -type d)
+if [ "$#" -eq 0 ]
+then
+set -- \
+$(
+    echo "searching..." 1>&2
+    find . -mindepth 2 -maxdepth 2 -name CMakeLists.txt
+    for dir in sources/*
+    do
+        [ -d "$dir" ] || continue
+        ## echo "search <$dir>" 1>&2
+        depth=1
+        # Is sources/pkg/pkg-version ?
+        if [ "$(echo "$dir" | sed -e 's#.*/[a-z][a-z]*##' | wc -w)" = 0 ]
+        then
+            depth=2
+        fi
+        find "$dir" -maxdepth "$depth" -name CMakeLists.txt
+    done
+)
+fi
 
+
+echo "processing..." 1>&2
 for dir
 do
     dir="${dir#./}" # Remove leading  "./"
     dir="${dir%/}"  # Remove trailing "/"
 
+    case "$dir" in
+        (*/CMakeLists.txt) file="$dir" ;;
+        (*) file="$dir/CMakeLists.txt" ;;
+    esac
+    dir="$(dirname "$file")"
+    dir="$(basename "$dir")"
+
     min=$(sed -n \
         -e 's/^.*cmake_minimum.*VERSION *\([0-9.][0-9.]*\).*/\1/p' \
-        "$dir/CMakeLists.txt" \
+        "$file" \
         2>/dev/null | head -1)
 
     if [ -n "$min" ]
     then
         # Remove trailing ".0" from version
-        echo "${min%.0}" "${dir#sources/}"
+        echo "${min%.0}" "$dir"
     fi
 
 done \
