STYLE: provide 'die' as alternative to 'usage'
- make option parsing more consistent

diff --git a/etc/tools/ThirdPartyFunctions b/etc/tools/ThirdPartyFunctions
--- a/etc/tools/ThirdPartyFunctions
+++ b/etc/tools/ThirdPartyFunctions
@@ -61,6 +61,17 @@ then
 fi
 
 
+# Report error and exit
+die()
+{
+    exec 1>&2
+    echo
+    echo "Error: see '${0##*/} -help' for usage"
+    while [ "$#" -ge 1 ]; do echo "    $1"; shift; done
+    echo
+    exit 1
+}
+
 # Test if it matches "*-none"
 _foamIsNone()
 {
diff --git a/makeCCMIO b/makeCCMIO
--- a/makeCCMIO
+++ b/makeCCMIO
@@ -90,23 +90,19 @@ do
         ;;
     lib|libso)
         targetType="$1"
-        shift
         ;;
     libccmio-[1-9]*)
         ccmioPACKAGE="${1%%/}"
-        shift
         ;;
     *)
-        usage "unknown option/argument: '$*'"
+        die "unknown option/argument: '$1'"
         ;;
     esac
+    shift
 done
 
-# warn if unavailable
-if [ ! -d ${ccmioPACKAGE} ]
-then
-    usage "missing source directory '$ccmioPACKAGE'"
-fi
+# assert: directory must be available
+[ -d "${ccmioPACKAGE}" ] || die "missing source directory '$ccmioPACKAGE'"
 
 
 #------------------------------------------------------------------------------
